### ISSUE TITLE
Thumbnail not visible

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2780] opened 2021-02-25 08:54 UTC
**Describe the bug**
Ratios and Proportional Reasoning Thumbnail is not visible on landscape

**To Reproduce**
1. Go to Home Screen
2. Landscape Orientation
3. Scroll to the bottom
4. last card, the `Ratios and Proportional Reasoning` image is not visible

**Expected behavior**
The image should be visible no matter which orientation

**Screenshots**
https://photos.app.goo.gl/6ZYnTvtBNv2UPAb79

**Comment by Akshat-gour** [comment] 2021-02-28 07:33
@anandwana001 
Assign me

**Comment by Akshat-gour** [comment] 2021-02-28 10:17
@anandwana001 
I cannot reproduce the error
I tested it on physical device(C7 pro API 26) and on Emulator(pixel XL API 30)
the thumbnail is visible

![image](https://user-images.githubusercontent.com/60266468/109414950-e0b9be00-79db-11eb-9054-b9021f377159.png)

**Comment by MaskedCarrot** [comment] 2021-02-28 11:52
@Akshat-gour I checked this and I was able to produce the error. Though the error appeared irregularly on some of the orientation change when I performed multiple orientation changes.

**Comment by Akshat-gour** [comment] 2021-03-06 13:05
@anandwana001 
Can U give me guidence were can be the error 
I looked but could not find the file in which error could be

**Comment by anandwana001** [comment] 2021-03-07 01:52
@MaskedCarrot Could you help here? Also, If you could mention the steps you had done to produce this error as mentioned in your earlier comment will be helpful.

**Comment by MaskedCarrot** [comment] 2021-03-07 08:13
@Akshat-gour you can start by looking into `topicSummaryViewModel` and `topic_info_fragment.xml` because we set the thumbnail in `topic_info_fragment.xml`

**Comment by MaskedCarrot** [comment] 2021-03-07 08:19
Steps to reproduce this issue:
1. Go to the home screen
2. change device orientation to landscape
3. scroll down to all topic to see the error in topic `Ratio and Proportional Reasoning`
4. if  the error is not reproduced, change orientation to portrait and go back to step 2

**Comment by Akshat-gour** [comment] 2021-03-10 18:25
@anandwana001 
@MaskedCarrot 
**topic_info_fragment.xml** is this layout(Screen Shot) but we need home screen layout of **all topic**
I found this **topic_summary_view.xml** file in which one topic view is created and image is set.
But not able to find how these each card view is placed on **home Screen**
**I think Problem Could be there.**
I also Found the Custom view used to set image **LessonThumbnailImageView.kt** and **ImageViewBindingAdapters.java**
**Can You Help**
![WhatsApp Image 2021-03-09 at 2 00 14 PM](https://user-images.githubusercontent.com/60266468/110441490-d7b5a480-80df-11eb-85e1-67944894060d.jpeg)

**Comment by ArpitShukIa** [comment] 2021-03-11 14:50
How to reproduce :

https://user-images.githubusercontent.com/51705072/110802625-5fe4a700-82a4-11eb-9cdb-e22160a50296.mp4

I added some extra items in the list. Clearly, as the list grows in size, more and more thumbnails will start disappearing.
 
From what I found, the bug lies in the `checkIfLoadingIsPossible` function of `LessonThumbnailImageView`.
```
private fun checkIfLoadingIsPossible() {
    if (::entityId.isInitialized &&
      ::entityType.isInitialized &&
      ::lessonThumbnail.isInitialized &&
      ::thumbnailDownloadUrlTemplate.isInitialized &&
      ::resourceBucketName.isInitialized &&
      ::gcsPrefix.isInitialized &&
      ::imageLoader.isInitialized &&
      ::logger.isInitialized
    ) {
      loadLessonThumbnail()
    }
  }
```
This function is called after initialising any of `entityId`, `entityType` and `lessonThumbnail`. The problem occurs when these three are initialised first, but the other dependencies haven't been yet injected and hence `loadLessonThumbnail` is never called for that `LessonThumbnailImageView`

**Comment by ArpitShukIa** [comment] 2021-03-11 15:02
One possible solution can be to wait for the dependencies to be injected by Dagger after the first 3 items are initialized.

@anandwana001 Any suggestions on how this can be achieved?

**Comment by anandwana001** [comment] 2021-03-16 05:18
Adding wait explicitly sounds like another fix, not a solution.  Can we try another approach where we can play with this initialization check in a different way. 
Adding @rt4914 for any update on this.

**Comment by rt4914** [comment] 2021-03-16 08:38
> One possible solution can be to wait for the dependencies to be injected by Dagger after the first 3 items are initialized.
> 
> @anandwana001 Any suggestions on how this can be achieved?

@ArpitShukIa Can you try to call `checkIfLoadingIsPossible` after everyone one of these dependencies is initialised ?

**Comment by ArpitShukIa** [comment] 2021-03-16 08:41
@rt4914 That's the main issue I think. How can we know when have all the dependencies been initialized?

**Comment by ArpitShukIa** [comment] 2021-03-16 09:40
The only way I can think of right now is to simply wait for them to be injected. Something like:
```
private val allDependenciesInjected
  get() = ::thumbnailDownloadUrlTemplate.isInitialized &&
    ::resourceBucketName.isInitialized &&
    ::gcsPrefix.isInitialized &&
    ::imageLoader.isInitialized &&
    ::logger.isInitialized

private fun checkIfLoadingIsPossible() {
  if (::entityId.isInitialized &&
    ::entityType.isInitialized &&
    ::lessonThumbnail.isInitialized
  ) {
    GlobalScope.launch(Dispatchers.Default) {
      while (!allDependenciesInjected);  // Empty loop
      withContext(Dispatchers.Main) {
        loadLessonThumbnail()
      }
    }
  }
}
```

**Comment by ArpitShukIa** [comment] 2021-03-23 12:31
@anandwana001 @rt4914 Can I work on this?

**Comment by anandwana001** [comment] 2021-03-23 12:59
@Akshat-gour are you still working on this?

**Comment by Akshat-gour** [comment] 2021-03-23 13:02
@anandwana001 
Actually, i am not able to find the solution to it.
u can Assign it to @ArpitShukIa

**Comment by ArpitShukIa** [comment] 2021-03-23 16:01
@anandwana001 Will it be okay to use [this](https://github.com/oppia/oppia-android/issues/2780#issuecomment-800106728) approach? (It does solve the problem)

**Comment by anandwana001** [comment] 2021-03-23 22:28
let's have a draft pr with this approach with the test case, and will review it.

**Comment by ArpitShukIa** [comment] 2021-03-24 13:09
@anandwana001 Okay, but can u tell what should be the test case. Will it have to iterate over all the topics in the recycler view and assert that their thumbnails are loaded?

**Comment by anandwana001** [comment] 2021-03-24 15:52
I guess this is something common to all the topics. So, I guess the problem we are solving here is:
Does the thumbnail of the last item is visible or not in landscape mode!! 
So this will be our test case.

**Comment by ArpitShukIa** [comment] 2021-03-24 16:42
@anandwana001 Actually dependencies are being injected in each View independent of any other View. So, just checking for the last item won't guarantee that all thumbnails have been loaded. And it looks like the problem exists in both portrait and landscape mode.

https://user-images.githubusercontent.com/51705072/112348155-9206f780-8ced-11eb-9d92-ba6aca73b01f.mp4

https://user-images.githubusercontent.com/51705072/112347989-64ba4980-8ced-11eb-9279-d952d0c1d16e.mp4

**Comment by anandwana001** [comment] 2021-03-25 02:03
@ArpitShukIa Should we test is all dependencies injected or not?

**Comment by ArpitShukIa** [comment] 2021-03-25 06:09
@anandwana001 In that case also we will have to check for all items in recycler views because each of them is independently requesting dependencies from Dagger.
I tried to figure out a way so that all instances of `LessonThumbnailImageView` in the recycler view can share common instances of dependencies (like passing dependencies from outside just like the way we are passing `entityId`, `entityType` & `lessonThumbnail`), but got no success yet.
With the current implementation of `LessonThumbnailImageView`, we will either have to write a test that checks for all items in the list OR just skip the testing part for this fix.

**Comment by anandwana001** [comment] 2021-03-30 05:43
What can be a possible else case in `checkIfLoadingIsPossible`?

From the architecture view, what should we do if we don't have all the dependencies required by the dependent? 
Adding @Srikanth-Kb on thoughts on this pattern.

**Comment by ArpitShukIa** [comment] 2021-03-30 06:26
> What can be a possible else case in `checkIfLoadingIsPossible`?

If loading is not possible right now, we need to defer it to a later time (a few milliseconds).
What we need is a listener which is invoked when a lateinit is initialized. Since we don't have such a thing, waiting for it to be initialised seems like a possible solution to me.

**Comment by ArpitShukIa** [comment] 2021-04-05 04:12
@anandwana001 @Srikanth-Kb 
Should I create a PR using [this](https://github.com/oppia/oppia-android/issues/2780#issuecomment-800106728) method OR do you suggest any other better approach?

**Comment by anandwana001** [comment] 2021-04-05 05:25
Let's send a draft and will review it accordingly.

**Closed as completed** 2021-04-30 07:18 UTC
Labels: Z-ibt
