### ISSUE TITLE
[BUG]: Absence of fractions on Fraction lesson - android app - Portuguese version

### ISSUE THREAD

**Issue by ltcpaa** [oppia/oppia-android#5201] opened 2023-10-17 21:49 UTC
### Describe the bug

There are some issues in some chapters on Fractions topic that are not exhibiting the fraction, therefore the user can't see what math operation they need to do.
Until now I've checked lessons 1 to 3, and both 2 and 3 have the same bug. I think it's best to check them all

### Steps To Reproduce

Go to chapter 2 and keep doing the lessons, you will see the absence of the fraction

### Screenshots/Videos

The absence of fraction is highlighted with the yellow arrow
![Chapter 2](https://github.com/oppia/oppia/assets/148286089/d1e52107-444f-40a8-9b24-6cb088348083)
![Chapter 2 (1)](https://github.com/oppia/oppia/assets/148286089/be0f97c0-db09-4e73-9e03-505e88b28b06)
![Chapter 3](https://github.com/oppia/oppia/assets/148286089/f40aa8f1-b49c-42b8-9487-cb66babe66c6)

### What device are you using?

Mobile

### Operating System

Android

### Tips for developers

Before tackling the bug, please use `git bisect` (see https://git-scm.com/docs/git-bisect) to investigate which PR caused it (you only need to go back as far as commit https://github.com/oppia/oppia/commits/9a334e9). If you find the PR, leave a comment on this issue pointing to it, or just say that it happened before commit 9a334e9 if you could reproduce it there. This will help us fix the issue by reverting the faulty PR.

Also, if this is your first issue, please make sure to follow https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue and https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up before claiming it. Thanks!

**Comment by adhiamboperes** [comment] 2023-10-19 07:55
Closing this since it's a duplicate of #5112

**Closed as duplicate by adhiamboperes** 2023-10-19 07:55 UTC
Labels: bug
