### ISSUE TITLE
[BUG]: Home screen topics Grid view unaligned after coming back from Lesson

### ISSUE THREAD

**Issue by MohitGupta121** [oppia/oppia-android#5150] opened 2023-09-12 18:08 UTC
### Describe the bug

Home screen topics Grid view unaligned after coming back from Lesson

https://github.com/oppia/oppia-android/assets/76530270/48d916d5-6ed1-4914-9d16-70c865d83c0f

### Steps To Reproduce

Go to any topic and then any lesson
Go back by (System or Navigation)
See the Topic Grids now

### Expected Behavior

Topic Grid should remain aligned.

### What device/emulator are you using?

Poco M2 Pro

### Which Android version is your device/emulator running?

Android 11

### Which version of the Oppia Android app are you using?

0.11-oppia-f0837d22fe

**Comment by Kshitiz-Mhto** [comment] 2023-09-18 11:09
I am new to Oppia-Android project, I would like to work on this issue, could you plz assign it to me? @adhiamboperes  @MohitGupta121

**Comment by adhiamboperes** [comment] 2023-09-18 11:58
> I am new to Oppia-Android project, I would like to work on this issue, could you plz assign it to me? @adhiamboperes @MohitGupta121


Could you please give a brief description of how you would go about solving this.

**Comment by adhiamboperes** [comment] 2023-09-18 12:02
This happens on tablets as well.
|||
|--|--|
|![Screenshot_1695036566](https://github.com/oppia/oppia-android/assets/59600948/653ca091-2db4-423a-87cf-bb9efb933c0c)| ![Screenshot_1695036506](https://github.com/oppia/oppia-android/assets/59600948/9443f1e6-ce5a-4c3c-94a3-7d6300a96989)|

**Comment by MohitGupta121** [comment] 2023-09-18 12:03
Thanks @adhiamboperes for tablet investigation.

**Comment by geektan123** [comment] 2023-09-19 19:02
Assign#5150

**Comment by adhiamboperes** [comment] 2023-09-22 09:14
> Assign#5150

Hi, in order to be assigned any issue,  please give a brief description of how you would go about solving it.

**Comment by nikitaevg** [comment] 2023-09-22 20:06
Hey there!

I want to work on this project as well.

I tried to understand what's going on here, I failed:). It has to do something with margins ([this](https://github.com/oppia/oppia-android/blob/cfce93c26bd3a22bcb80313908b36bb26f8aabae/app/src/main/java/org/oppia/android/app/home/topiclist/TopicSummaryViewModel.kt#L61) function). 

I had some non viable hypothesis. One interesting thing here is that when this bug happens this function I linked first is called for the 5th (last) element and only then for 0th, 1st...

Anyway, I came up with [this](https://github.com/nikitaevg/oppia-android/commit/023d5b057f29a6cc45667999336c07c8c3f921fa) solution. I don't know why it works, but the code becomes simpler and it works - the problem doesn't appear anymore, see the [video](https://drive.google.com/file/d/1B7GUxegD3-XXFbbMO-3GLeYjuzAnFbG6/view?usp=sharing). I checked it on Pixel 3 and Pixel C. 

I understand it changes the layout, but I think it's not that noticeable. I also understand it's not a proper solution, but it works:) See the new layout for Pixel 3 and Pixel C attached.

WDYT about this approach?

[Pixel3](https://github.com/oppia/oppia-android/assets/6707908/d9964d42-b79e-4cf2-9142-dfedca142188)
[Pixel3_landscape](https://github.com/oppia/oppia-android/assets/6707908/32ca96d0-7ed0-48f1-ba5d-d72df66759a9)
[Pixel C](https://github.com/oppia/oppia-android/assets/6707908/b04efcf5-9bfd-4e08-9e92-74274da5854e)

**Comment by seanlip** [comment] 2023-09-23 17:52
Hi @nikitaevg -- thanks for this! Just from the PM side -- in the new layout, I think that the tiles in the right column in the Pixel 3 mocks are too close to the right edge of the screen. The margin should be consistent on the left and on the right. Is that achievable with your approach?

Also, I suggest showing what the equivalent mocks are for the current codebase so that the difference between the old/new ones can be seen more easily,

@adhiamboperes do you have any thoughts on the technical approach used here? Just as an FYI I found the relevant PR that introduced the changes (using the `blame` functionality in GitHub): see https://github.com/oppia/oppia-android/pull/2246/files#diff-9d65508457d46773757a6d2bb48b791b0dee5f9fb9e46c673a808c5de2294172R49 -- @nikitaevg maybe the comments and context there might be interesting as well.

**Comment by nikitaevg** [comment] 2023-09-24 10:34
Hey Sean!

Thanks for your comment! Yeah, it was my bad they were inconsistent on the left and right. I thought it was like this before. Sure, I don't want to break it:)

I found a real problem here. My new proposal is [here](https://github.com/nikitaevg/oppia-android/commit/961cf00ef3d90a8ea17d2976816001da51fd4196), will create a proper PR soon. 

The gist is these cards that become unaligned - they are being reused after returning to the main screen. Their margin is updated in the code, but the RecyclerView is not notified about those updates.

Check [this](https://github.com/oppia/oppia-android/assets/6707908/c7f8ca50-6590-4497-9b25-7cc5714c8466) video where you can see the bug is gone.

**Comment by adhiamboperes** [comment] 2023-09-24 10:56
> Hey Sean!
> 
> Thanks for your comment! Yeah, it was my bad they were inconsistent on the left and right. I thought it was like this before. Sure, I don't want to break it:)
> 
> I found a real problem here. My new proposal is [here](https://github.com/nikitaevg/oppia-android/commit/961cf00ef3d90a8ea17d2976816001da51fd4196), will create a proper PR soon.
> 
> The gist is these cards that become unaligned - they are being reused after returning to the main screen. Their margin is updated in the code, but the RecyclerView is not notified about those updates.
> 
> Check [this](https://github.com/oppia/oppia-android/assets/6707908/c7f8ca50-6590-4497-9b25-7cc5714c8466) video where you can see the bug is gone.


Hi,
I think this approach is better and it is consistent with my own investigation into the root cause of the bug as well.

**Comment by adhiamboperes** [comment] 2023-11-06 10:49
@nikitaevg proposed calling `View.setLayoutParams()` instead of `View.requestLayout()` in [MarginBindingAdapters](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/databinding/MarginBindingAdapters.java) in #5160. 

`View.setLayoutParams()` sets the layout parameters associated with this view. These supply parameters to the parent of this view specifying how it should be arranged. 
`View.requestLayout() ` should be called when something has changed which has invalidated the layout of this view. This will schedule a layout pass of the view tree. View.setLayoutParams() calls this method. At a glance, this does not handle the provided layout params, unlike the other method.

We need to test this code to prevent regressions in the UI, and the first step is to set up a test that does something very similar to the  bug and see if we can repro the breakage in Robolectric, then we can step-debug to see what is causing the breakage, and set up a proper test for the code.
- This means setting up the test in HomeFragmentTest which has the layout under test.
- Observe the behavior when manually reproing the issue and try to turn it into a test. This acts like a debuggable environment for analyzing android.

**Comment by Abinash6000** [comment] 2023-11-21 13:06
Unable to reproduce the error. Am I doing something wrong?

https://github.com/oppia/oppia-android/assets/110354418/6cfe557c-b42e-4501-883a-0214b50a6685

**Comment by adhiamboperes** [comment] 2023-11-22 01:13
Hi @Abinash6000, could you please try to repro this on a tablet device like a nexus 9?

**Comment by Abinash6000** [comment] 2023-11-22 11:03
Still unable to reproduce the error.

https://github.com/oppia/oppia-android/assets/110354418/dea14435-52df-4d20-8836-6f2eed781cf3


https://github.com/oppia/oppia-android/assets/110354418/8c923a29-be1d-4061-ae41-aba4960945bd

**Comment by AyeshaLoladia** [comment] 2024-02-29 14:14
Hii, it would be of great help if anyone let's me know whether this issue has been solved yet or not. I would like to work on it

**Comment by adhiamboperes** [comment] 2024-03-01 09:16
@AyeshaLoladia, please try to reproduce this issue on mobile and tablet emulators and then let us know so we can assign it to you!

**Comment by Vinay-Khanagavi** [comment] 2024-10-19 12:19
@MohitGupta121  It's about a year since this issue was created why has nobody solved this issue, I just saw this bug and wanted to open an issue and found It already exists and it is a terrible sign for any app,
it would be better if you could make this impact medium from low, Thank you

**Comment by seanlip** [comment] 2024-10-28 23:28
@Vinay-Khanagavi Thanks for the note! I agree with you that it is medium-impact, and I have updated the label accordingly.

**Comment by TanishMoral11** [comment] 2024-11-02 11:50
Hey @adhiamboperes , I’d like to start working on this issue, but I noticed PR #5160 . already seems to address it effectively. 
Could you let me know if there were any specific concerns that prevented it from being merged? 
This would help me understand how to proceed or make any needed improvements. 
Thank you!

**Comment by adhiamboperes** [comment] 2024-11-02 12:11
@TanishMoral11, there were some incomplete tests and the contributor abandoned the PR. The solution is otherwise acceptable

**Comment by TanishMoral11** [comment] 2024-11-02 14:49
Thank you for clarifying, @adhiamboperes !

Would it be alright if I submit a new PR with the same changes and ensure that all the tests are completed? 
I’d be happy to take it forward and address any additional requirements if needed. 
Thank you!

**Comment by adhiamboperes** [comment] 2024-11-02 15:12
Assigned this issue to you @TanishMoral11

**Closed as completed** 2024-12-20 19:59 UTC
Labels: good first issue, Impact: Medium, bug, Work: Medium
