### ISSUE TITLE
"Continue" Button increased its top/bottom padding

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2142] opened 2020-11-20 21:02 UTC
There are several instances where the top/bottom padding of the continue button increases. After tapping "Continue" on one page, the "Continue" button on the following page appears taller. [[Video](https://drive.google.com/file/d/1g4kJB4UuD4D-ZpgA64EAqUMrmdmg1hbQ/view?usp=sharing)]
The video is recorded in topic **Place Values**, story **Jaime's Adventures in the Arcade**, **Chapter 1: What are the place values**?

**Comment by ForgottenProgramme** [comment] 2020-11-24 19:12
Hey, @mschanteltc !
I saw that video you attached. I think the size of the 'continue' button is changing according to the length of the card above it.

**Comment by 7phalange7** [comment] 2020-11-28 06:59
Hello, @mschanteltc 
May I work on this ?  

The issue is probably because the continue button height is constrained to the parent but the parent layout has height as `wrap_content`.

**Comment by rt4914** [comment] 2020-11-30 12:18
> Hello, @mschanteltc
> May I work on this ?
> 
> The issue is probably because the continue button height is constrained to the parent but the parent layout has height as `wrap_content`.

@7phalange7 Assigning this to you. In future, you don't need to wait for approval if you are confident about the issue. You can just check all the comments and if the issue is not assigned to anyone else you can leave a comment and start working, something like `I am working on this`.

**Closed as completed** 2021-01-11 03:10 UTC
Labels: good first issue, Z-ibt
