### ISSUE TITLE
Opening screen distortion

### ISSUE THREAD

**Issue by Victor-Titan** [oppia/oppia-android#3193] opened 2021-05-13 15:38 UTC
**Describe the bug**
The start screen of the app distorts when showing the Oppia logo before transitioning to the user select screen. It doesn't happen always.

**To Reproduce**
1. Clear the app from the recent apps pane
2. Open the Oppia Android App

**Expected behavior**
The screen should not distort and vertically shift the logo before showing us the select user menu.

**Screenshots**

https://user-images.githubusercontent.com/54766268/118144892-99fc3180-b42a-11eb-8646-86c43e14f60e.mp4

https://user-images.githubusercontent.com/54766268/118149388-21e43a80-b42f-11eb-8696-ca64b1711017.mp4

**Device**
For the first video
- Device/emulator being used: Pixel 3 XL Emulator
- SDK version: Android 10(API 29)

For the second video
- Device/emulator being used: Poco X3 (Realtime device)
- SDK version: Android 10 (API 29)

**Additional context**
This only happens some times on real time when your device is a little slow. To reproduce it on the emulator, just open the app after clearing it once from the recent apps pane.

**Comment by pravesh00** [comment] 2021-05-21 16:20
Can I work on this?

**Comment by Victor-Titan** [comment] 2021-05-21 22:14
@pravesh00 sure!

**Comment by anandwana001** [comment] 2021-06-21 20:19
@pravesh00 any update on this?

**Comment by pravesh00** [comment] 2021-06-21 20:52
@anandwana001 I am not working right now and please unassign me so other contributors can work.

**Comment by seanlip** [comment] 2024-09-08 09:16
Duplicate of #2652, closing.

**Closed as duplicate by seanlip** 2024-09-08 09:16 UTC
Labels: Priority: Nice-to-have, Impact: Low, Z-ibt, bug
