### ISSUE TITLE
The solution displayed is incorrect for the lesson 'What are the place values'

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4299] opened 2022-04-14 09:31 UTC
**Describe the bug**
Solution displayed is incorrect for the lesson 'What is place value'

**To Reproduce**
1. Go to 'Place Values'
2. Click on 'Lessons'- Select '1. What are the place values'
3. Click on Continue to get to the question page
4. Enter the wrong answer and get the hint
5. Enter wrong answer and wait for sometime to get solution
6. Click on Reveal Solution and click on Reveal button

**Expected behavior**
The only solution is : 4 should be displayed

Actual Result:
The only solution is : 0/0 is displayed

**Demonstration**
![Screenshot 2022-04-14 3 00 18 PM](https://user-images.githubusercontent.com/101634267/163357004-0894329b-84fa-4f41-bc4d-8dffe9dfcd98.png)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment] 2022-04-14 19:57
Thanks @KolliAnitha.

Marking this as a duplicate of #3956 since I think both are numeric interaction cases (and the broader tracking issue is #1050).

**Closed as not planned by BenHenning** 2022-04-14 19:57 UTC
Labels: Z-ibt
