### ISSUE TITLE
After changing the Reading text size to Extra large in Options and on opening a chapter the first page is still seen in Medium size

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4714] opened 2022-11-14 03:27 UTC
**Describe the bug**
After changing the Reading text size to Extra large in Options and on opening a chapter the first page is still seen in Medium size

**To Reproduce**
1. Click on menu bar options in Home page- Select Options
3. Click on Reading Text size - select Extra Large
4. Open any Topic- Ratios and Proportional Reasoning
5. See the text is displayed in Medium
6. Click on Continue
7. The next pages are seen in Extra Large

**Expected behavior**
Even the first page should be displayed in Extra Large size

**Demonstration**

https://user-images.githubusercontent.com/101634267/201568818-a5435d15-0353-4f78-a283-11fdd84345b8.mp4

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android version 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment] 2022-11-15 00:38
@KolliAnitha I'm slightly confused here. The issue description & title makes it sound like changing the reading text size to extra large doesn't resize the lesson text, but from the video it does seem to be doing that. Is the actual issue that non-lesson text isn't also being resized, or am I misunderstanding the problem being reported here?

**Comment by KolliAnitha** [comment] 2022-11-15 00:46
@BenHenning, In the video it is seen that the first page after opening the lesson is not resized to extra large. The other pages in the lesson are resized correctly.

**Comment by BenHenning** [comment] 2022-11-15 00:50
Just to clarify @KolliAnitha is "first page" the page shown at 0:35 in the video or 0:38 in the video?

**Comment by KolliAnitha** [comment] 2022-11-15 01:14
The page shown at 00:35 is in medium size.

**Comment by BenHenning** [comment] 2022-11-15 01:20
Ah okay, thanks for clarifying! The resume lesson screen isn't actually part of the player itself, so this fits under #1491 as the eventual goal is to allow general text resizing broadly in the app.

Considering this to be a duplicate of that issue.

**Closed as not planned by BenHenning** 2022-11-15 01:20 UTC
