### ISSUE TITLE
No back button 

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#680] opened 2020-02-20 20:58 UTC
**Issue Description**
There is no presence of a back button in the toolbar which hampers UX. 

**Ideal Situation** 
In my opinion, the toolbar must contain a back button that takes the user to the previous activity. 

**Screenshot** 
Current - 
<img src="https://user-images.githubusercontent.com/53938155/74977683-2ea6f800-5451-11ea-9959-67c6d99ed7bf.png" width=200/>

**Would you like to work on this issue** 
Yes.

**Comment by PrarabdhGarg** [comment] 2020-02-21 07:01
@Sarthak2601 possible duplicate of Issue #654

**Comment by Sarthak2601** [comment] 2020-02-21 07:40
@PrarabdhGarg Oh Okay. Can I link my PR to that issue and close this one ?

**Comment by PrarabdhGarg** [comment] 2020-02-21 07:45
Perhaps @rt4914 might be able to decide that

**Comment by rt4914** [comment] 2020-02-21 08:05
@PrarabdhGarg @Sarthak2601 Actually this is not an issue, as the Navigation Drawer icon in topics have been kept intentionally. Therefore closing this issue and its respective PR for now.

**Closed as completed by rt4914** 2020-02-21 08:05 UTC
Labels: Z-ibt
