### ISSUE TITLE
[BUG]:  RecyclerView in App Language does not appear

### ISSUE THREAD

**Issue by sandy99405** [oppia/oppia-android#5281] opened 2023-12-22 02:38 UTC
### Describe the bug

There are no App Language options and no Recycler View with radio buttons unlike Preferred Audio Language.
While debugging, the oppiaLanguage is set to LANGUAGE_UNSPECIFIED.

#### 2) log in to the account and click on the burger option in Home 
 #### 3) go to options>App Language

### Expected Behavior

The App Language Fragment need to show the RecyclerView containing the Radio Button VIews in it.

### Screenshots/Videos

https://github.com/oppia/oppia-android/assets/55664068/63ff1881-5689-44e7-bc8f-14908a625db2

### What device/emulator are you using?

Samsung M21 Model name : SM-M215G/DS 

### Which Android version is your device/emulator running?

Android Version - 13

**Comment by theMr17** [comment] 2023-12-22 03:10
Hi @sandy99405, thank you for bringing up the issue. But it seems to be a duplicate of #5106.

**Comment by seanlip** [comment] 2023-12-22 14:13
Closing as duplicate of #5106 (but @sandy99405 please feel free to reopen if you disagree with that assessment, thanks!)

@theMr17 Thanks for identifying the duplicate issue.

**Closed as duplicate by seanlip** 2023-12-22 14:13 UTC
Labels: bug

**Comment by sandy99405** [comment] 2023-12-23 01:58
It's ok @seanlip . I will work on the original(https://github.com/oppia/oppia-android/issues/5106) issue itself. Thank you :)
