### ISSUE TITLE
Images are not fully displayed

### ISSUE THREAD

**Issue by isalooo** [oppia/oppia-android#3345] opened 2021-06-19 13:12 UTC
**Describe the bug**
Critical text in images is cut off. This makes it difficult for users to learn the math concepts. 

**To Reproduce**

In the place values lesson, there are multiple images are not fully displayed. 

**Expected behavior**
Images should be fully displayed. 

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot_20210526-055327_Oppia](https://user-images.githubusercontent.com/82181327/122643553-53c07f00-d108-11eb-95cd-00e8b12e7e14.jpg)
![Screenshot_20210526-055147_Oppia](https://user-images.githubusercontent.com/82181327/122643554-54f1ac00-d108-11eb-906f-6748d2facf2f.jpg)
![Screenshot_20210526-054559_Oppia](https://user-images.githubusercontent.com/82181327/122643556-558a4280-d108-11eb-8b46-dc0e60763689.jpg)

**Device** samsung Galaxy s9+
- Android version 8 

**Additional context**

**Comment by rt4914** [comment] 2021-11-18 16:45
@rishidyno Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by TheSwarnim** [comment] 2022-01-29 16:19
Hi, @rt4914 I would like to work on this issue. Please assign it to me.

**Comment by TheSwarnim** [comment] 2022-01-31 15:32
Hi @rishidyno and @rt4914, could you tell me how can I produce the same behavior. I'm not able to find the place value session in the app

**Comment by rt4914** [comment] 2022-02-02 07:11
@TheSwarnim This has been explained in meeting but for reference adding it here too.

1. The issue is that images are cut-off and it can be because of two reasons (a.) the images are two big (b.) the images are the last thing in rich text. I think (b.) might be the reason because all the above screenshots show that the images are last part of rich-text.
2. The screenshots displayed above are from alpha app and therefore we cannot find them in current develop code. 
3. To reproduce them visit the "What is a Fraction?" exploration content in https://github.com/oppia/oppia-android/blob/develop/domain/src/main/assets/umPkwp0L1M0-.json and https://github.com/oppia/oppia-android/blob/develop/domain/src/main/assets/umPkwp0L1M0-.textproto and edit the `states` such that you can create a case where there are images at the bottom and there is not content after that image.

**Comment by TheSwarnim** [comment] 2022-02-02 07:26
Thanks, Rajat for your reference. It will help me a lot.

**Comment by BenHenning** [comment] 2022-06-10 01:26
For searching context, this issue was found in 0.5-alpha (MR2).

**Comment by adhiamboperes** [comment] 2022-11-16 19:23
> @TheSwarnim This has been explained in meeting but for reference adding it here too.
> 
> 1. The issue is that images are cut-off and it can be because of two reasons (a.) the images are two big (b.) the images are the last thing in rich text. I think (b.) might be the reason because all the above screenshots show that the images are last part of rich-text.
> 2. The screenshots displayed above are from alpha app and therefore we cannot find them in current develop code.
> 3. To reproduce them visit the "What is a Fraction?" exploration content in https://github.com/oppia/oppia-android/blob/develop/domain/src/main/assets/umPkwp0L1M0-.json and https://github.com/oppia/oppia-android/blob/develop/domain/src/main/assets/umPkwp0L1M0-.textproto and edit the `states` such that you can create a case where there are images at the bottom and there is not content after that image.


@BenHenning, I have tried several means to reproduce this, to no avail. I don't think this is still an issue.

Steps taken to reproduce:
1. Created a virtual device that simulates the reported device, _Galaxy S9+_ - 6.2", Oreo, 1440x2960px, 4GB RAM.
2. Created a virtual device with a small screen - 4"
3. Used a 6.7" physical device
4. Used the quoted instructions to simulate the conditions for image being cropped. See below:

|1|2|3|
| -------------| -----| -----|
|![Screenshot_1668625992](https://user-images.githubusercontent.com/59600948/202273730-5294d4b7-ec75-4649-b3a8-03d22ec5f3f9.png) |![Screenshot_1668625757](https://user-images.githubusercontent.com/59600948/202273858-78162201-e310-4051-acca-1cb45e631313.png) |![Screenshot_1668625659](https://user-images.githubusercontent.com/59600948/202273925-5e34de7b-66f6-483b-b3f9-7391a747a335.png)|

**Comment by BenHenning** [comment] 2022-11-17 01:31
Thanks @adhiamboperes. This may not actually be an issue anymore as we’ve made changes to image handling since it was filed. However, I want to be sure the related issue that you filed is not a flake as that might mean this is still sometimes a problem.

**Comment by BenHenning** [comment] 2022-11-17 10:02
See https://github.com/oppia/oppia-android/issues/4688#issuecomment-1318382684. I think per @adhiamboperes's findings, there isn't actually anything more to do here.

**Comment by KolliAnitha** [comment] 2023-06-12 13:11
Below few images are not displayed fully
![Screenshot_20230612-180537](https://github.com/oppia/oppia-android/assets/101634267/cd8335df-01ec-47e6-97b2-7f7244d95efb)
![Screenshot_20230612-180244](https://github.com/oppia/oppia-android/assets/101634267/cb9506d2-6d0d-4231-8a42-5f8ab15cf4d4)
![Screenshot_20230612-180143](https://github.com/oppia/oppia-android/assets/101634267/432ebd60-10ae-4476-bd98-d11ba9268484)

**Comment by BenHenning** [comment] 2023-06-14 23:41
Spent a bit of time looking into this. UrlImageParser seems to be making some sort of layout mistake here where it's not resizing the image correctly to fit within its container. I actually wonder if we should just redo how we handle image resizing and push it to be within the draw function, instead, since then we have access to the Canvas's clip bounds (and know *exactly* how much space the image can take up). However, bounds still need to be computed in order for text line wrapping to work correctly, so this isn't a complete solution. More work is needed here, and given that enough of the images show in order to proceed I don't think we should block on this as changes to the core image flow risks breaking image sizing in other niche scenarios.

**Comment by seanlip** [comment] 2023-06-15 03:44
Thanks @BenHenning. Bumping this to 0.12.

**Comment by adhiamboperes** [comment] 2023-06-15 10:34
@BenHenning there are multiple problems with images being displayed, and we should definitely look into reworking the image display logic.
I created a theme in CLaM for this: https://github.com/orgs/oppia/projects/4/views/29.

The current implementation has issues with center aligning images that have a width greater than the view width after resizing. It also assumes that images that are to be displayed in a view with a wrap_content width don't have padding, which is basically not correct(this affects multiple choice interactions with images). Lastly, there's an issue computing image Rect(drawableLeft) if the image is part of a list, which makes me think that there is an issue with conflicting indentation computation with https://github.com/oppia/oppia-android/blob/74f39685add3a6633f6a806aae5b3a2eb3668959/utility/src/main/java/org/oppia/android/util/parser/html/ListItemLeadingMarginSpan.kt#L22

**Closed as completed** 2023-11-22 11:59 UTC
Labels: Impact: Medium, Z-ibt, bug, Work: Medium
