### ISSUE TITLE
[BUG]: Hint is empty for few questions

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#5049] opened 2023-06-12 06:15 UTC
**Describe the bug**
Hint is empty for a question in Fractions

**To Reproduce**
1. Go to 'Fractions' - What is a Fraction
2. Click on Continue till you go to the question 'what fraction is shown by the coloured part of this picture
3. Wait till the hint pops up
4. Click on the Hints- see that there is no hint displayed in the hints page

**Expected behavior**
Hint must be displayed with Show hint button

**Demonstration**
![hint](https://github.com/oppia/oppia-android/assets/101634267/b0b5d41b-7f62-49ee-8b8f-9b2f7275bfbc)

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.11-beta-8e0fcf19ac

**Comment by seanlip** [comment] 2023-06-12 06:17
@KolliAnitha Could you please screenshot the question as well, for better identification? Thanks.

**Comment by KolliAnitha** [comment] 2023-06-12 06:19
sure Sean
![question ](https://github.com/oppia/oppia-android/assets/101634267/f70fd7cb-47b5-4295-bc2a-fee8efac42ec)

**Comment by seanlip** [comment] 2023-06-12 06:23
Thanks -- on Web, there are actually no hints for this question, so the hint bar should not appear.

@adhiamboperes could you please investigate why this is happening? Thanks.

**Comment by KolliAnitha** [comment] 2023-06-12 08:53
Adding one more question with no hint
![hint (1)](https://github.com/oppia/oppia-android/assets/101634267/b6c39177-cd6e-4cf9-b325-f565772ee1f2)

**Comment by KolliAnitha** [comment] 2023-06-13 04:39
Observed few questions with no hints in What is a Ratio chapter
![Screenshot_20230613-100542](https://github.com/oppia/oppia-android/assets/101634267/1f5e2e37-cbfe-4b62-9d30-ef79bd9ff41d)

**Comment by BenHenning** [comment] 2023-06-14 23:39
This is caused by a pipeline issue:
https://github.com/oppia/oppia-android/blob/d3e2fd2ce3bcc9a5cdbe6fb577e4251ebfc80283/scripts/src/java/org/oppia/android/scripts/assets/DtoProtoToLegacyProtoConverter.kt#L316

A solution should only be set if one is present (to avoid it being a default proto). This is also the case for all other interaction types which support solutions.

**Comment by BenHenning** [comment] 2023-06-15 00:38
The fix is now checked into the pipeline branch & will be available on the next RC push of the release branch.

**Closed as completed by BenHenning** 2023-06-15 00:38 UTC
Labels: Impact: Medium, bug, Work: Medium

**Comment by KolliAnitha** [comment] 2023-06-16 17:13
Empty hints are not seen now in 0.11-beta-3343155232
