### ISSUE TITLE
Dark Mode support not working in Lessons Fragments

### ISSUE THREAD

**Issue by iampradeep-hr** [oppia/oppia-android#4711] opened 2022-11-12 21:24 UTC
**Describe the bug**
Dark Mode Support for the Lessons Fragment not working

**To Reproduce**

https://user-images.githubusercontent.com/81664507/201495052-338af93e-4fbe-4727-b0ca-6a37117593d5.mp4

**Expected behavior**
Dark mode not working in topic_lessons_fragment

**Environment**
- Device/emulator being used: <Xiaomi Redmi Note 11>
- Android or SDK version (Android 11)
- App version : 1.0

**Additional context**

**Comment by iampradeep-hr** [comment] 2022-11-12 21:25
I would like to work on this issue.

**Comment by BenHenning** [comment] 2022-11-15 00:43
Thanks for filing this @iampradeep-hr. I suspect this is fine to go ahead and start working on, but we should also check: @rt4914 is there already an issue tracking this work?

**Comment by iampradeep-hr** [comment] 2022-11-15 02:32
@BenHenning I have fixed it.Should I have to create a seperate git branch and push the code?

**Comment by iampradeep-hr** [comment] 2022-11-15 03:12
The issue is with the color resource specified for background attribute in topic_lessons_fragment.xml

**Comment by MohitGupta121** [comment] 2022-11-29 16:48
Thanks @iampradeep-hr for rasing issue.

Actually this issue is a duplicate of https://github.com/oppia/oppia-android/issues/4624 and work started on that issue.
So I'm closing this issue to avoid confusion.

**Closed as not planned by MohitGupta121** 2022-11-29 16:48 UTC
