### ISSUE TITLE
Continue button is not aligned properly when reading text size is extra large

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4361] opened 2022-05-16 11:01 UTC
**Describe the bug**
Continue button is not aligned properly when reading text size is extra large

**To Reproduce**
1. Go to 'Navigation menu'- Select Options
2. Click on 'Reading text size'- Change to Extra Large
3. Open any exploration
4. Scroll down to click on Continue

**Expected behavior**
Continue button should be aligned properly 

![Screenshot_2022-05-16-16-08-24-65_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/168579072-6b4d7d06-8969-4c28-8c1e-ca9f9759732c.jpg)

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

**Comment by saudAnwar786** [comment] 2022-05-18 03:22
@KolliAnitha  I can do this by changin text size

**Comment by BenHenning** [comment] 2022-05-18 08:34
Thanks for showing interest @saudAnwar786. I suggest addressing #4352 before tackling a second issue, though I think this is a good candidate.

Please note that this isn't quite as simple as changing text size. We want components like buttons to have consistent sizes throughout the app, so it's instead necessary to figure out how ensure the button is large enough to fit the text rather than shrinking the text.

**Comment by BenHenning** [comment] 2022-06-10 17:18
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by Chandra-Sekhar-Bala** [comment] 2022-06-21 17:36
Hey @BenHenning  can I work on this?

**Comment by BenHenning** [comment] 2022-06-22 02:32
Hi @Chandra-Sekhar-Bala! Thanks for showing interest in Oppia!

I see that you're a first-time contributor. I suggest heading over to our [onboarding wiki page](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#onboarding-instructions) for instructions on how to get started with contributing on Oppia. Once done, this issue is definitely available to be worked on.

**Comment by Chandra-Sekhar-Bala** [comment] 2022-06-22 11:39
Thanks for the reference @BenHenning. Successfully submitted CLA from and Oppia contributor survey form and read all docs. 
Think I'm ready to get started with this issue. I'll be needing more help in future steps, as I am just a beginner at open source.

**Comment by BenHenning** [comment] 2022-06-22 20:43
Sounds good @Chandra-Sekhar-Bala. In that case, I suggest mentioning that you'd like to work on this issue to your onboarding mentor once they reach out to you. Welcome to Oppia. :)

**Comment by Chandra-Sekhar-Bala** [comment] 2022-06-22 20:48
@BenHenning , Okay will do that and also thanks for that welcome too ☺️

**Comment by Chandra-Sekhar-Bala** [comment] 2022-06-22 20:49
Hey @yash10019coder , I'd like to start with this one  🦾

**Comment by yash10019coder** [comment] 2022-06-23 03:41
Assigned @Chandra-Sekhar-Bala thanks

**Comment by Chandra-Sekhar-Bala** [comment] 2022-06-23 18:39
I think the issue is solved, what should I do now ?

**Comment by yash10019coder** [comment] 2022-06-23 18:42
@Chandra-Sekhar-Bala you can now make a pull request by following this [guide](https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR).

**Comment by BenHenning** [comment] 2022-06-30 18:59
Sorry, this is actually being worked on by @Ryggs. I forgot to assign it before.

**Comment by pratyaksh1610** [comment] 2022-07-02 18:31
I would like to work on this issue. @BenHenning

**Comment by pratyaksh1610** [comment] 2022-07-06 05:37
I am unable to find good first issue that i can resolve. Can u help me out @BenHenning

**Comment by Ryggs** [comment] 2022-07-06 10:34
This issue is being worked on @pratyaksh1610

**Comment by BenHenning** [comment] 2022-07-07 04:31
Hi @pratyaksh1610. You can find available starter issues [here](https://github.com/oppia/oppia-android/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee). That being said, it looks like this is your first time contributing to the codebase, You should head over to the [onboarding instructions on the wiki](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#onboarding-instructions) so that you can get started with the steps to be onboarded. Part of that process includes finding a viable starter issue.

**Comment by pratyaksh1610** [comment] 2022-07-07 06:21
Thanks for the reference @BenHenning. Successfully submitted CLA from and Oppia contributor survey form and read all docs.
Think I'm ready to get started with open source.

**Closed as completed** 2022-08-13 21:57 UTC
Labels: good first issue, Impact: Low, Z-ibt
