### ISSUE TITLE
Incomplete sentence is displayed in response for one of the questions in an exploration

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4351] opened 2022-05-09 10:25 UTC
**Describe the bug**
Incomplete sentence is displayed in response for one of the questions in an exploration

**To Reproduce**
1. Go to 'Fractions'
2. Click on 'Subtracting Fractions'
3. Click on Continue
4. In the first question page enter 2 wrong answers
5. For the 2nd wrong attempt verify the response displayed

**Expected behavior**
'No, that's not right. You may want to review the topic' must be displayed

Actual Result:
'No, that's not right. You may want to review the .' is displayed

![Screenshot_2022-04-29-15-48-27-13_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/167391760-df99aede-0bad-44e9-b172-57acb0da7eab.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment] 2022-06-10 17:18
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by oyeraghib** [comment] 2022-06-22 13:07
Hey can I work on this issue ?

**Comment by BenHenning** [comment] 2022-06-22 20:42
Hi @oyeraghib. This issue might be a bit harder than other starter issues. You're welcome to work on it if you're interested, but I suggest looking for other issues marked as good starter issues as they may be a simpler introduction to the codebase.

**Comment by oyeraghib** [comment] 2022-06-24 07:41
Okay, thanks I will look into the good first issues first.

**Comment by pratyaksh1610** [comment] 2022-08-21 04:46
@KolliAnitha I am unable to reproduce the issue , and I have checked the assets in `domain`, string is not present as a response.

**Comment by KolliAnitha** [comment] 2022-08-21 05:06
@pratyaksh1610 Please follow the repro steps to check this issue. I am still able to repro the issue in 0.8-alpha-091b45a188. Attaching video for same.
https://user-images.githubusercontent.com/101634267/185776395-edf1efd9-a08e-425e-a108-1946aeac8f5c.mp4

**Comment by pratyaksh1610** [comment] 2022-08-21 05:10
@KolliAnitha In mine, I can only see 2 chapters in Fractions and chapter-2 is locked as of now.

**Comment by pratyaksh1610** [comment] 2022-08-21 05:27
@KolliAnitha Is it like we need to first open all chapters by submitting.

**Comment by seanlip** [comment] 2022-08-21 05:27
Hi, this is a content issue; I am not sure why this was characterized as a coding one. The data in the Android app repo is different from the data on the Android app for release testing since the latter uses the data from the Oppia website.

I have now fixed the content issue, so this just needs a re-pull of the content. The issue here was that the feedback was using an external link component as opposed to a concept card, and the former is not available in the Android app.

**Comment by seanlip** [comment] 2022-08-21 05:27
Assigning @BenHenning for doing the content pull and moving this to the Beta MR1 milestone.

**Comment by BenHenning** [comment] 2022-09-09 09:47
Confirming this has been fixed in the latest pull of content:

https://user-images.githubusercontent.com/12983742/189322540-26a2c832-651e-4600-bae4-46d78e08226e.mp4

**Closed as completed by BenHenning** 2022-09-09 09:47 UTC
Labels: Impact: Low, Z-ibt

**Comment by KolliAnitha** [comment] 2022-09-13 04:21
Working fine in beta version.
![Screenshot_2022-09-13-09-49-31-61_943a62cb4c6fb83e010e1c2e82766a17](https://user-images.githubusercontent.com/101634267/189807997-992c3735-a1a9-4dc3-9e82-5239122fdd3a.jpg)
