### ISSUE TITLE
Issue in Domain on-boarding flow

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [oppia/oppia-android#599] opened 2020-01-09 09:20 UTC
Fix #565: Domain on-boarding flag #574
<img width="1628" alt="small" src="https://user-images.githubusercontent.com/54615666/72054448-02934580-32ef-11ea-9201-56d28622a978.png">

**Comment by rt4914** [comment] 2020-01-10 05:57
@nikitamarysolomanpvt please write steps to reproduce this issue.

**Comment by nikitamarysolomanpvt** [comment] 2020-01-16 16:35
@rt4914 Just need to run test-cases.

**Comment by anandwana001** [comment] 2020-11-17 08:07
@rt4914 Looks like `OnBoardingFlowControllerTest` file doesn't exist anymore.

**Comment by rt4914** [comment] 2020-11-17 08:18
This file was renamed in https://github.com/oppia/oppia-android/pull/1397/files .
Also, this is no more an issue the last reference that we have for this is #1397 which must have fixed this automatically. Therefore closing this issue.

**Closed as completed by rt4914** 2020-11-17 08:18 UTC
Labels: Z-ibt
