### ISSUE TITLE
Test failure in TopicPracticeFragmentTest

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3366] opened 2021-06-23 13:04 UTC
<img width="1542" alt="Screenshot 2021-06-23 at 6 33 21 PM" src="https://user-images.githubusercontent.com/9396084/123101322-8e505180-d451-11eb-8f2b-d5513968cd5c.png">

**Comment by TheSwarnim** [comment] 2021-06-24 05:26
Hello @rt4914, Sir, I want to work on this issue but I'm not able to understand what I've to change/edit...

**Comment by rt4914** [comment] 2021-06-26 21:29
@TheSwarnim basically the test is failing because the item which is clickable is small so you need to update the test case so that it works, example scrolling to show the view/item fully.

**Comment by TheSwarnim** [comment] 2021-06-27 05:49
Ok, sir, I'll see it

**Comment by anandwana001** [comment] 2021-06-30 06:45
@TheSwarnim Let me know if you need any help in testing.

**Comment by TheSwarnim** [comment] 2021-06-30 09:13
> @TheSwarnim Let me know if you need any help in testing.

@anandwana001 thank you sir for the help, the main that I'm facing that I'm not able to launch the test even after removing @DisableAccessibilityChecks line from the function, here is the screenshot:
![test](https://user-images.githubusercontent.com/54211377/123934811-467d7d00-d9b1-11eb-8888-496d9cb104c6.PNG)
even it is not showing what the @rt4914 sir have shared the ss and no test is run as you can in ss

**Comment by anandwana001** [comment] 2021-06-30 09:15
@TheSwarnim 

Could you try running this espresso test in a fresh emulator?

**Comment by TheSwarnim** [comment] 2021-06-30 09:18
> @TheSwarnim
> 
> Could you try running this espresso test in a fresh emulator?

Ok sir, let me try it out...

**Comment by anandwana001** [comment] 2021-06-30 09:26
Also, if further assistance required, then we can move this conversation to the Gitter channel.

**Comment by TheSwarnim** [comment] 2021-06-30 09:59
> Also, if further assistance is required, then we can move this conversation to the Gitter channel.

Thank you, sir, thankfully it works on a physical device but not in the emulator (even new). I wanted to know what we were wanted to achieve in this test as it gets stuck in the practice mode

**Comment by TheSwarnim** [comment] 2021-07-03 04:54
Hello @rt4914, Sir, I'm not understanding what is the aim of this test case. Can you please explain in brief

**Comment by rt4914** [comment] 2021-07-05 18:41
@TheSwarnim This error normally occurs when the item which we are trying to access in test case is not visible on screen. To solve this you will need to scroll to that view and then continue with the test case.

**Comment by anandwana001** [comment] 2021-07-15 02:48
@TheSwarnim any update on this?

**Comment by yash10019coder** [comment] 2021-08-04 06:48
@prayutsu please assing me this issue

**Comment by prayutsu** [comment] 2021-08-04 06:51
@TheSwarnim Are you working on this?

**Comment by TheSwarnim** [comment] 2021-08-17 10:22
@prayutsu, yes I'm working on this.

**Comment by anandwana001** [comment] 2021-08-17 15:31
Hi @TheSwarnim Let me know if you need any help in creating a PR for this issue. Also, you can share where are you stuck on.

**Comment by rt4914** [comment] 2021-11-18 16:45
@TheSwarnim Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by shankarpriyank** [comment] 2022-01-22 06:56
Hi @bkaur-bkj could I would like to work on this could you please assign this to me

**Comment by shankarpriyank** [comment] 2022-01-22 07:37
Also I am also encountering the same error as @TheSwarnin , and I am getting the same message even with a physical device , an help would really be appreciated @anandwana001

**Comment by anandwana001** [comment] 2022-01-22 16:14
@shankarpriyank Could you please post the update error log you are getting?

**Comment by shankarpriyank** [comment] 2022-01-22 16:33
![image](https://user-images.githubusercontent.com/75121767/150647259-2e87750f-cdce-45ac-9f0c-e47a64c00d92.png)
@anandwana001

**Comment by yashbansal130** [comment] 2022-01-28 05:55
@shankarpriyank
i found this article related to that {adb shell} command, see if you can find anything useful
 https://developer.android.com/training/testing/instrumented-tests/androidx-test-libraries/runner

**Comment by TheSwarnim** [comment] 2022-01-28 08:56
Hi @shankarpriyank , I think I can help you with this. Just go to the developer options in your phone/emulator and disable all animations and then launch the test again.
Let me know if it doesn't work still now.

**Comment by Akshatkamboj14** [comment] 2022-01-31 21:55
Hey i want to work on this..can u please assign me?

**Comment by rt4914** [comment] 2022-02-10 06:55
Un-assigned because of inactivity.

**Comment by addy-zero** [comment] 2022-02-26 10:56
@rt4914 This seems like a good issue for me. Can you give me some pointers to get started?

**Comment by rt4914** [comment] 2022-03-01 13:12
@adizcode I don't have more information apart from this failure. Can you investigate the reasons of failure and create PR based on that and if thats not possible can you discuss this with your mentor? Thanks.

**Comment by addy-zero** [comment] 2022-03-01 13:46
@rt4914 Actually I've just been assigned to a couple other issues, so I prefer picking this up at a later date.

**Comment by antonmagnus** [comment] 2022-11-09 08:17
Can I be assigned this issue?

**Comment by dmdbilal** [comment] 2022-11-16 13:42
Can i work on this issue ?

**Comment by BenHenning** [comment] 2022-11-17 01:34
@dmdbilal I think you’re assigned another issue. I suggest focusing on that one, first, then you can take another issue to work on.

**Comment by masclot** [comment] 2023-01-13 12:01
I just run this test in AndroidStudio Bumblebee, using Pixel 3a emulator and Api 28. 10 out of 10 tests passed, including testTopicPracticeFragment_loadFragment_selectSubtopics_clickStartButton_skillListTransferSuccessfully
Should this issue be closed? or should I use a different device for the test?

**Comment by yash10019coder** [comment] 2023-01-13 12:10
maybe try running this test more times to check whether it's flaky or not

**Comment by masclot** [comment] 2023-01-13 12:43
Done. I think this issue is a duplicate of https://github.com/oppia/oppia-android/issues/3413 which was fixed already.

**Comment by BenHenning** [comment] 2023-01-13 19:39
I think you're correct @masclot and I appreciate you taking the time to verify that the issue hasn't recurred. :) Closing this since it seems to be a duplicate of #3413.

**Closed as not planned by BenHenning** 2023-01-13 19:39 UTC
Labels: Priority: Essential, good first issue, Impact: Low, Z-ibt
