### ISSUE TITLE
Variable name is displayed instead of actual incorrect answer

### ISSUE THREAD

**Issue by Sparsh1212** [oppia/oppia-android#2860] opened 2021-03-08 18:04 UTC
**Describe the bug**
When an incorrect answer is given, the output displays `{{answer}}` instead of the actual incorrect input provided.

**To Reproduce**
1. Go to 'First Test Topic'
2. Select the 'Second Story' lesson.
3. Give the 'Third Exploration' test.
4. Give any random input (say 'abcde') as the answer to the 'In fact, the word Oppia means ...' question.
5. You will observe that `{{answer}}` is displayed in place of your provided input in the output message.

**Expected behavior**
It should display the actual incorrect input provided in the output message inplace of `{{answer}}`

**Screenshots**
<img height="600" src="https://user-images.githubusercontent.com/55937724/110360987-6cc78780-8065-11eb-9f9c-3dbf45a024d2.png" width="350" />

**Device**
Realme 6

**Comment by Sparsh1212** [comment] 2021-03-08 18:10
@rt4914 Can you please confirm if this is a valid issue and not a duplicate of any other previous issue.

**Comment by rt4914** [comment] 2021-03-09 22:18
@Sparsh1212 Thanks for filing this. I am able to reproduce it but its `Third Exploration` not `Second Exploration`. Please update the description.

**Comment by Sparsh1212** [comment] 2021-03-10 05:32
> @Sparsh1212 Thanks for filing this. I am able to reproduce it but its `Third Exploration` not `Second Exploration`. Please update the description.

Yeah, sorry it is `Third Exploration`. 
I have edited the description now.

**Comment by rt4914** [comment] 2021-03-10 07:50
@Sparsh1212 Thanks a lot.

**Comment by nlok5923** [comment] 2021-03-10 17:31
@rt4914 please can you assign this issue to me.

**Comment by ArpitShukIa** [comment] 2021-03-11 07:40
Hi,
I am also trying to solve this issue. 
While trying to find the root cause of this issue, I found the json `test_exp_id_3.json` corresponding to `Third Exploration`.

![Screenshot](https://user-images.githubusercontent.com/51705072/110752031-b208d680-826a-11eb-8567-3d1a54753f87.png)


The `param_changes` JSONArray  in the `default_outcome` JSONObject is empty.
Can you please verify if this is the issue OR is the array supposed to be empty?

**Comment by BenHenning** [comment] 2021-04-11 20:13
This is actually a known issue that we probably won't fix. Oppia web supports parameters which allow explorations to dynamically tweak values across states, and display them. We actually don't plan to ever support this in Oppia Android since we've discovered that parameters are difficult to maintain, and don't add much value to the learning experience.

Thanks for filing this--it gave me reason to file #3081 detailing the eventual plan for assets. This issue will be resolved as part of that broader effort, so closing this in favor of that one.

**Closed as completed by BenHenning** 2021-04-11 20:13 UTC
Labels: Z-ibt
