### ISSUE TITLE
Splash Screen Stretched

### ISSUE THREAD

**Issue by anshbajpai** [oppia/oppia-android#2652] opened 2021-02-07 14:29 UTC
**Describe the bug**
 Splash screen is displayed when a user opens the app, on small screen devices the splash screen is working as expected, but on large screen devices, the splash screen is getting stretched and doesn't work as expected.

**To Reproduce**
1. Go to the Oppia app
2. Click on the icon
3. If your device screen is more than 6 inch
4. See  splash screen getting stretched

**Expected behavior**
 The splash screen should be displayed in the same aspect ratio as needed.

**Screenshots**

[Note: Also reported in #3193 -- see additional videos in that issue.]

Expected Behaviour
<img width="275" alt="Expected Behaviour" src="https://user-images.githubusercontent.com/65030524/107149237-7fbf3d00-697d-11eb-9f3c-2360380fb545.png">
Actual Behaviour
![SplashScreen](https://user-images.githubusercontent.com/65030524/107149266-ada48180-697d-11eb-9808-196e01635fc4.jpeg)

**Device**
- OnePlus 7 Pro
- Android 10.0

The logo should be fixed as per device width:
- Mobile ([Portrait](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/ddc5589e-10d1-48e4-b551-5487801233e1), [Landscape](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/375d3300-f70d-44ed-a48a-269a58ecc854))
- Tablet ([Portrait](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/d39fdc8a-2bee-4867-a1a6-ce4280671c2b), [Landscape](https://xd.adobe.com/view/dfe8ccd4-39eb-414d-a0b2-b5674357f966-8abb/screen/d69bb715-1aea-4815-8401-6e7fde167ed4))

**Comment by anshbajpai** [comment] 2021-02-07 14:30
Hi , i want to work on this issue

**Comment by chrk2205** [comment] 2021-02-07 19:21
@anshbajpai 
did you signed the CLA??
https://github.com/oppia/oppia-android/wiki

**Comment by anshbajpai** [comment] 2021-02-08 04:07
Yeah, I have signed the CLA now.

**Comment by anandwana001** [comment] 2021-02-08 04:15
@anshbajpai Suggesting to fill the Contributor survey as well to get an onboarding mentor assigned to get started with the contribution. 
https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by anshbajpai** [comment] 2021-02-08 05:09
@anandwana001 I have completed the survey now

**Comment by anandwana001** [comment] 2021-03-03 04:31
@anshbajpai any update on this?

**Comment by anandwana001** [comment] 2021-03-03 04:33
unassigning as no further update.

**Comment by ArpitShukIa** [comment] 2021-03-12 05:49
I would like to work on this. Assign to me plz.

**Comment by shankarpriyank** [comment] 2022-01-10 08:02
I would love to work on this can you please assign this issue to me?

**Comment by vivaansahai** [comment] 2022-12-26 20:52
Hi, I would like to work on this issue. Please assign me.

**Comment by adhiamboperes** [comment] 2022-12-28 20:41
> Hi, I would like to work on this issue. Please assign me.

Hi @vivaansahai, I have assigned this issue to you.

**Comment by YesShubham01** [comment] 2023-01-03 07:39
Can anyone describe me ... where can i find code for this splash screen?

**Comment by adhiamboperes** [comment] 2023-01-03 19:06
> Can anyone describe me ... where can i find code for this splash screen?

Hey @YesShubham01, are you attempting to work on this issue? It is currently assigned to @vivaansahai. You can look for a different issue to work on.

**Comment by vivaansahai** [comment] 2023-01-03 19:11
@YesShubham01 you can get yourself assigned on this issue.

**Comment by masclot** [comment] 2023-01-13 16:23
I looked into this. I could reproduce the issue on a Pixel 4XL emulator running Api 28, but not with Api 33.
It seems there are two splash screens: splash_activity.xml and splash_page.xml.

splash_page.xml is a vector drawable and installed as a window background of SplashActivity.kt
IMO it always stretches, but the stretch is only obvious in screens with 'non-standard' aspect ratios.
It is the classic way of building splash screens. It does not show in Api 33.

splash_activity.xml is a View and does not stretch. It shows on top of/ instead of  splash_page.xml once the activity View is created. This View does not stretch. AFAICT its purpose is just to show a label with the flavor of the apk.

Since splash_page stretches and splash_activity does not, depending on screen aspect ratio, one can see the transition from one to the other as the Oppia text moves/resizes. This can be very fast in the emulators I tried.

Unfortunately I don't know how to prevent stretching using a vector drawable in a background. Using a bitmap would fix it I think, but we would need a bitmap for every resolution and splash_activity.xml would need to be changed as well.

However, instead of that I would suggest moving to android's splash screen Api: https://developer.android.com/develop/ui/views/launch/splash-screen
and find another way of showing the apk flavor.

**Comment by BenHenning** [comment] 2023-01-13 20:08
I think you've fully identified the set of issues @masclot. I also couldn't think of a way to do this that didn't involve using bitmaps which is why earlier approaches ended up not working (see https://github.com/oppia/oppia-android/pull/2894#issuecomment-806331393). My current assumption is that we'll need to use bitmap drawables, but I wanted to do this via a build-time generation of the images from the vector drawable to avoid needing to add a bunch of binary files to the main repository (the different build flavors could easily be added to this approach, too, by having separate vector drawables to reference).

I wasn't aware of the splash screen API--that's a really nice idea. While it does exist in compat form (https://developer.android.com/reference/kotlin/androidx/core/splashscreen/SplashScreen) it doesn't have backward compatibility for the animations, which is unfortunate. I think what we could do is:
- Migrate to the AndroidX compat splash screen
- Add new vector drawables for each type of splash screen (based on build flavor)
- Add animated versions of those drawables
- Set up the new splash screen with both drawables (where the animated ones are locked to API 31+)
- Remove the old splash assets & logic

This will presumably require some work from our design team, but it's probably the most future-proof approach and will still let us have a nice looking splash without any jumping or, hopefully, distortion.

**Comment by supreme96** [comment] 2023-01-18 18:54
@BenHenning Can we make smaller sub tasks for the above described approach? I think I can take ownership of one of them as a starter issue?

**Comment by BenHenning** [comment] 2023-02-07 03:52
> @BenHenning Can we make smaller sub tasks for the above described approach? I think I can take ownership of one of them as a starter issue?

@supreme96 I think that's a nice suggestion.  I think the MVP for this, however, would be everything except the animated drawable (since migrating the splash screen is more or less an "all or nothing" exercise).

**Comment by adityabarodiya** [comment] 2023-02-10 15:04
I might be able to fix this issue. It could be my first contribution, please assign this issue to me.

**Comment by adityabarodiya** [comment] 2023-02-11 14:31
I want to work on this issue, please assign this issue to me.

**Comment by adityabarodiya** [comment] 2023-02-12 10:07
Sorry, I couldn't figure out why is this issue happening. Unassign this issue to me. I'll look for another issue that I can fix.

**Comment by HarshJainofficial** [comment] 2023-02-13 05:14
Please assign this to me i definitely very curious to work on this project.

**Comment by SidharthMudgil** [comment] 2023-02-16 09:20
@BenHenning Hi, I have found 1 fix for this, tell me will it be ok? if Yes, please assign me this

### Output
### K20

https://user-images.githubusercontent.com/68889544/219314965-8ee33191-ceee-4ed5-8359-72569bb5169d.mp4

### Realme 1

https://user-images.githubusercontent.com/68889544/219322176-c5608bd4-3567-4ab0-b192-65667ba9bbd1.mp4

**Comment by BenHenning** [comment] 2023-02-17 02:03
@SidharthMudgil the videos seem to have the same splash screen behavior as the current app (at least in terms of the jumping between the static & dynamic splash pages). Do you have a "before" video to show the stretched behavior without your fix?

**Comment by SidharthMudgil** [comment] 2023-02-17 08:22
@BenHenning 

https://user-images.githubusercontent.com/68889544/219591272-87d26055-d104-4d29-bcb9-7bdfec3eeff1.mp4

**Comment by BenHenning** [comment] 2023-02-23 03:34
@SidharthMudgil thanks! That does look like it's behaving correctly. I can't be certain that the solution is correct without looking at the code (since it depends on what it's doing), but I think you can go ahead and make a PR for this.

**Comment by SidharthMudgil** [comment] 2023-02-23 08:32
@BenHenning Sorry, I just checked my solution is similar to https://github.com/oppia/oppia-android/pull/2655 so I think it is not the correct solution.

**Comment by manan1979** [comment] 2023-03-06 13:50
can i work on this issue?

**Comment by seanlip** [comment] 2023-03-06 14:14
@manan1979 Please provide an explanation of what your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue. Thanks!

**Comment by adhiamboperes** [comment] 2023-10-04 18:17
It doesn't seem like @backpackerdeveloper is still working on this issue. Note to other devs: We agreed that the approach taken in https://github.com/oppia/oppia-android/pull/5147 is fine, and there are comments on the PR that need to be addressed for the solution to be complete.

Note: You need to have Bazel set up and running in order to resolve this.

**Comment by Cyclotron17** [comment] 2023-12-07 17:35
Hi Team,

I hope you're doing well. I've encountered an issue related to converting dp to sdp in our Android project. After some research, I found a solution that involves using the "sdp" library to make our layout dimensions more adaptable across different screen sizes and resolutions.

To implement this solution, I propose the following changes:

Added "sdp" Library:
In the app-level build.gradle file, add the "sdp" library dependency:

in app-level build.gradle add the following dependency 
implementation 'com.intuit.sdp:sdp-android:1.0.6'

Updated the  Layout XML:
Modify the layout_width and layout_height attributes in the layout XML file to use sdp:

in the splash_activity.xml file change the width and height as following
<ImageView
    android:id="@+id/splash_oppia_logo"
    android:layout_width="@dimen/width_228sdp"
    android:layout_height="@dimen/height_88sdp"
    android:importantForAccessibility="no"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="@+id/logo_top_margin"
    app:srcCompat="@drawable/full_oppia_logo" />
Define sdp Dimensions:
 In the "dimens.xml" file in the "res/values" directory to include the sdp dimensions:


<resources>

    
    <dimen name="width_228sdp">228sdp</dimen>

    
    <dimen name="height_88sdp">88sdp</dimen>

</resources>
These changes should resolve the issue by making our layout dimensions scalable. Please review and let me know if you have any feedback or concerns.

Thanks,
Can you please assign me this issue?

**Comment by adhiamboperes** [comment] 2023-12-08 06:30
> Hi Team,
> 
> I hope you're doing well. I've encountered an issue related to converting dp to sdp in our Android project. After some research, I found a solution that involves using the "sdp" library to make our layout dimensions more adaptable across different screen sizes and resolutions.
> 
> To implement this solution, I propose the following changes:
> 
> Added "sdp" Library: In the app-level build.gradle file, add the "sdp" library dependency:
> 
> in app-level build.gradle add the following dependency implementation 'com.intuit.sdp:sdp-android:1.0.6'
> 
> Updated the Layout XML: Modify the layout_width and layout_height attributes in the layout XML file to use sdp:
> 
> in the splash_activity.xml file change the width and height as following Define sdp Dimensions: In the "dimens.xml" file in the "res/values" directory to include the sdp dimensions:
> 
> ```
> 
> <dimen name="width_228sdp">228sdp</dimen>
> 
> 
> <dimen name="height_88sdp">88sdp</dimen>
> ```
> 
> These changes should resolve the issue by making our layout dimensions scalable. Please review and let me know if you have any feedback or concerns.
> Thanks, Can you please assign me this issue?

@Cyclotron17, the approach is sound. But as per my previous comment, you also need to add the dependency to bazel, and I have linked a way to do it.

**Comment by Cyclotron17** [comment] 2023-12-08 17:41
> > Hi Team,
> > I hope you're doing well. I've encountered an issue related to converting dp to sdp in our Android project. After some research, I found a solution that involves using the "sdp" library to make our layout dimensions more adaptable across different screen sizes and resolutions.
> > To implement this solution, I propose the following changes:
> > Added "sdp" Library: In the app-level build.gradle file, add the "sdp" library dependency:
> > in app-level build.gradle add the following dependency implementation 'com.intuit.sdp:sdp-android:1.0.6'
> > Updated the Layout XML: Modify the layout_width and layout_height attributes in the layout XML file to use sdp:
> > in the splash_activity.xml file change the width and height as following Define sdp Dimensions: In the "dimens.xml" file in the "res/values" directory to include the sdp dimensions:
> > ```
> > 
> > <dimen name="width_228sdp">228sdp</dimen>
> > 
> > 
> > <dimen name="height_88sdp">88sdp</dimen>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These changes should resolve the issue by making our layout dimensions scalable. Please review and let me know if you have any feedback or concerns.
> > Thanks, Can you please assign me this issue?
> 
> @Cyclotron17, the approach is sound. But as per my previous comment, you also need to add the dependency to bazel, and I have linked a way to do it.

Sure thing, will be adding that as well

**Comment by TanishMoral11** [comment] 2024-10-08 15:23
Hey @anandwana001, Can You Please Assign This Issue To Me.

**Comment by adhiamboperes** [comment] 2024-10-09 09:05
@TanishMoral11, assigned.

**Comment by TanishMoral11** [comment] 2024-10-10 17:33
Hey @adhiamboperes ,

I want to share the approach I'm planning to take for this issue, and I would appreciate your feedback on whether it is correct:

splash_image.xml:
I will create a new layer-list drawable, which includes:

A background color (@color/oppiaPrimaryLight)
The splash image (@drawable/splash_page) centered.

splash_page.xml:
I plan to modify the path data for the splash image, and I will remove the old clip-path.

styles.xml:
I will update the SplashScreenTheme to reference the new splash_image drawable, and set adjustViewBounds to true to handle different screen sizes.

Can you please confirm if this approach is correct, or suggest any changes I should make?

Thank you!

**Comment by adhiamboperes** [comment] 2024-10-15 11:32
@TanishMoral11, I think splash_page is a vector that is generated a green bg + @drawable/full_oppia_logo. It maybe thage you need to completely replace the splash_page with the new drawable you describe. Could you please try it out and let us know.

**Comment by TanishMoral11** [comment] 2024-10-16 17:25
@adhiamboperes PTAL https://github.com/oppia/oppia-android/pull/5555

**Closed as completed** 2024-10-30 13:36 UTC
Labels: good first issue, Impact: Low, Z-ibt, bug
