### ISSUE TITLE
Fix UI for profile chooser screen in add-view

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2116] opened 2020-11-16 06:47 UTC
`profile_chooser_add_view.xml` needs to be updated so that the UI looks similar to mocks.

## Mocks
https://xd.adobe.com/view/ee9e607b-dbd6-4372-48dc-b687d32af3da-98af/grid/
https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/grid
https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/33741ea7-89da-4e5d-b2a4-9872f6db48b4/
https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/6fb19f15-699a-40aa-8392-cdfc6d7bf8c5/

https://github.com/oppia/oppia-android/wiki/Working-on-UI

## Current Screenshot
![Screenshot_1605508088](https://user-images.githubusercontent.com/9396084/99220465-c11fd080-2804-11eb-9e85-68d91ae34d4b.png)
![Screenshot_1605508113](https://user-images.githubusercontent.com/9396084/99220469-c41ac100-2804-11eb-815b-7e57f95d45ef.png)
![Screenshot_1605508138](https://user-images.githubusercontent.com/9396084/99220472-c54bee00-2804-11eb-871d-d05dd5e3f71d.png)
![Screenshot_1605508141](https://user-images.githubusercontent.com/9396084/99220474-c5e48480-2804-11eb-8cf6-37ae0e93655a.png)

## Device:
Nexus-9 Emulator
API 29

**Comment by ShridharGoel** [comment] 2020-11-17 08:41
I would like to work on this.

**Comment by ShridharGoel** [comment] 2020-11-22 17:23
Hi, this is how the screen looks currently:

<img width="767" alt="Select Profile 1" src="https://user-images.githubusercontent.com/35566748/99910680-5c3d0c80-2d15-11eb-8723-7a2a4cece385.png">

<img width="764" alt="Select Profile 2" src="https://user-images.githubusercontent.com/35566748/99910692-6bbc5580-2d15-11eb-9843-4fc58ab5856f.png">


May I know what needs to be changed, since it seems to be in accordance with the designs?

**Comment by ShridharGoel** [comment] 2020-11-22 17:25
This is how the screens look currently:

<img width="767" alt="Select Profile 1" src="https://user-images.githubusercontent.com/35566748/99910725-a2926b80-2d15-11eb-9f8b-3fa0412b7c32.png">

<img width="764" alt="Select Profile 2" src="https://user-images.githubusercontent.com/35566748/99910727-a6be8900-2d15-11eb-8981-f4359289380e.png">


Since it looks in accordance with the designs, may I know what needs to be changed?

**Comment by rt4914** [comment] 2020-11-23 13:11
> This is how the screens look currently:
> 
> <img alt="Select Profile 1" width="767" src="https://user-images.githubusercontent.com/35566748/99910725-a2926b80-2d15-11eb-9f8b-3fa0412b7c32.png">
> 
> <img alt="Select Profile 2" width="764" src="https://user-images.githubusercontent.com/35566748/99910727-a6be8900-2d15-11eb-8981-f4359289380e.png">
> 
> Since it looks in accordance with the designs, may I know what needs to be changed?

@ShridharGoel If you run it on latest develop and Nexus & tablet. You will see following UI. Where the `Add Profile` is not aligned.
![Screenshot_1606137020](https://user-images.githubusercontent.com/9396084/99965819-6b769580-2dbb-11eb-882d-0d55a1af9c3e.png)

**Comment by ShridharGoel** [comment] 2020-11-23 17:38
@rt4914 Yes, the issue is reproducible on the latest commits. Thanks.

**Comment by ShridharGoel** [comment] 2020-11-23 17:42
@rt4914 Yes, the issue is replicable on the latest commits. Thanks.

**Comment by sorinmircea** [comment] 2022-11-18 09:31
Can I take this issue ?

**Comment by BenHenning** [comment] 2022-11-18 09:44
Feel free to @msorins. Assigning you.

**Comment by ArchitJain1201** [comment] 2022-12-09 14:48
@BenHenning Can I work on this issue ?

**Comment by BenHenning** [comment] 2022-12-17 05:50
It doesn't seem like @msorins is still working on this (or at least right now), so feel free @ArchitJain1201. Apologies for the delay in responding!

**Comment by ArchitJain1201** [comment] 2023-01-14 18:09
I want to confirm. since this issue has been moved to [Team], can I still work on it or not?

**Comment by r1shhh1** [comment] 2023-01-23 15:58
Can i work on this issue

**Comment by adhiamboperes** [comment] 2023-03-13 18:57
Unassigning @ArchitJain1201 due to inactivity

**Comment by aayushimathur6** [comment] 2023-04-15 09:53
@adhiamboperes as per the expected issue, when I m reproducing it mine is coming a bit aligned. PTAL 
![tablet](https://user-images.githubusercontent.com/92685651/232206757-d787c071-e522-43cb-8665-85f8dd865194.png)

**Comment by adhiamboperes** [comment] 2023-04-17 17:10
> @adhiamboperes as per the expected issue, when I m reproducing it mine is coming a bit aligned. PTAL !

Hi @aayushimathur6, can you share the specifications of the device you used to repro? One tip is to use an emulator with the same specifications as the device on which the issue was reported.

**Comment by adhiamboperes** [comment] 2023-04-18 07:52
> > @adhiamboperes as per the expected issue, when I m reproducing it mine is coming a bit aligned. PTAL !
> 
> Hi @aayushimathur6, can you share the specifications of the device you used to repro? One tip is to use an emulator with the same specifications as the device on which the issue was reported.

I attempted to repro the issue myself on the Nexus 9 API 29 and I can confirm that it is no longer reproducing, additionally, the recent work done in #4849  and #4844  contain screenshots that confirm this.

**Tablet Landscape**
<img width="884" alt="Screenshot 2023-04-18 at 10 08 58" src="https://user-images.githubusercontent.com/59600948/232705470-8d8b1534-3f30-408f-adbb-3d2836b3b8b3.png">

**Tablet Portrait**
<img width="667" alt="Screenshot 2023-04-18 at 10 10 04" src="https://user-images.githubusercontent.com/59600948/232705510-08eb0cdd-befd-436c-a7f4-80fcd1d22f15.png">

**Comment by adhiamboperes** [comment] 2023-04-18 07:55
However, subsequent work in #4874  breaks the default profile chooser view.

![Screenshot_1681801427](https://user-images.githubusercontent.com/59600948/232710039-d97434e7-80cc-49c0-88c7-1c5d944c13fe.png)

@seanlip, what's the appropriate action in this case between creating a new issue for this and reverting #4874?

**Comment by seanlip** [comment] 2023-04-18 08:01
If the issue was caused by #4874 (i.e. it worked fine before that PR and didn't after that PR) then please revert that PR. That's better than trying to fix-forward (unless the fix is obvious) because develop should always be clean and releasable.

Thanks for checking!

**Comment by adhiamboperes** [comment] 2023-04-18 09:03
> If the issue was caused by #4874 (i.e. it worked fine before that PR and didn't after that PR) then please revert that PR. That's better than trying to fix-forward (unless the fix is obvious) because develop should always be clean and releasable.
> 
> Thanks for checking!

I do not have the appropriate permissions to revert this so I will leave it for @BenHenning.

<img width="1427" alt="Screenshot 2023-04-18 at 12 03 08" src="https://user-images.githubusercontent.com/59600948/232728560-0f867267-8f29-44e0-b5c0-a2bdd408b08d.png">

**Comment by adhiamboperes** [comment] 2023-04-18 09:04
Otherwise we can close this issue as fixed. Thanks @aayushimathur6

**Comment by aayushimathur6** [comment] 2023-04-18 15:35
> Otherwise we can close this issue as fixed. Thanks @aayushimathur6

sure, Thanks @adhiamboperes I will find a new one to work on

**Comment by aayushimathur6** [comment] 2023-04-18 15:35
> > @adhiamboperes as per the expected issue, when I m reproducing it mine is coming a bit aligned. PTAL !
> 
> Hi @aayushimathur6, can you share the specifications of the device you used to repro? One tip is to use an emulator with the same specifications as the device on which the issue was reported.

Nexus 9 API 29

**Comment by masclot** [comment] 2023-04-28 13:21
I tried to reproduce this in Nexus 9 emulator, API 29, but couldn't. I tried with the old branch I still have with the original changes, and a new branch where I only apply the changes to MarginBindingAdapters. I could not reproduce the issue.
Screenshots:

|landscape | portrait|
|-|-|
|![profile_chooser_landscape](https://user-images.githubusercontent.com/103062089/235158153-504a2719-bcbb-4cc9-a4c8-1f686929df38.png)|![profile_chooser_portrait](https://user-images.githubusercontent.com/103062089/235158159-f5430257-a96c-4891-91aa-dddb57302ecf.png)|

Did you change any configuration?

**Comment by adhiamboperes** [comment] 2023-05-02 12:58
Hi @masclot, I have confirmed that I can repro this when I check out commit `7fd290d68f0440d926f2d443dbd7bfb28ab20547`, which is the one I reverted. I suspect that your view may be cached. Can your clear your cache and retry? 
I did not change any configs--this is a clean install of the app.

**Comment by masclot** [comment] 2023-05-05 09:04
Thanks @adhiamboperes  I could reproduce the issue by clearing the application data, which shows a somewhat different profile chooser on app start. Also, I could only reproduce in landscape mode.

**Closed as completed** 2023-06-24 06:34 UTC
Labels: Priority: Essential, good first issue, Impact: Low, Z-ibt, enhancement
