### ISSUE TITLE
Administrator controls toggle radio buttons by clicking on the complete item

### ISSUE THREAD

**Issue by FareesHussain** [oppia/oppia-android#3130] opened 2021-04-28 04:21 UTC
**Describe the bug**
Toggle Radio button by clicking on the `topic_update_on_wifi_constraint_layout` and `auto_update_topic_constraint_layout`

**To Reproduce**
1. Go to 'Administrator Controls'
2. Click on 'Download and update only on Wifi'
3. The radio button is not changed

**Expected behavior**
To be able to toggle the radio button by clicking anywhere on the view.

**Screenshots**
![image](https://user-images.githubusercontent.com/54740946/116240742-cbfe6a00-a781-11eb-8889-6c93f0ebd201.png)

**Comment by rt4914** [comment] 2021-05-06 13:25
@FareesHussain This is the desired behaviour. Its not a bug we should close this unless to have any compelling reason for this change.

**Comment by FareesHussain** [comment] 2021-05-06 13:34
This was found in while testing aplha MR2 and I had to use the bug tracker template as per the instructions. 
I will change the label now.

**Closed as completed** 2021-07-05 18:50 UTC
Labels: Z-ibt
