### ISSUE TITLE
Topic Progress Logic Update: getOngoingTopicList (TopicController)

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2630] opened 2021-02-05 12:03 UTC
<img src="https://user-images.githubusercontent.com/9396084/107030388-970ff600-67d6-11eb-8942-82586b69f6f5.png" width="200" />
<img src="https://user-images.githubusercontent.com/9396084/107030394-99725000-67d6-11eb-9c62-b623c3cbbacc.png" width="200" />

If learner finishes one story of a topic, then that topic should be considered as **Finished** but it is still considered as **In Progress** in current codebase.
The following cases should give following results for topic progress:
1. If no story is finished in a topic and and no story has not even started yet. -> **Not Started**
2. If no story is finished in a topic but the atleast one story has been started. -> **In Progress**
3. If atleast one story is finished and other stories have not been started yet. -> **Completed**
4. If atleast one story is finished and any other story has started. -> **In Progress**

**Comment by rt4914** [comment] 2021-02-05 12:05
@BenHenning @mschanteltc Does this issue + logic makes sense?
The main problem is even if learner finishes atleast one story in each topic, some topics are still considered as **In Progress** because in those topics their other stories are pending.

**Comment by mschanteltc** [comment] 2021-02-05 20:14
I agree with all the cases. Even though the fourth point (one story is finished and another story has started -> **In Progress**) might be confusing, labeling it as "In Progress" is a better indicator than "Completed" since there is unfinished material that the learner might want to pick back up on.

**Comment by Sparsh1212** [comment] 2021-02-23 11:38
I would love to work on this issue. Please assign it to me. Also, if possible guide me a bit on how to start working on this.

**Comment by Sparsh1212** [comment] 2021-02-25 15:03
@rt4914 I had a look at the `TopicController` file but I am unable to figure out where exactly the logic has to be updated so that it reflects in the entire codebase. Can you please give me an idea on how to start working on this?

**Comment by rt4914** [comment] 2021-03-01 15:15
@Sparsh1212 Any topic can have multiple stories. But if a learner finishes one story that means we can consider that topic as finished.
Try this out:
1. Install fresh copy.
2. Finish `First Story` in `First Test Topic`.
Now at this point as per our definition, because one story is finished we can consider that topic as finished. Therefore the navigation drawer should show `1 Story Completed | 0 Topic in Progress`.

**Comment by anandwana001** [comment] 2021-03-08 09:02
@Sparsh1212 Any update on this?

**Comment by Sparsh1212** [comment] 2021-03-08 09:19
> @Sparsh1212 Any update on this?

I was able to reproduce the issue. But I am facing trouble in getting started on this, I had a look at the `TopicController.kt` file but was unable to figure out, where exactly should I update the logic so that we get the desired output that we want. If you can guide me a bit on this, then that will be of much help to me.
 Thanks.

**Comment by anandwana001** [comment] 2021-03-08 09:23
Keeping @rt4914 in continue with the above discussion and for guidance too.

**Comment by rt4914** [comment] 2021-03-08 09:35
@Sparsh1212 You can start with `getOngoingTopicList` as this is the public function getting used in `app` module. If you traverse in this function you will end up at `checkIfTopicIsOngoing`. This function is responsible to given information whether a topic is ongoing or not. You will need to update the logic in this function.

**Closed as completed** 2021-03-21 01:01 UTC
Labels: Priority: Essential, Z-ibt
