### ISSUE TITLE
Text voiceovers in English for Portuguese language

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3821] opened 2021-09-20 23:02 UTC
**Describe the bug**
The text voiceovers appear in English even after changing the  device language to Portuguese. 

**To Reproduce**
1. Change the device language to Portuguese
2. Go to Oppia app 
3. Go to a lesson
4. Select and play voiceovers

**Expected behavior**
Portuguese voiceovers should appear if the device language is selected as Portuguese.

**Screenshots**
NA

**Device**
- Device/emulator being used - TBD
- SDK version - TBD

**Additional context**
NA

**Comment by anandwana001** [comment] 2022-02-11 05:42
@BenHenning Currently, there is no Portuguese language data in any JSON file. 
Example - `src/main/assets/umPkwp0L1M0-.json`

Could you please provide me with some Portuguese mp3 files?

**Comment by BenHenning** [comment] 2022-02-11 05:59
@anandwana001 can you try loading the alpha assets via the script in the assets repository? I think many of the production lessons do have Portuguese voiceovers.

**Comment by anandwana001** [comment] 2022-02-11 06:43
@BenHenning Looks like https://github.com/oppia/oppia-android-assets/pull/7 does not contain any Portuguese data.

**Comment by anandwana001** [comment] 2022-02-17 09:33
In corresponding to this issue, another issue we have is that if the device language is Portuguese then the language settings show English as the default language.

<img src="https://user-images.githubusercontent.com/25057618/154447085-e842014c-31c5-4e37-8102-7c3df001b694.png" width=230 height=450/>

Similar to https://github.com/oppia/oppia-android/issues/3828

**Comment by anandwana001** [comment] 2022-02-17 09:42
@BenHenning Just wanted to check if the issue - https://github.com/oppia/oppia-android/issues/3791
is affecting somehow this issue in terms of fixing it?

**Comment by BenHenning** [comment] 2022-02-18 05:53
It's relevant, but this bug probably won't be fixed by moving to the shared locale (since that would localize the names according to that language). I think the issue is that we're hardcoding the English names for the languages. We should be displaying the localized name of each language in that language, instead (which wouldn't change based on the user's locale, and I think will result in potentially being able to remove the locale dependency from that class altogether).

**Comment by anandwana001** [comment] 2022-02-28 10:45
@srushtirk For this specific release where we need the Portuguese language, will it be fine if we make our app default language to Portuguese in place of English? 
Doing this will make our app language and app's audio language to Portuguese as default. 

Implementing the part where the audio language gets updated as per the device language will need some time, so by the time this gets fixed, could we follow the above-mentioned approach?
Let me know your thoughts this.

**Comment by srushtirk** [comment] 2022-02-28 17:54
@anandwana001 This release will be focusing on users in Kenya who are not familiar with Portuguese. Changing the default app language to Portuguese would result into a bad user experience for our primary users for this release; and therefore this approach is not recommended. 

@isalooo FYI

**Comment by BenHenning** [comment] 2022-03-01 04:36
> @srushtirk For this specific release where we need the Portuguese language, will it be fine if we make our app default language to Portuguese in place of English? Doing this will make our app language and app's audio language to Portuguese as default.
> 
> Implementing the part where the audio language gets updated as per the device language will need some time, so by the time this gets fixed, could we follow the above-mentioned approach? Let me know your thoughts this.

I don't think this is what we discussed, actually @anandwana001. We always want the app default to be English. I think the consideration here is whether we should add Portuguese as an option in the language selection prompt, and if not tying together the written and audio languages is okay for now (since that's the thing that's difficult).

@srushtirk do you have thoughts on the above (that is, whether it's fine that there's an inconsistency between the selected written and audio languages)?

**Comment by srushtirk** [comment] 2022-03-02 03:52
@anandwana001 Can you share an approximate ETC for the complete resolution on this issue? 
@BenHenning If the full resolution can be incorporated by additional 2 weeks of extension for the code complete, then can we try to achieve that? If not, then let's move this issue to possibly an Alpha MR4.1 as discussed earlier today or Beta MR1 .

**Comment by anandwana001** [comment] 2022-03-03 09:55
I think this can be achievable within 2 weeks unless there is some requirement that comes under the domain/data module. I will inclined towards the @BenHenning thoughts on this.

**Comment by BenHenning** [comment] 2022-03-08 06:37
> @anandwana001 Can you share an approximate ETC for the complete resolution on this issue? @BenHenning If the full resolution can be incorporated by additional 2 weeks of extension for the code complete, then can we try to achieve that? If not, then let's move this issue to possibly an Alpha MR4.1 as discussed earlier today or Beta MR1 .

Is an extension still on the table? It was my understanding per the ETH folks that they'd prefer to get MR4 earlier.

**Closed as completed** 2022-09-09 13:30 UTC
Labels: Impact: Medium, Z-ibt
