### ISSUE TITLE
Place holder is not seen in a textbox after tapping outside the textbox in Fractions 

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4525] opened 2022-08-23 15:29 UTC
**Describe the bug**
Place holder is not seen in a textbox after tapping outside the textbox in Fractions 

**To Reproduce**
1. Go to 'Fractions' - Open What is a Fraction
2. Click on 'Continue' till you reach the page 'What fraction is shown by the shaded part of this drawing'
3. Tap on the textbox to enter, now tap outside the textbox or go back
4. Focus on the textbox is lost and see the place holder of the textbox

**Expected behavior**
'Enter a fraction in the form of x/y' should be seen

Note: It is working fine in Place Values topic

**Demonstration**
https://user-images.githubusercontent.com/101634267/186199428-2ffd7d5e-6593-40ba-b060-14198f1cb690.mp4

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by BenHenning** [comment] 2022-09-15 00:02
This is a duplicate of #4509, so it should be fixed now.

**Closed as not planned by BenHenning** 2022-09-15 00:02 UTC
Labels: Z-ibt
