### ISSUE TITLE
Chapter list doesn't stack up or hide after clicking the up arrow next to the topic in lessons tab

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#4075] opened 2021-12-30 18:51 UTC
**Describe the bug**
Stack up arrow next to the chapter list in the lessons tab does nothing.
Source: EdTech Hub Researchers

**To Reproduce**
1. Go to Oppia app
2. Go to a topic - lessons tab
3. Click the drop down (arrow) to see full list of chapters for that topic
4. Clicking on the up arrow to stack/hide the chapter list doesn't work/does nothing.

**Expected behavior**
The up arrow should stack and hide the chapter list, and turn into a drop down arrow.

**Demonstration**
![image](https://user-images.githubusercontent.com/27875087/147779973-bf6d8975-9b9f-4791-a314-2227a36e3192.png)

**Environment**
- Device/emulator being used: Samsung Galaxy 8 
- Android or SDK version (e.g. Android 5 or SDK 21): Android 9
- App version: 0.6-alpha-908d57b2b1

**Additional context**

**Comment by yashbansal130** [comment] 2022-02-02 05:19
@yash10019coder can i try this one?

**Comment by yash10019coder** [comment] 2022-02-02 19:19
ya sure

**Comment by yashbansal130** [comment] 2022-02-03 04:52
@yash10019coder it is working fine in my emulator both on Pixel 3 and Nexus 10 API 30

**Comment by yash10019coder** [comment] 2022-02-05 06:54
try to run it on Android 9

**Comment by yashbansal130** [comment] 2022-02-05 13:36
@yash10019coder working fine on Android 9 API 28

**Comment by yash10019coder** [comment] 2022-02-05 18:21
@srushtirk can you please confirm that the issue still exists?

**Comment by yash10019coder** [comment] 2022-02-05 18:32
@srushtirk I just tried it in my phone with the latest develop and it works.

https://user-images.githubusercontent.com/76404817/152654341-dd4e3892-0db8-4355-bc7a-913c3198a5c7.mp4

**Comment by srushtirk** [comment] 2022-02-08 05:05
Hi @yash10019coder thanks for checking, looks like the issue still exists on the specific device listed in the issue, but is working fine on other devices (I tested on Pixel 5, android 12).

**Comment by yashbansal130** [comment] 2022-02-08 18:32
@yash10019coder what should i do then?

**Comment by yash10019coder** [comment] 2022-02-10 05:49
you can try to run on all devices from android 6 or 7 to android 12 and can check whether they are working or not.

**Comment by yashbansal130** [comment] 2022-02-10 07:08
> you can try to run on all devices from android 6 or 7 to android 12 and can check whether they are working or not.


working fine on API 25 to 32

**Comment by yash10019coder** [comment] 2022-02-10 07:13
@yashbansal130 can you try to check this on Samsung Galaxy8 Andorid 9
you can download the hardware profile for the device

**Comment by yashbansal130** [comment] 2022-02-10 07:15
@yash10019coder how can i do that?

**Comment by yash10019coder** [comment] 2022-02-10 07:17
https://developer.samsung.com/galaxy-emulator-skin/guide.html

**Comment by yash10019coder** [comment] 2022-02-10 07:18
on creating the new emulator you can use new hardware profile and then import the profile you are going to download

**Comment by yashbansal130** [comment] 2022-02-10 07:31
@srushtirk samsung galaxy s8?

**Comment by yashbansal130** [comment] 2022-02-10 12:05
@yash10019coder 
![Screenshot from 2022-02-10 17-34-42](https://user-images.githubusercontent.com/66557534/153405424-6e697483-cd54-4069-857b-767cc82a42ef.png)
error while launching device

**Comment by yashbansal130** [comment] 2022-02-13 05:16
@yash10019coder any idea about it?

**Comment by yashbansal130** [comment] 2022-02-15 10:09
@srushtirk should we close this one?

**Comment by srushtirk** [comment] 2022-02-17 20:34
Hi @yashbansal130 has this issue been tested on Samsung Galaxy S8 and is working fine? I'm not able to understand clearly from the previous comments.

**Comment by yashbansal130** [comment] 2022-02-18 05:29
> Hi @yashbansal130 has this issue been tested on Samsung Galaxy S8 and is working fine? I'm not able to understand clearly from the previous comments.

I am having error launching samsung galaxy 8 since I had to download the skin for this one

**Comment by yashbansal130** [comment] 2022-02-21 12:20
@srushtirk please help me in this one

**Comment by BenHenning** [comment] 2022-02-23 03:48
@yashbansal130 what error are you encountering? We can't provide suggestions without better understanding what you've tried, and what issue you ran into trying that.

**Comment by yashbansal130** [comment] 2022-02-23 04:56
> @yashbansal130 what error are you encountering? We can't provide suggestions without better understanding what you've tried, and what issue you ran into trying that.

here is the screenshot of the error I am getting 


![Screenshot from 2022-02-23 10-25-29](https://user-images.githubusercontent.com/66557534/155263803-79afcad5-6581-49f1-8cce-8c470faed4c3.png)

**Comment by BenHenning** [comment] 2022-02-24 05:24
@yash10019coder have you done any searching on whether others have faced this same problem for Samsung emulators?

**Comment by BenHenning** [comment] 2022-02-24 05:24
@yashbansal130 have you done any searching on whether others have faced this same problem for Samsung emulators?

**Comment by yashbansal130** [comment] 2022-02-24 07:08
> @yashbansal130 have you done any searching on whether others have faced this same problem for Samsung emulators?

not everybody have a samsung emulator because the skin has to be downloaded separately and I tried for different API versions and @yash10019coder also tried for some versions. No I have not done any research on other users.

**Comment by srushtirk** [comment] 2022-02-24 22:34
FYI - I have requested the POC who reported it to share a video recording of this issue. It will likely be available by mid next week.

**Comment by BenHenning** [comment] 2022-02-25 06:42
Thanks @srushtirk and @yashbansal130. This might be a case where we need to first see the video to try and guess what's going on. We may be able to hack something in the app to force the same scenario to reproduce once we can see what it looks like, and that would allow for an investigation to begin.

**Comment by BenHenning** [comment] 2022-03-08 23:21
@srushtirk I recommend deprioritizing this issue until we have video demonstrating it since otherwise it's difficult to make progress on it since we can't easily reproduce it.

**Comment by srushtirk** [comment] 2022-03-08 23:56
Agreed, let's deprioritize this one. I also haven't received the video from the POC yet.

**Comment by BenHenning** [comment] 2022-06-10 01:29
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by KevinGitonga** [comment] 2022-09-30 09:16
@srushtirk @rt4914 @BenHenning not able to reproduce this on current develop branch as of now PTAL on attached video below.

https://user-images.githubusercontent.com/20886444/193236616-245c4bbb-cdc5-49c4-a9e7-37ddfa7e6022.mp4

**Comment by BenHenning** [comment] 2022-10-01 03:05
Thanks for checking @KevinGitonga. Given that the original issue no longer seems reproducible, closing this.

**Closed as not planned by BenHenning** 2022-10-01 03:05 UTC
Labels: Priority: Nice-to-have, Impact: Low, Z-ibt
