### ISSUE TITLE
[BUG]: Multiple choice options are not loaded for questions in all the lessons

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#5023] opened 2023-06-07 02:43 UTC
**Describe the bug**
Multiple choice options are not loaded for questions in all the lessons

**To Reproduce**
1. Go to 'Place Values' - What are Place Values
2. Click on 'Continue' to go to the next pages till you reach the question 'what place is the digit 2 in
3. Scroll down to see the options
4. See that the options do not load

**Expected behavior**
All the multiple choice options should load properly to move to the next pages

**Demonstration**
![Screenshot_20230607-074026](https://github.com/oppia/oppia-android/assets/101634267/4cc0f25e-c41b-4039-9a64-283249a22567)
![subject (2)](https://github.com/oppia/oppia-android/assets/101634267/b4bb44f9-e4ea-49a0-9d6c-74540c998b2a)

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.11-beta-8c81c98d8b

**Comment by seanlip** [comment] 2023-06-07 03:31
This is a blocker for 0.11. Assigning to @adhiamboperes for investigation.

**Comment by BenHenning** [comment] 2023-06-07 03:51
I’m assuming this is because of missing images. Will check and follow up once we have a fix in place for the missing images.

**Comment by seanlip** [comment] 2023-06-07 04:08
@BenHenning Just a note, this isn't due to missing images. It affects all multiple-choice questions, including those with text options. Here is the web version of the question:

![Screenshot from 2023-06-07 12-07-49](https://github.com/oppia/oppia-android/assets/10575562/17ab43b4-f430-4f3c-8670-cd1e38eb7244)

**Comment by MohitGupta121** [comment] 2023-06-07 04:16
@KolliAnitha @seanlip I am checking this in our GitHub codebase and local database but not found any question like this, is that a production app or database?

**Comment by seanlip** [comment] 2023-06-07 04:18
Yup this is a production question. But could you please check the demo exploration questions to see if any multiple-choice options display? Thanks!

**Comment by MohitGupta121** [comment] 2023-06-07 04:23
Okay Thanks @seanlip, checking.

**Comment by MohitGupta121** [comment] 2023-06-07 04:28
@seanlip Options are visible in development database:
Thanks.

<img src="https://github.com/oppia/oppia-android/assets/76530270/f30de1c8-a169-4289-a30d-89a606cb937e" height="400" style="max-width: 100%">

**Comment by seanlip** [comment] 2023-06-07 04:29
Hm, that's odd. Thanks for checking, @MohitGupta121. 

@KolliAnitha Just to check, are *any* multiple choice options visible in the build that you are testing?

**Comment by KolliAnitha** [comment] 2023-06-07 04:32
@seanlip None of the questions have multiple options. I verified in Place Values, Multiplication and Ratios and Proportional reasoning

**Comment by adhiamboperes** [comment] 2023-06-07 05:55
Preliminarily, I think this is an issue with image rendering, LaTeX or svg for android. For example, the screenshot @seanlip shared is LaTeX, and on the local build of the rc, none of the LaTeX display either in the lesson content or the multiple choice options are rendered. But plain text mcq options are rendered.
Edit: my local build does not show any images at all for any lesson.

**Comment by seanlip** [comment] 2023-06-07 06:00
@adhiamboperes I'm not sure about that? My screenshot is actually plaintext, not LaTeX. With LaTeX the math symbols would be bigger and in a different font.

Here's another screenshot that shows that the issue is not LaTeX/images:


![Screenshot from 2023-06-07 14-00-20](https://github.com/oppia/oppia-android/assets/10575562/39fd05ad-637b-434e-909a-5df98dae5efd)

**Comment by adhiamboperes** [comment] 2023-06-07 07:33
Okay, so interestind debugging experience, but finally found this exception
Glide exception:

```
23-08-16 12:25:53.920 24050-24050/org.oppia.android W/Glide: Load failed for https://storage.googleapis.com/oppiaserver-resources/exploration/umPkwp0L1M0-/assets/image/img_20180121_113315_pqwqhf863w_height_565_width_343.png with size [-2147483648x-2147483648]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    javax.net.ssl.SSLHandshakeException(Chain validation failed)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    javax.net.ssl.SSLHandshakeException(Chain validation failed)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    javax.net.ssl.SSLHandshakeException(Chain validation failed)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class javax.net.ssl.SSLHandshakeException: Chain validation failed
```

Which will occur if you are calling HTTPS API and the device date time is incorrect. See https://stackoverflow.com/a/69278955/11396524.

After fixing the time on my device all images and multiple choice options show.

The reason why some images are showing and others aren't is because some of them are cached locally and others are retrieved from gcs. This is per  https://github.com/oppia/oppia-android/blob/8c81c98d8bdeaca167190b99df793efafa7cf9fd/utility/src/main/java/org/oppia/android/util/caching/AssetRepository.kt#L42 and  https://github.com/oppia/oppia-android/blob/8c81c98d8bdeaca167190b99df793efafa7cf9fd/utility/src/main/java/org/oppia/android/util/caching/AssetRepository.kt#L49.

Can @KolliAnitha confirm if this helps?

**Comment by seanlip** [comment] 2023-06-07 13:02
Noting that this issue occurs for checkbox options too, and that it makes the lesson unplayable (I am doing some light testing as well).

**Comment by adhiamboperes** [comment] 2023-06-08 20:59
I am unable to reproduce this issue in any lesson.

<img src=https://github.com/oppia/oppia-android/assets/59600948/58d26d57-634e-4d97-9870-d5caced19203 width="400" height="900">

**Comment by BenHenning** [comment] 2023-06-09 07:24
d3e2fd2ce3bcc9a5cdbe6fb577e4251ebfc80283 from #4885 addresses this. The fixed lesson data will be included in the next beta RC.

**Closed as completed by BenHenning** 2023-06-09 07:24 UTC
Labels: bug, Impact: High, Work: High

**Comment by KolliAnitha** [comment] 2023-06-12 10:12
Working fine in 0.11-beta-8e0fcf19ac
![subject (8)](https://github.com/oppia/oppia-android/assets/101634267/f0fb0529-b1cb-4c97-86b9-6fd25b277134)
![subject (7)](https://github.com/oppia/oppia-android/assets/101634267/f7da5be2-9f1a-4717-92ab-92d244b26caf)
