### ISSUE TITLE
Edit Account button in Administrator Controls screen not responding.

### ISSUE THREAD

**Issue by ShivamMadlani** [oppia/oppia-android#4288] opened 2022-04-07 13:09 UTC
**Describe the bug**
"Edit Account" button in the "Administrator Controls" activity gives no response on clicking.

**To Reproduce**
1. Go to 'Administrator Controls'.
2. Click on 'Edit Account'.
3. See error

**Expected behavior**
The user should be able to edit the account details on clicking the "Edit Account" button.

**Demonstration**
<img src="https://user-images.githubusercontent.com/94903454/162203649-b8e81093-cace-4e97-b051-a2e4d1f2295e.jpg" height = "500"/>

https://user-images.githubusercontent.com/94903454/162204068-99fe8c6d-481e-4b8d-82d6-226d2e26e5d9.mp4

**Environment**
- Device/emulator being used: Pixel 3a API 28
- Android or SDK version (e.g. Android 5 or SDK 21): Android 9.0
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Comment by seanlip** [comment] 2022-04-07 13:16
Hi @ShivamMadlani, thanks for reporting! Note that this is tracked in https://github.com/oppia/oppia-android/issues/4006 too, so we might want to merge both issues.

**Comment by seanlip** [comment] 2022-04-07 13:20
Actually, to avoid confusion: closing this as a duplicate of #4006.

**Closed as completed by seanlip** 2022-04-07 13:20 UTC
Labels: Z-ibt

**Comment by ShivamMadlani** [comment] 2022-04-19 16:48
I reported this issue on Gitter when I came across it. I was told to create an issue for this by Apoorv. Also, I didnt know this issue already existed. Sorry for the inconvinience caused.

**Comment by seanlip** [comment] 2022-04-19 16:53
Not an issue! Closing duplicates is a regular thing we do to keep the issue tracker clean, so please don't worry -- you did the right thing.
