### ISSUE TITLE
[BUG]: Unable to submit answer to proceed to the next page in Fractions chapter 1

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#5050] opened 2023-06-12 06:28 UTC
**Describe the bug**
 Unable to submit answer to proceed to the next page in Fractions chapter 1

**To Reproduce**
1. Go to 'Fractions' - What is a Fraction
2. Click on Continue till you reach the page 'what fraction is shown by the coloured part of this picture
3. Enter 4/10 and click on Submit button
4. See that the submit button is disabled

**Expected behavior**
Submit button should be enabled after entering a fraction into the textbox

**Demonstration**
![subject (4)](https://github.com/oppia/oppia-android/assets/101634267/231616f0-6e99-43f7-80e0-3f09ff2db96b)

https://github.com/oppia/oppia-android/assets/101634267/10504e55-5187-4f45-bf54-ebb72ac02ec2

**Environment**
Device/emulator being used: Infinix SMART 5
Android or SDK version (e.g. Android 5 or SDK 21): Android 11
App version (you can get this through system app settings or via the admin controls menu in-app): 0.11-beta-8e0fcf19ac

**Comment by adhiamboperes** [comment] 2023-06-12 07:46
Update, there is an exception thrown when classifying the answer to this question:

```
2023-06-20 05:50:53.086 5048-5048/org.oppia.android E/StateFragment: Failed to retrieve answer outcome
    java.lang.IllegalStateException: Failed when classifying answer # org.oppia.android.app.model.InteractionObject@739e3e21
    fraction {
      denominator: 10
      numerator: 4
    } for interaction FractionInput
        at org.oppia.android.domain.classify.AnswerClassificationController.classifyAnswer(AnswerClassificationController.kt:80)
        at org.oppia.android.domain.classify.AnswerClassificationController.classify(AnswerClassificationController.kt:38)
        at org.oppia.android.domain.exploration.ExplorationProgressController$submitAnswerImpl$2.invokeSuspend(ExplorationProgressController.kt:615)
        at org.oppia.android.domain.exploration.ExplorationProgressController$submitAnswerImpl$2.invoke(Unknown Source:10)
        at org.oppia.android.domain.exploration.ExplorationProgressController.tryOperation(ExplorationProgressController.kt:785)
        at org.oppia.android.domain.exploration.ExplorationProgressController.tryOperation$default(ExplorationProgressController.kt:781)
        at org.oppia.android.domain.exploration.ExplorationProgressController.submitAnswerImpl(ExplorationProgressController.kt:596)
        at org.oppia.android.domain.exploration.ExplorationProgressController$createControllerCommandActor$1.invokeSuspend(ExplorationProgressController.kt:477)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: Expected input value to be of type SIGNED_INT not NON_NEGATIVE_INT
        at org.oppia.android.domain.classify.rules.GenericRuleClassifier.retrieveInputObject(GenericRuleClassifier.kt:49)
        at org.oppia.android.domain.classify.rules.GenericRuleClassifier.matches(GenericRuleClassifier.kt:35)
        at org.oppia.android.domain.classify.AnswerClassificationController.classifyAnswer(AnswerClassificationController.kt:67)
        at org.oppia.android.domain.classify.AnswerClassificationController.classify(AnswerClassificationController.kt:38) 
        at org.oppia.android.domain.exploration.ExplorationProgressController$submitAnswerImpl$2.invokeSuspend(ExplorationProgressController.kt:615) 
        at org.oppia.android.domain.exploration.ExplorationProgressController$submitAnswerImpl$2.invoke(Unknown Source:10) 
        at org.oppia.android.domain.exploration.ExplorationProgressController.tryOperation(ExplorationProgressController.kt:785) 
        at org.oppia.android.domain.exploration.ExplorationProgressController.tryOperation$default(ExplorationProgressController.kt:781) 
        at org.oppia.android.domain.exploration.ExplorationProgressController.submitAnswerImpl(ExplorationProgressController.kt:596) 
        at org.oppia.android.domain.exploration.ExplorationProgressController$createControllerCommandActor$1.invokeSuspend(ExplorationProgressController.kt:477) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

```

I would need to investigate the code in the `AnswerClassificationController` and `GenericRuleClassifier` classes.

**Comment by adhiamboperes** [comment] 2023-06-12 07:47
That said, I believe this is a content issue as there are additional problems I have noticed with this lesson.

Edit: This actually works fine on web, so it is a pipeline issue

**Comment by BenHenning** [comment] 2023-06-14 23:38
This is caused by a pipeline issue:
https://github.com/oppia/oppia-android/blob/d3e2fd2ce3bcc9a5cdbe6fb577e4251ebfc80283/scripts/src/java/org/oppia/android/scripts/assets/DtoProtoToLegacyProtoConverter.kt#L1515

That should be 'setSignedInt'.

**Comment by BenHenning** [comment] 2023-06-15 00:37
The fix is now checked into the pipeline branch & will be available on the next RC push of the release branch.

**Closed as completed by BenHenning** 2023-06-15 00:37 UTC
Labels: bug, Impact: High, Work: Medium

**Comment by KolliAnitha** [comment] 2023-06-16 17:16
Working fine in 0.11-beta-3343155232
![subject (12)](https://github.com/oppia/oppia-android/assets/101634267/92419f68-b54b-4185-92a0-5fe84ab492c4)
