### ISSUE TITLE
Merge profile_chooser_profile_view.xml into single xml file

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#3558] opened 2021-07-27 09:56 UTC
Currently there are 4 versions of `profile_chooser_profile_view.xml` file merge it into single xml file.

We can use https://text-compare.com/ to compare two versions of this file and for all the differences we can create variables in `dimens.xml` file and use it accordingly.

It can happen that it becomes really hard to merge all 4 files into single file, in such cases prefer code-readability over single file. Therefore it can be fine if in the end the code still contains 2 or 3 files.

**Note**: **In PR, make sure you add before and after screenshot of mobile-portrait, mobile-landscape, tablet-portrait and tablet-landscape for comparison and make sure that there is not difference between before and after UI.**

**Comment by Rishavgupta12345** [comment] 2021-11-25 05:10
i would like to work on this please assign me

**Comment by shubhanshu-coder** [comment] 2022-01-09 05:49
can u pl assign this to me and pl guide how to setup

**Comment by rt4914** [comment] 2022-01-19 07:41
@shubhanshu-coder 
Please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by Akshatkamboj14** [comment] 2022-01-24 18:55
Can You Please assign me this issue

**Comment by saudAnwar786** [comment] 2022-06-22 03:21
hello @rishidyno assign this to me

**Comment by rt4914** [comment] 2022-08-02 19:31
Unassigned because of inactivity.

**Comment by saudAnwar786** [comment] 2022-09-04 05:51
hello @rishidyno assign this to me

**Comment by dmdbilal** [comment] 2022-11-16 13:44
Can i work on this issue ?

**Comment by BenHenning** [comment] 2022-11-17 01:32
Hi @dmdbilal. It looks like this issue is indeed available—assigning it to you.

**Comment by dmdbilal** [comment] 2022-11-20 13:09
@rt4914 @BenHenning  I've some doubts.
How can i merge the style field with respect to the screen size(mobile, tablet)?.
and I'm just new to android development.

**Comment by dmdbilal** [comment] 2022-11-20 16:35
I have made a plan, that is I can merge the files (mobile-potrait, tab-potrait, tab-landscape) and i can't do anything in mobile-landscape because it's divider view is different from other. So I planned to leave it and finally i can make these 4 files into 2 files. But the problem is how can i put the style field of a view with respective to the screen size.

**Comment by rt4914** [comment] 2022-11-22 16:59
@dmdbilal Merging of files means that we want to reduce those files but if you think that we do need multiple files, then its fine you can create a PR accordingly to that. I think your plan here is correct.

**Comment by dmdbilal** [comment] 2022-11-24 15:13
I have merged the 3 layout files(mobile-potrait, tab-potrait, tab-landscape) into a single file and when i run it on the mobile it runs well. But i can't run the app on tablet. When the app opens then only the 'select your profile' text only show and after few seconds the app automatically quitted.
@rt4914 @BenHenning What did I done wrong?

**Comment by rt4914** [comment] 2022-11-24 16:32
@dmdbilal Try this solution https://github.com/oppia/oppia-android/wiki/Frequent-Errors-and-Solutions#crashing-layout-tags-in-tablet

**Comment by dmdbilal** [comment] 2022-11-25 15:30
@rt4914 @BenHenning I've deleted the tab-potrait layout and i can't delete the tab-landscape because the mobile-landscape is different from all others so I can't merge that and tab_layout is quite similar to mobile-potrait.

**Mobile Landscape**
![Before (Mobile-landscape)](https://user-images.githubusercontent.com/91405690/204015704-6af3a704-5fb1-4359-bca9-4a7d0a3691a1.png)

**Tab Landscape**
![before (tab-landscape)](https://user-images.githubusercontent.com/91405690/204015827-c8a0bdf9-012f-4231-a5ac-69ea944e4d1c.png)

If I delete the tab-landscape then the tab landscape view will same as like mobile-landscape.

And also if i delete the tab-potrait layout and leave the mobile-landscape, tab-landscape, mobile-potrait as it was, I'm getting this layout. But this layout works well in mobile-potrait.

**Tab potrait after deleting tab-potrait layout**
![Screenshot_20221125_205000](https://user-images.githubusercontent.com/91405690/204016245-51360654-a9c3-4a77-8251-30f91befea1f.png)

**Mobile Potrait**
![Before (Mobile-Portrait)](https://user-images.githubusercontent.com/91405690/204016486-833aad72-9a81-4629-8e38-2606f626a8c7.png)

**Comment by rt4914** [comment] 2022-11-26 12:00
> @rt4914 @BenHenning I've deleted the tab-potrait layout and i can't delete the tab-landscape because the mobile-landscape is different from all others so I can't merge that and tab_layout is quite similar to mobile-potrait.
> 
> **Mobile Landscape** ![Before (Mobile-landscape)](https://user-images.githubusercontent.com/91405690/204015704-6af3a704-5fb1-4359-bca9-4a7d0a3691a1.png)
> 
> **Tab Landscape** ![before (tab-landscape)](https://user-images.githubusercontent.com/91405690/204015827-c8a0bdf9-012f-4231-a5ac-69ea944e4d1c.png)
> 
> If I delete the tab-landscape then the tab landscape view will same as like mobile-landscape.
> 
> And also if i delete the tab-potrait layout and leave the mobile-landscape, tab-landscape, mobile-potrait as it was, I'm getting this layout. But this layout works well in mobile-potrait.
> 
> **Tab potrait after deleting tab-potrait layout** ![Screenshot_20221125_205000](https://user-images.githubusercontent.com/91405690/204016245-51360654-a9c3-4a77-8251-30f91befea1f.png)
> 
> **Mobile Potrait** ![Before (Mobile-Portrait)](https://user-images.githubusercontent.com/91405690/204016486-833aad72-9a81-4629-8e38-2606f626a8c7.png)

@dmdbilal Just make sure that before and after screenshot remains the same, if it means you cannot remove all files then its better to keep multiple files.

**Comment by dmdbilal** [comment] 2022-11-26 13:38
@rt4914 I think it can't be merged, because the text size of the views(profile_name_text, profile_last_visited, profile_is_admin_text) in mobile and tab layouts differ and as well as the position of the views also differ in mobile-landscape from others.

**Comment by dmdbilal** [comment] 2022-11-26 13:41
I've seen other PRs and there the layout files for both mobile and tablet view has no different text sizes, all of them have a common size. So this makes this profile_chooser_profile_vew layout different from others.

**Comment by yash10019coder** [comment] 2022-12-04 11:15
Hi @dmdbilal could you try to like make the text size into a single variable name and assign them to all of thee dimens.xml for different configurations like for mobile tablet, port and landscape?

**Comment by dmdbilal** [comment] 2022-12-09 12:57
> Hi @dmdbilal could you try to like make the text size into a single variable name and assign them to all of thee dimens.xml for different configurations like for mobile tablet, port and landscape?

@yash10019coder I've replaced the text.size of those layouts to separate dimens.xml. and I've a problem that is when I deleted the layouts for tab land and port i can run the app for mobile but when I run it on tab it crashes suddenly.

**Comment by yash10019coder** [comment] 2022-12-09 14:16
Could you create a PR so that i can debug the code?

**Comment by yash10019coder** [comment] 2022-12-09 14:16
> > Hi @dmdbilal could you try to like make the text size into a single variable name and assign them to all of thee dimens.xml for different configurations like for mobile tablet, port and landscape?
> 
> @yash10019coder I've replaced the text.size of those layouts to separate dimens.xml. and I've a problem that is when I deleted the layouts for tab land and port i can run the app for mobile but when I run it on tab it crashes suddenly.

@dmdbilal Could you create a PR so that i can debug the code?

**Comment by dmdbilal** [comment] 2022-12-09 14:34
@yash10019coder I've created the PR and you can check now.

**Comment by seanlip** [comment] 2023-03-28 08:55
Deassigning @dmdbilal due to inactivity.

**Comment by seanlip** [comment] 2023-04-05 04:43
Per discussion with @BenHenning, closing this issue because it looks like merging these files is a bit complicated and probably not worth it.

**Closed as not planned by seanlip** 2023-04-05 04:43 UTC
Labels: Priority: Nice-to-have, good first issue, Impact: Low, Z-ibt, enhancement
