### ISSUE TITLE
Recently Played Topic Cards Keep Sliding Back n Forth

### ISSUE THREAD

**Issue by Arjupta** [oppia/oppia-android#2288] opened 2020-12-17 15:01 UTC
**Describe the bug**
The Recently Played Topics are shown at the start of the screen after a user log-in. The Cards which are shown there keep moving back and forth without any interaction by user
**To Reproduce**
1. Open the App and start the exploration on First Test Topic
2. Complete Prototype Exploration of First Story under it
3. Go back to the homepage and explore other topics
4. You will see that after going through few explorations this issue happens.

**Expected behavior**
The Recent Topic Cards should move only after the detection of any gesture by the user.

**Screenshots**
![ezgif-6-7e4d012e095d](https://user-images.githubusercontent.com/64064110/102504394-c80d5d80-40a6-11eb-85a9-35f8efa951e8.gif)

**Device**
- Physical device ( Real Me 3 )
- SDK 29

**Additional context**
The Steps to repeat the error might not work for everyone, because the process is not completely known to me also

**Comment by Arjupta** [comment] 2020-12-17 15:03
@rt4914 can you try to reproduce it

**Comment by rt4914** [comment] 2020-12-17 16:54
> @rt4914 can you try to reproduce it

Yes I have noticed this recently again in emulator.

**Comment by yk1ax** [comment] 2020-12-18 12:48
I tried to reproduce this but couldn't because I came across another bug while doing it on my physical device where it isn't showing the input option for forward slash. My device has Samsung Keyboard by default so I tried reproducing it after downloading Gboard and then the keyboard is being shown as expected. So this should be considered as a bug in samsung keyboard right? But this could turn out to be an issue for a considerable number of users. What should we do about it then ?

<img src="https://user-images.githubusercontent.com/54735451/102616362-7378e980-415d-11eb-8fb8-dc4102b56d3f.jpg" width="300"> <img src="https://user-images.githubusercontent.com/54735451/102616375-78d63400-415d-11eb-8423-cb426b2fb2e7.jpg" width="300">

**Comment by rt4914** [comment] 2020-12-18 16:39
@yk1ax Thanks a lot. Can you please file a **bug** for this issue so that we can keep track of it.

**Comment by yk1ax** [comment] 2020-12-18 16:41
> @yk1ax Thanks a lot. Can you please file a **bug** for this issue so that we can keep track of it.

Ok sure I'll do that soon.

**Comment by imraghav20** [comment] 2021-01-20 12:27
@rt4914 can I work on this issue?

**Comment by imraghav20** [comment] 2021-01-21 13:15
Is this the right file concerned?
https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingListAdapter.kt

**Comment by rt4914** [comment] 2021-01-21 15:55
> Is this the right file concerned?
> https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingListAdapter.kt

No. The correct file is https://github.com/oppia/oppia-android/blob/d305f94bf315e2dbf4ee65447dbae98b96503022/app/src/main/java/org/oppia/android/app/home/HomeFragmentPresenter.kt#L93

Note: It might be the case that this issue not reproducible anymore. So first try to reproduce this.

**Comment by imraghav20** [comment] 2021-01-21 18:09
> > Is this the right file concerned?
> > https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingListAdapter.kt
> 
> No. The correct file is
> 
> https://github.com/oppia/oppia-android/blob/d305f94bf315e2dbf4ee65447dbae98b96503022/app/src/main/java/org/oppia/android/app/home/HomeFragmentPresenter.kt#L93
> 
> Note: It might be the case that this issue not reproducible anymore. So first try to reproduce this.

Yes the bug still exists. I tried to reproduce it.

**Comment by jcqli** [comment] 2021-01-21 18:45
I think [PromotedStoryListView](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/home/promotedlist/PromotedStoryListView.kt) is also a relevant file (or maybe is relevant instead of the HomeFragmentPresenter). [StartSnapHelper](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/recyclerview/StartSnapHelper.kt) might also be related

**Comment by imraghav20** [comment] 2021-01-23 12:01
> > > Is this the right file concerned?
> > > https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/home/recentlyplayed/OngoingListAdapter.kt
> > 
> > 
> > No. The correct file is
> > https://github.com/oppia/oppia-android/blob/d305f94bf315e2dbf4ee65447dbae98b96503022/app/src/main/java/org/oppia/android/app/home/HomeFragmentPresenter.kt#L93
> > 
> > Note: It might be the case that this issue not reproducible anymore. So first try to reproduce this.
> 
> Yes the bug still exists. I tried to reproduce it.

@rt4914 in the latest pull I saw that the issue has been resolved and does not exist.

**Comment by imraghav20** [comment] 2021-01-23 12:19
The issue was solved as a part of #632

**Comment by FareesHussain** [comment] 2021-01-23 17:53
> The issue was solved as a part of #632

@ARJUPTA can you check this now it seems to be fixed in https://github.com/oppia/oppia-android/pull/2246
Can you check if you can reproduce this

**Comment by Arjupta** [comment] 2021-01-23 18:01
@FareesHussain I am also not able to see it now. Also it is very tough to reproduce, if @rt4914 is also not able to produce this then we can close this issue

**Comment by rt4914** [comment] 2021-01-23 19:17
Thanks what I suspected too. This is no more reproducible. Thanks @FareesHussain @ARJUPTA and @imraghav20

**Closed as completed by rt4914** 2021-01-23 19:17 UTC
Labels: Z-ibt
