### ISSUE TITLE
Audio player running after closing 

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1801] opened 2020-09-04 13:29 UTC
**Describe the bug**
Alpha release apk

**To Reproduce**
1. Start an exploration
2. Play audio - listen completely
3. Answer correct - continue
4. Next state
5. Click on audio icon in toolbar - this close the player - hide the audio player from screen
6. You can hear the voiceover now also

[Video File](https://drive.google.com/file/d/1hOncsuKvQwQyA0dCyuoVj4P6H60wJoqg/view?usp=sharing) describing the issue.

**Expected behavior**
After closing the audio player, player should not run

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Device**
- Redmi note 5 pro

**Additional context**
Note that a related issue is #2893 which is caused by the same synchronization issues in the audio player.

**Comment by Arjupta** [comment] 2020-09-30 04:56
@rt4914  I am unable to reproduce this error.

**Steps to reproduce**
- Opened Exploration _(Fractions)_
- Opened the _Lessons_ Tab and started the _What is fraction?_ topic
- Clicked the audio button from toolbar and audio started playing after agreeing to the data usage dialog
- After audio completed playing clicked the Continue button, next screen opens and the audio has started playing but it is related to that particular screen only

**Device**  - Realme -3 

Have I performed any wrong step?

**Comment by anandwana001** [comment] 2020-09-30 05:05
> @rt4914 I am unable to reproduce this error.
> 
> **Steps to reproduce**
> 
> * Opened Exploration _(Fractions)_
> * Opened the _Lessons_ Tab and started the _What is fraction?_ topic
> * Clicked the audio button from toolbar and audio started playing after agreeing to the data usage dialog
> * After audio completed playing clicked the Continue button, next screen opens and the audio has started playing but it is related to that particular screen only
> 
> **Device** - Realme -3
> 
> Have I performed any wrong step?

@ARJUPTA 
**To Reproduce**
Steps to reproduce the behavior:
1. Start an exploration
2. Play audio - listen completely
3. Answer correct - continue
4. Next state
5. **Click on audio icon in toolbar - this close the audio player - hide the audio player from screen**
6. You can hear the voiceover now also as the audio icon is showing no audio as we had already clicked on it.

**Comment by Arjupta** [comment] 2020-09-30 05:30
@anandwana001 Sir even after answering a question correctly and moving on to next screen with audio bar present which is then closed by clicking on the toolbar. No voiceover audio was playing, everything worked normally. Can't reproduce the error :(

**Comment by BenHenning** [comment] 2020-09-30 06:33
@anandwana001 is this consistently reproducible for you? Also, for both @anandwana001 & @ARJUPTA I suggest mentioning what device/emulator & SDK you're trying to repro this one since issues like this can sometimes be device specific, or not/only reproducible on an emulator vs. real device.

**Comment by Arjupta** [comment] 2020-09-30 07:02
> @anandwana001 is this consistently reproducible for you? Also, for both @anandwana001 & @ARJUPTA I suggest mentioning what device/emulator & SDK you're trying to repro this one since issues like this can sometimes be device specific, or not/only reproducible on an emulator vs. real device.

@BenHenning details of the device are as follows-
1) Real device
1) Android 10 (API level 29) 
2) Realme 3 (Color OS)

**Comment by anandwana001** [comment] 2020-09-30 07:06
> @anandwana001 is this consistently reproducible for you? Also, for both @anandwana001 & @ARJUPTA I suggest mentioning what device/emulator & SDK you're trying to repro this one since issues like this can sometimes be device specific, or not/only reproducible on an emulator vs. real device.

Yes, this is consistently reproducible. 

1. Real device - Redmi note 5 pro / API 28
2. Real/Virtual device - Pixel 3aXL - API 28 and 30

**Comment by BenHenning** [comment] 2020-09-30 19:43
Hmm @anandwana001 are you able to repro on Pixel 3a emulator? That might be useful to try since then others can test in the same environment.

**Comment by anandwana001** [comment] 2020-09-30 22:43
> Hmm @anandwana001 are you able to repro on Pixel 3a emulator? That might be useful to try since then others can test in the same environment.

Yes @BenHenning , It is repro on pixel 3a emulator (virtual). I am checking if I can create a screen record for this and will add here.

**Comment by BenHenning** [comment] 2020-10-01 03:25
Aha, that's great to know @anandwana001. A recording would be useful.

@ARJUPTA are you able to repro it using the steps above when trying on a Pixel 3a emulator locally?

**Comment by anandwana001** [comment] 2020-10-01 04:33
@BenHenning @ARJUPTA 
Please have a look at this [video file](https://drive.google.com/file/d/1hOncsuKvQwQyA0dCyuoVj4P6H60wJoqg/view?usp=sharing),  If you know the steps to repo this you can skip to 0:58 seconds.

**Comment by Arjupta** [comment] 2020-10-01 06:57
@BenHenning and @anandwana001 , also check my recording with same steps. I will also test it on pixel3a. [video link](https://drive.google.com/file/d/1Vum62Kza8zC3AOiUXcLJxzUiHv6uFP7u/view?usp=drivesdk)

**Comment by anandwana001** [comment] 2020-10-01 07:22
Ok, let me check in a bit deep. I will test on bit more devices and see if I could repro this issue.

**Comment by Arjupta** [comment] 2020-10-02 05:08
@BenHenning I also tried it on Pixel 3a (API 27) Virtual Device, but still there was no error encountered

**Comment by BenHenning** [comment] 2020-10-02 05:27
Interesting. @ARJUPTA would you be able to share a recorded video of your repro attempts? That might better help us understand if there are any differences. 

Otherwise, if we can’t figure out what’s going wrong then we should add logs and have Akshay repro it to see if we can get more data on what might be happening.

**Comment by Arjupta** [comment] 2020-10-02 06:21
> Interesting. @ARJUPTA would you be able to share a recorded video of your repro attempts? That might better help us understand if there are any differences.
> 
> Otherwise, if we can’t figure out what’s going wrong then we should add logs and have Akshay repro it to see if we can get more data on what might be happening.

@BenHenning sir, this is the [recorded video](https://drive.google.com/file/d/1CMzz_lQDYA9CnCiJ06KI2RrPWEjrhC8Q/view?usp=sharing). Here we can see that the audio on the second screen closes once the toolbar icon is pressed. Ignore the buffering of audio (・ω・)

**Comment by anandwana001** [comment] 2020-10-02 06:23
> > Interesting. @ARJUPTA would you be able to share a recorded video of your repro attempts? That might better help us understand if there are any differences.
> > Otherwise, if we can’t figure out what’s going wrong then we should add logs and have Akshay repro it to see if we can get more data on what might be happening.
> 
> @BenHenning sir, this is the [recorded video](https://drive.google.com/file/d/1CMzz_lQDYA9CnCiJ06KI2RrPWEjrhC8Q/view?usp=sharing). Here we can see that the audio on the second screen closes once the toolbar icon is pressed. Ignore the buffering of audio (・ω・)

Could you try clicking on the audio icon as soon as you click the continue button? You can check the video in the issue description. So, before the audio begins after clicking the continue, you switch the audio off.

**Comment by Arjupta** [comment] 2020-10-02 09:36
> > > Interesting. @ARJUPTA would you be able to share a recorded video of your repro attempts? That might better help us understand if there are any differences.
> > > Otherwise, if we can’t figure out what’s going wrong then we should add logs and have Akshay repro it to see if we can get more data on what might be happening.
> > 
> > 
> > @BenHenning sir, this is the [recorded video](https://drive.google.com/file/d/1CMzz_lQDYA9CnCiJ06KI2RrPWEjrhC8Q/view?usp=sharing). Here we can see that the audio on the second screen closes once the toolbar icon is pressed. Ignore the buffering of audio (・ω・)
> 
> Could you try clicking on the audio icon as soon as you click the continue button? You can check the video in the issue description. So, before the audio begins after clicking the continue, you switch the audio off.

Yes @anandwana001, this time that error occurred? @BenHenning sir, Instantly clicking over that button before audio starts causes it. Looks like a corner case to handle.

**Comment by BenHenning** [comment] 2020-10-02 19:56
Ah, glad we clarified that missing part of the repro steps. 

We should still fix this since it’s not entirely obvious whether this corner case can be more easily hit by some folks (consider slower devices).

**Comment by Arjupta** [comment] 2020-10-03 03:17
> Ah, glad we clarified that missing part of the repro steps.
> 
> We should still fix this since it’s not entirely obvious whether this corner case can be more easily hit by some folks (consider slower devices).

@BenHenning sir then how can this be taken care of? Can you provide me with some steps to solve this issue? I want to work on it.

**Comment by BenHenning** [comment] 2020-10-05 23:09
@ARJUPTA since you can repro the issue, you will need to add log lines and step through the code in order to figure out what’s broken.

You should start by analyzing how the app behaves when it does the right thing. Look through related functions for audio, observe how they behave when you go through a similar repro scenario without hitting the bug.

Once you have an idea how things work without the bug, repro the bug and observe how things have changed. That help you find what area of code is doing the wrong thing. From there, you can work toward a solution. 

This is a bit high level, but does it help at all?

**Comment by Arjupta** [comment] 2020-10-06 08:11
@BenHenning sir the steps you mentioned are surely helpful , but can I also get to know some files which are related audio playing. Just some filenames which I need to start understand, rest I will ask you for help when needed.
Thanks

**Comment by BenHenning** [comment] 2020-10-06 19:50
Sure. I suggest starting with https://github.com/oppia/oppia-android/blob/develop/app/src/main/res/layout/audio_fragment.xml and https://github.com/oppia/oppia-android/blob/74db288b9ac25fb942a8feb35e918bcd7e94e55c/app/src/main/java/org/oppia/android/app/player/audio/AudioViewModel.kt#L117.

In general, one way to find the code that needs to change is to run the app & search for strings in code, then work backward to find the layouts & corresponding view models that show that UI. You can continue searching for related files until you find the fragment & activity that use these views, as well as what service-level controllers are used to do the actual audio playing logic. The latter searching is done by looking for uses of views, strings, method calls, classes, etc. (which can be done within Android Studio).

**Comment by srikanthkb** [comment] 2021-01-18 11:58
Here's an update on investigating this issue:

- `ExplorationActivity` hosts the audio option in the toolbar. 
- Audio option is enabled and disabled by extending the `AudioUiManager` interface. 
- And when we click the "audio" button in `ExplorationActivity`, depending on the state of the AudioFragment, the method implementations of `enableAudioPlayback` and `disableAudioPlayback` are called. 
- These methods further call `hideAudioFragment` (or) `showAudioFragment` 
https://github.com/oppia/oppia-android/blob/d35588c38d101e96774557f97a6202432011aa18/app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt#L258 
- Finally, the call to the `viewModel` is made in the following line 
https://github.com/oppia/oppia-android/blob/d35588c38d101e96774557f97a6202432011aa18/app/src/main/java/org/oppia/android/app/player/audio/AudioFragmentPresenter.kt#L191-L194

- With a few debug statements in the code-flow, we can infer that it takes between 1 and 2 seconds for the `prepared` variable to be updated
![image](https://user-images.githubusercontent.com/36214903/104911749-5714da80-59b1-11eb-8ed9-24457da170a0.png)

- So, if we click the audio button (to disable playback), in this span of 1-2 seconds, the `prepared` value would be `false`, in which case the code block inside `if(prepared)`, i.e. `viewModel.pauseAudio()` is not called, and hence the audio keeps playing, even though the UI closes the AudioFragment.

Also, another way to reproduce this bug would be as follows:
- Start an exploration
- Double-click the audio playback button
-  The audio should will continue to play, while the Audio fragment closes the media player.

**Closed as completed** 2023-02-02 00:45 UTC
Labels: Impact: Low, Issue: Needs Clarification, Z-ibt

**Comment by KevinGitonga** [comment] 2023-02-02 07:06
Thank's @BenHenning.
