### ISSUE TITLE
Some views have very low visibility on add user profile screen in dark mode [A11y]

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4738] opened 2022-11-17 14:15 UTC
**Describe the bug**

The "Required" text below name text input field and the info icon on add new user profile screen have very low visibility. They are also result in text and image contrast issues when run under an accessibility scanner. Attaching a screenshot for reference.

![image](https://user-images.githubusercontent.com/64526117/202469542-f93e75c8-3cd3-4ac2-b0b0-c084bded03b6.png)

**To Reproduce**
1. Using dark mode, click on add new user profile on profiles screen
2. info icon and help text have a contrast issue

**Environment**
- Device/emulator being used: <Vivo V25 pro>
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment] 2022-11-18 10:00
Doesn't need to be release blocking since this seems like a dark mode-specific issue.

**Comment by MohitGupta121** [comment] 2022-11-29 18:19
@BenHenning I think this issue is fixed by @rt4914 in PR #4774 
So can we close this issue @rt4914 ?

|||
|:----------------------------------------:|:-----------------------------------------:|
| ![](https://user-images.githubusercontent.com/9396084/204584535-12a46e7d-9ffa-48ce-8eeb-8499287814af.png) | ![](https://user-images.githubusercontent.com/9396084/204584551-afd0b186-f954-4f9f-ae93-587a3c7c2aa2.png) |
|||

**Comment by BenHenning** [comment] 2022-11-29 19:24
@MohitGupta121 shouldn't this only be closed once that PR is merged? If the issue isn't addressed yet on develop, it should remain open (since it isn't fixed yet).

**Comment by MohitGupta121** [comment] 2022-11-30 03:31
> @MohitGupta121 shouldn't this only be closed once that PR is merged? If the issue isn't addressed yet on develop, it should remain open (since it isn't fixed yet).

Yes, this will close when the PR gets merged, I mentioned this issue in that PR.

**Closed as completed** 2022-12-10 19:41 UTC
