### ISSUE TITLE
[Tablet] Highfi AdminPinActivity

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2118] opened 2020-11-16 14:59 UTC
Currently `AdminPinActivity` screen does not have dedicated tablet layout design in develop.
Implement the `AdminPinActivity` for landscape and portrait mode for tablet devices.
Mock Link: https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/6876c089-6ee6-48d4-85bb-880be3b5ac35/

Reference: https://github.com/oppia/oppia-android/wiki/Working-on-UI

**Comment by FareesHussain** [comment] 2020-11-18 13:41
Please assign this to me

**Comment by FareesHussain** [comment] 2020-11-20 04:53
@rt4914 please review

**Comment by rt4914** [comment] 2020-11-20 07:15
> @rt4914 please review

@FareesHussain Please mention the reviewing part on PR and not on issues. Thanks.

**Comment by FareesHussain** [comment] 2020-11-23 03:55
@rt4914 I'm closing #2125 as it is the duplicate of #2129 which I created cause some checks were not passing

**Closed as completed** 2020-11-23 13:19 UTC
Labels: Priority: Essential, good first issue, Type: Task, Z-ibt
