### ISSUE TITLE
When Reading text size is extra large, Previous responses are not aligned properly in the question page

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4371] opened 2022-05-23 11:41 UTC
**Describe the bug**
When Reading text size is extra large, Previous responses are not aligned properly in the question page

**To Reproduce**
1. Go to 'Options'- Select Reading text size as Extra Large
2. Open any chapter say 'Order of Operations
3. Go to Question page- Enter multiple incorrect answers
4. See the Previous Responses bar displayed

**Expected behavior**
Previous Responses and count should be aligned properly as for text size medium

![Screenshot_2022-05-23-17-06-04-91_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/169811807-585e0fc0-a99d-49c1-8142-6c84fadcf939.jpg)

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

**Comment by deonwaju** [comment] 2024-03-21 04:34
This issue seems to be resolved already in recent versions @adhiamboperes, please find attached screen recordings and screenshots of 4 different screen sizes of mobile devices. 

Screen Recording of a 4.0" mobile device:

https://github.com/oppia/oppia-android/assets/54560535/a9c40c73-ae08-460d-981d-c57214e7394f

<img width="273" alt="Screenshot 2024-03-21 at 05 11 48" src="https://github.com/oppia/oppia-android/assets/54560535/53a3f8eb-78f5-4427-8c55-083103f75b0c">

Screen Recording of a 5.0" mobile device:

https://github.com/oppia/oppia-android/assets/54560535/8bfc391a-d862-4d78-a494-e65e490929cb

<img width="354" alt="Screenshot 2024-03-21 at 04 53 07" src="https://github.com/oppia/oppia-android/assets/54560535/43f50b36-644b-49c1-8741-6dfdea6a922a">

Screen Recording of a 5.6" mobile device:

https://github.com/oppia/oppia-android/assets/54560535/a4ba023e-967b-498c-8fad-3a2f3797dc2d

 <img width="349" alt="Screenshot 2024-03-21 at 05 31 41" src="https://github.com/oppia/oppia-android/assets/54560535/c9ec2459-2b2d-4abd-8da3-889f5ff35bff">


 Screen Recording of a 6.3"  mobile device:

https://github.com/oppia/oppia-android/assets/54560535/1bd72b9c-64a7-49da-ae74-72371d3b55d6

<img width="354" alt="Screenshot 2024-03-21 at 05 33 03" src="https://github.com/oppia/oppia-android/assets/54560535/ac9a431f-e331-467b-aa86-c425a207e690">

**Comment by adhiamboperes** [comment] 2024-03-21 10:17
Thanks @deonwaju for the comprehensive recordings! 

I'm closing this issue as not reproducible.

**Closed as not planned by adhiamboperes** 2024-03-21 10:17 UTC
Labels: Impact: Low, Z-ibt, bug, Work: Medium
