### ISSUE TITLE
Tablet Story Card UI

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3109] opened 2021-04-21 08:26 UTC
**Describe the bug**
The cards UI needs to fix as per the tablet

**To Reproduce**
1. Open the app on a tablet
2. Click on any card on home screen
3. Go to the lesson tab
4. Click on the topic name
5. The card screen gets open

**Expected behavior**
The card size would be adequate as per the tablet

**Screenshots**
![Screenshot_1618993429](https://user-images.githubusercontent.com/25057618/115521979-4ffbb200-a2a9-11eb-9f08-f02704b7109a.png)
![Screenshot_1618993716](https://user-images.githubusercontent.com/25057618/115522393-b1238580-a2a9-11eb-82e5-faf3a92a3636.png)

**Device**
- emulator being used
- SDK version - Pixel C API 28

**Comment by AnubhavPabby** [comment] 2021-05-03 19:03
Hey can i work on this issue?

**Comment by anandwana001** [comment] 2021-05-04 01:50
@AnubhavPabby begin here - https://github.com/oppia/oppia-android/wiki#onboarding-instructions

**Comment by AnubhavPabby** [comment] 2021-05-04 07:17
@anandwana001 I have read the wiki and have done all the necessary setup and performed the onboarding instructions

**Comment by anandwana001** [comment] 2021-05-04 07:46
@mschanteltc could you check if we have any specific size for these cards on tablet UI?

**Comment by mschanteltc** [comment] 2021-05-04 19:37
> @mschanteltc could you check if we have any specific size for these cards on tablet UI?

The cards should be the same size as mobile's. PTAL a this [mock](https://xd.adobe.com/view/d405de00-a871-4f0f-73a0-f8acef30349b-a234/screen/d70a3ade-826a-4ac6-95e6-907a24d7b896/).

**Comment by anandwana001** [comment] 2021-05-05 00:59
Thanks, @mschanteltc for clearing this. 

@AnubhavPabby I had assigned this issue to you.

**Comment by AnubhavPabby** [comment] 2021-05-05 20:17
@anandwana001 Hey I have started working on it

**Comment by rt4914** [comment] 2021-05-06 13:00
@AnubhavPabby Actually I will have to close this issue as it was a duplicate of #1824 which I am already working on.

**Closed as completed by rt4914** 2021-05-06 13:00 UTC
Labels: good first issue, Z-ibt
