### ISSUE TITLE
Text size updating for other screens

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1540] opened 2020-07-29 13:04 UTC
**Describe the bug**

- [ ] Text Size of Exploration not changing as soon as we update the text size in options.
- [x] Text Size also affecting the Options Screen text `OptionsActivity` as well as `HelpActivity` or any possible screen we can go after starting Exploration.

**To Reproduce**
Steps to reproduce the behaviour:
Go to any exploration -> click on overflow menu -> `options` -> change the text size -> back to exploration -> **text size not changed** -> leave the exploration -> enter the exploration again -> **text size changed** -> click on overflow menu -> 
**text size of menu gets affected** -> click on `options` or `help` -> you can see text size affected for all text on screen

**Expected behaviour**
Text size should only be updated for the only exploration player, not any other screen

**Screenshots**
<p>
<img src="https://user-images.githubusercontent.com/25057618/88802239-6a947500-d1c8-11ea-974c-1746f4a31cec.png" width="250" height="450"/>
<img src="https://user-images.githubusercontent.com/25057618/88802250-6e27fc00-d1c8-11ea-8e18-3cf211c5fa82.png" width="250" height="450"/>
<img src="https://user-images.githubusercontent.com/25057618/88802254-6ec09280-d1c8-11ea-851b-a23703c0316d.png" width="250" height="450"/>
<img src="https://user-images.githubusercontent.com/25057618/88802258-6f592900-d1c8-11ea-9d1e-b347411ae763.png" width="250" height="450"/>
</p>

**Device**
Pixel XL API 28

**Comment by BenHenning** [comment] 2020-07-29 16:41
I think we shouldn't block alpha on this bug. While it's annoying, it's not totally app breaking & alpha is focusing on core functionality, not peripheral behaviors.

**Comment by anandwana001** [comment] 2020-07-29 16:52
Ok

> I think we shouldn't block alpha on this bug. While it's annoying, it's not totally app breaking & alpha is focusing on core functionality, not peripheral behaviors.

Ok, Let's take this on later

**Comment by rt4914** [comment] 2020-09-24 19:01
@rt4914 Assigning this to myself for now so that I can divide this into multiple issues.

**Comment by FareesHussain** [comment] 2021-01-05 09:09
@rt4914 I'll create a PR for the second bug in the description as the first bug requires some time

**Comment by rt4914** [comment] 2021-01-05 09:13
> @rt4914 I'll create a PR for the second bug in the description as the first bug requires some time

@FareesHussain Sounds good.

**Comment by prayutsu** [comment] 2021-04-27 06:55
/cc @BenHenning 

When reading text size is updated, the other UI components like DialogFragment are also affected - 
![Screenshot_2021-04-27-11-26-11-738_org oppia android](https://user-images.githubusercontent.com/54636525/116198448-93479c00-a753-11eb-9375-7efa6f4842fb.jpg)

**Comment by BenHenning** [comment] 2021-04-28 02:27
Note that this was found while testing alpha MR2 but is determined to not be a blocker.

**Comment by rt4914** [comment] 2021-11-18 16:46
@FareesHussain Unassigning you from this issue because of inactivity, please re-assign yourself if you are currently working on this.

**Comment by MohitGupta121** [comment] 2022-10-11 14:15
@BenHenning I'm try to reproduce this issue but for `LessonFragment` text size is changing as soon as we update, we need this as solution?

But for the `RevisionFragment` even Text Size is not changing from all ways. Text size changing is not implement for `RevisionFragment` or it's an issue?

https://user-images.githubusercontent.com/76530270/195115459-ce9a6b18-8c91-429d-8e6d-ae53d495945c.mp4

**Comment by BenHenning** [comment] 2022-10-11 16:42
Thanks @MohitGupta121. I think this was fixed in #4411 so we can close this.

**Closed as not planned by BenHenning** 2022-10-11 16:42 UTC
Labels: Impact: Medium, Issue: Needs Clarification, Z-ibt
