### ISSUE TITLE
When Reading text size is changed from in lesson options it is not reflected immediately 

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4372] opened 2022-05-23 11:46 UTC
**Describe the bug**
When Reading text size is changed from in lesson options it is not reflected immediately 

**To Reproduce**
1. Go to Expressions and Equations- Open Evaluating Expressions
2. Click on Continue
3. Click on more options and select Reading Text size 
4. Change it from medium to small
5. Navigate back to the lesson page
6. The text size is not changed to small

**Expected behavior**
On changing the text size it should be applied to the lesson and should display it in the selected format

https://user-images.githubusercontent.com/101634267/169812544-f9d7b64a-b953-4f3c-92a0-da7c7c4ffb29.mp4

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

**Comment by BenHenning** [comment] 2022-06-16 20:24
Duplicate of #4285.

**Closed as not planned by BenHenning** 2022-06-16 20:24 UTC
Labels: Impact: Low, Z-ibt

**Comment by KolliAnitha** [comment] 2022-11-13 08:23
Unable to test this as In-lesson options are not Opening #4712

**Comment by KolliAnitha** [comment] 2022-11-24 06:05
Working fine in RC02 version of beta MR2.

https://user-images.githubusercontent.com/101634267/203706419-567efc41-2724-41c8-8ae0-d5d40326c4f7.mp4
