### ISSUE TITLE
Profile name is not properly aligned

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#2669] opened 2021-02-09 11:08 UTC
**Describe the bug**
username is not properly aligned on the profile page.

**To Reproduce**
1. click on the navigation drawer icon
2. Click on the profile picture
3. See the error

**Expected behavior**
The username should be correctly aligned in the center.

**Screenshots**

<img src="https://user-images.githubusercontent.com/53645584/107355062-fcc0f280-6af4-11eb-85f4-6ccac5d6c8e8.jpg" alt="Screenshot_20210209-141125" width="250"/>

**Device**
- Device/emulator being used: Real device Oneplus 7
- SDK version 29

**Comment by prayutsu** [comment] 2021-02-09 11:23
@rt4914 Do we need the username in the center?

**Comment by yashraj-01** [comment] 2021-02-09 12:13
@MaskedCarrot can I work on this issue?

**Comment by MaskedCarrot** [comment] 2021-02-09 12:14
@yashraj-iitr Please wait for @rt4914's review on this.

**Comment by yashraj-01** [comment] 2021-02-09 12:17
> @yashraj-iitr Please wait for @rt4914's review on this.

sure. thanks.

**Comment by rt4914** [comment] 2021-02-09 13:18
As per mocks it should be in centre. Thanks @MaskedCarrot . Assigning this to @yashraj-iitr 

https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/7fb5929e-4652-4412-bf8c-64d94f4159f9/

**Comment by anandwana001** [comment] 2021-02-09 16:32
Before fixing this issue, could anyone please check the commit history of this file and see which PR cause this issue, because as far as I remember there exist no such issue earlier.

**Comment by yashraj-01** [comment] 2021-02-09 17:04
> Before fixing this issue, could anyone please check the commit history of this file and see which PR cause this issue, because as far as I remember there exist no such issue earlier.

I found out that the related code was modified in PR #2556. So maybe this was the cause.

**Comment by yashraj-01** [comment] 2021-02-09 17:26
<img width="270" height="555" src="https://user-images.githubusercontent.com/63469151/107400748-221b2400-6b28-11eb-80de-ffdf312ab11d.png">

@rt4914 @MaskedCarrot @anandwana001 I think username displayed here is not so good. We should restrict it to a single line, at least in portrait mode. What are your thoughts?

Also, I have centre aligned username in `profile_progress_header.xml`. I'll be making a PR shortly for it.
<img width="270" height="555" src="https://user-images.githubusercontent.com/63469151/107401223-a9689780-6b28-11eb-8ac6-0f205f4ee568.png">

**Comment by yashraj-01** [comment] 2021-02-09 17:36
> As per mocks it should be in centre. Thanks @MaskedCarrot . Assigning this to @yashraj-iitr
> 
> https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/7fb5929e-4652-4412-bf8c-64d94f4159f9/

@rt4914 is the username is centred aligned in other layouts as well i.e, `layout-land`, `layout-sw600dp-port` and `layout-sw600dp-land`?

**Comment by anandwana001** [comment] 2021-02-09 17:46
We cannot restrict them in one line, what if the name is long enough to not fit in one line.
Name reference - https://github.com/oppia/oppia-android/pull/2556#issuecomment-768023638

Try using similar example in your pr to see if all the names are fitting and looking correctly or not.

**Comment by yashraj-01** [comment] 2021-02-09 17:56
> We cannot restrict them in one line, what if the name is long enough to not fit in one line.
> Name reference - [#2556 (comment)](https://github.com/oppia/oppia-android/pull/2556#issuecomment-768023638)
> 
> Try using similar example in your pr to see if all the names are fitting and looking correctly or not.

we can ellipsize it if it exceeds one line. I'm talking about the Home screen only. Rest everywhere it can display full names. 

What do you think?

**Comment by rt4914** [comment] 2021-02-10 07:49
> > We cannot restrict them in one line, what if the name is long enough to not fit in one line.
> > Name reference - [#2556 (comment)](https://github.com/oppia/oppia-android/pull/2556#issuecomment-768023638)
> > Try using similar example in your pr to see if all the names are fitting and looking correctly or not.
> 
> we can ellipsize it if it exceeds one line. I'm talking about the Home screen only. Rest everywhere it can display full names.
> 
> What do you think?

@yashraj-iitr This was verified by our designer and we came to conclusion that the username should be shown fully except at `ProfileChooser` screen.

**Comment by rt4914** [comment] 2021-02-10 07:51
> > As per mocks it should be in centre. Thanks @MaskedCarrot . Assigning this to @yashraj-iitr
> > https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/7fb5929e-4652-4412-bf8c-64d94f4159f9/
> 
> @rt4914 is the username is centred aligned in other layouts as well i.e, `layout-land`, `layout-sw600dp-port` and `layout-sw600dp-land`?

@yashraj-iitr We need username to be in centre only for `mobile-portrait` screen i.e. `layout` only.

**Comment by yashraj-01** [comment] 2021-02-10 08:09
> > > We cannot restrict them in one line, what if the name is long enough to not fit in one line.
> > > Name reference - [#2556 (comment)](https://github.com/oppia/oppia-android/pull/2556#issuecomment-768023638)
> > > Try using similar example in your pr to see if all the names are fitting and looking correctly or not.
> > 
> > 
> > we can ellipsize it if it exceeds one line. I'm talking about the Home screen only. Rest everywhere it can display full names.
> > What do you think?
> 
> @yashraj-iitr This was verified by our designer and we came to conclusion that the username should be shown fully except at `ProfileChooser` screen.

okay. then that's not an issue. thanks.

**Closed as completed** 2021-02-10 21:11 UTC
Labels: Z-ibt
