### ISSUE TITLE
[Portuguese] Some words appearing in English for Portuguese language

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3824] opened 2021-09-21 00:01 UTC
**Describe the bug**
Some words are displayed in English language despite of selecting the device language as Portuguese.

**To Reproduce**
1. Go to Oppia app and user profile
2. In user profile menu, select options 
3. See error: Reading display size ("Tamanho do Texto de Leitura") appears in English (Eg: Medium) instead of Portuguese (Eg: Médio)
4. Go back to the topics tab
5. See error: The names of the lessons and chapters are in English (Same problem as the web version and Arabic language issue (Issue 3820))

**Expected behavior**
All words should be displayed in Portuguese language.

**Demonstration**
1. Reading display size:
![image](https://user-images.githubusercontent.com/27875087/134091355-8853521b-e740-4e98-9f97-ea1b06fef729.png)

2. The names of the lessons and chapters are in English
![image](https://user-images.githubusercontent.com/27875087/134092229-923347f0-a310-496d-8a25-775bf3630008.png)

3. Concept and Revision cards are in English
![image](https://user-images.githubusercontent.com/27875087/134092382-548c180a-2569-4806-9099-da8f2bb02a78.png)

**Environment**
- Device/emulator being used: TBD
- Android or SDK version (e.g. Android 5 or SDK 21): TBD
- App version: TBD

**Additional context**

**Comment by BenHenning** [comment] 2021-09-27 08:31
I believe this isn't a blocker for MR3 (& am thus removing it from our blocker list). If I got that wrong, please re-add it @srushtirk.

Also, these are all known issues (particularly around the lack of translations for story/chapter/topic titles, and revision/concept cards). FWIW, the app does support translations for revision & concept cards, but the lesson structures don't yet support translations for titles & descriptions.

**Comment by BenHenning** [comment] 2022-06-10 01:30
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by Akshatkamboj14** [comment] 2023-08-21 16:22
Tried to reproduce the issue, but as shown in the demonstration, I only find 2,3 part (i.e. The names of the lessons and chapters are in English, Concept and Revision cards are in English) as issues. I didn't find the first part (i.e. Reading display size:)as issue in my findings.
![Screenshot_1692632461](https://github.com/oppia/oppia-android/assets/92685493/66b68625-e67a-474c-80c0-d203bc9f80cd)
I have tried on api 28 and api 25.

**Comment by BenHenning** [comment] 2023-08-22 17:44
@Akshatkamboj14 I suspect that the language size strings have been either finished being translated or correctly hooked up to translations since this issue was opened.

**Comment by adhiamboperes** [comment] 2023-09-01 16:04
> @Akshatkamboj14 I suspect that the language size strings have been either finished being translated or correctly hooked up to translations since this issue was opened.


Yes, just confirmed that (on beta), the lessons have been translated as well, only the Revision cards are still in english. Isn't this now a content team issue, @BenHenning?

**Comment by seanlip** [comment] 2023-09-02 01:31
The revision cards (and concept cards) not yet being translated is a known gap, and will need to be addressed once we have translations for those on Web as well. However, nothing can be done about this yet on the Android side since Web doesn't have those translations available. Once that infrastructure is set up, we can create a new issue for importing those translations specifically.

For the other issues here, I confirm too that they've been all fixed, so I think we can close this issue. Thank you for investigating, @Akshatkamboj14 and @adhiamboperes!

**Closed as completed by seanlip** 2023-09-02 01:31 UTC
Labels: Impact: Medium, Z-ibt, bug, Work: Medium
