### ISSUE TITLE
Inconsistent in-progress and completed topics display across the app

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3823] opened 2021-09-20 23:42 UTC
**Describe the bug**
The number of topics in-progress and completed is not being displayed consistently across different screens in the app.

**To Reproduce**
*Have at least one lesson in-progress and at least one lesson completed for reproducing this issue in the app

1. Select device language as Portuguese
2. Go to Oppia app
3. Click on your user profile 
4. The description below the profile will show some topics and lessons in progress and some completed
5. Click on the user profile
6. See the error (different number on in-progress and completed topics and lessons)

**Expected behavior**
Consistent number of  in-progress and completed topics and lessons should be displayed across the app. 

**Demonstration**
On the menu screen 1 story completed and 1 topic in-progress (for Place Values and addition and subtraction) is displayed, but when clicked on user profile, the screen shows 0 topics in-progress and 0 stories completed. 
![image](https://user-images.githubusercontent.com/27875087/134090280-0a33986b-b989-40fc-b3f3-f0e55023a248.png)

**Environment**
- Device/emulator being used: TBD
- Android or SDK version (e.g. Android 5 or SDK 21): TBD
- App version: TBD

**Additional context**

**Comment by BenHenning** [comment] 2022-06-10 01:30
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by MohitGupta121** [comment] 2022-10-03 03:42
|Menu|Profile|
|:----------------------------------------:|:-----------------------------------------:|
| ![](https://user-images.githubusercontent.com/76530270/193497097-8c3b3a60-11c7-4bc0-97ad-d3845168f753.png) | ![](https://user-images.githubusercontent.com/76530270/193497101-f4b0e43d-630f-4c7b-8d68-7ca36d9484a0.png) |




@BenHenning I am unable to reproduce this issue in my emulator.

Environment

- Emulator used: Pixel 4
- Android & SDK version: Android 10 & SDK 29
- App version: 1.0

**Comment by BenHenning** [comment] 2022-10-04 08:29
Hmm, not sure when this would've been fixed actually but thanks for checking @MohitGupta121! I think we can close this as not reproducible at this point.

**Closed as not planned by BenHenning** 2022-10-04 08:29 UTC
Labels: Impact: Low, Z-ibt

**Comment by MohitGupta121** [comment] 2022-10-04 08:31
Okay thanks you @BenHenning for acknowledge me.
