### ISSUE TITLE
[BUG]: Multiple substitutions specified in non-positional format of string resource

### ISSUE THREAD

**Issue by MohitGupta121** [oppia/oppia-android#5484] opened 2024-08-13 05:43 UTC
### Describe the bug

```
> Task :app:mergeDebugResources
/opensource/oppia-android/app/src/main/res/values-ar/strings.xml:95:2: Multiple substitutions specified in non-positional format of string resource string/chapter_completed. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-ar/strings.xml:93:2: Multiple substitutions specified in non-positional format of string resource string/chapter_in_progress. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-ar/strings.xml:96:2: Multiple substitutions specified in non-positional format of string resource string/chapter_name. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-ar/strings.xml:97:2: Multiple substitutions specified in non-positional format of string resource string/chapter_prerequisite_title_label. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-ar/strings.xml:110:2: Multiple substitutions specified in non-positional format of string resource string/math_expression_error_number_after_var_term. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-ar/strings.xml:447:2: Multiple substitutions specified in non-positional format of string resource string/onboarding_slide_dots_content_description. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-ar/strings.xml:329:2: Multiple substitutions specified in non-positional format of string resource string/profile_last_visited. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-ar/strings.xml:152:2: Multiple substitutions specified in non-positional format of string resource string/question_training_session_progress. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:80:2: Multiple substitutions specified in non-positional format of string resource string/chapter_completed. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:78:2: Multiple substitutions specified in non-positional format of string resource string/chapter_in_progress. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:81:2: Multiple substitutions specified in non-positional format of string resource string/chapter_name. Did you mean to add the formatted="false" attribute?

/Users/mohitgupta/.gradle/caches/transforms-3/a3ac098c2f10fa536abc6ff8a77d1852/transformed/material-1.6.0-alpha01/res/values-sw/values-sw.xml:7:4: Multiple substitutions specified in non-positional format of string resource string/chapter_prerequisite_title_label. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:98:2: Multiple substitutions specified in non-positional format of string resource string/math_expression_error_consecutive_binary_operators. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:101:2: Multiple substitutions specified in non-positional format of string resource string/math_expression_error_missing_lhs_for_addition_operator. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:102:2: Multiple substitutions specified in non-positional format of string resource string/math_expression_error_missing_lhs_for_division_operator. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:103:2: Multiple substitutions specified in non-positional format of string resource string/math_expression_error_missing_lhs_for_multiplication_operator. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:110:2: Multiple substitutions specified in non-positional format of string resource string/math_expression_error_multiple_redundant_parentheses. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:94:2: Multiple substitutions specified in non-positional format of string resource string/math_expression_error_number_after_var_term. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:92:2: Multiple substitutions specified in non-positional format of string resource string/math_expression_error_redundant_parentheses_individual_term. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:378:2: Multiple substitutions specified in non-positional format of string resource string/onboarding_slide_dots_content_description. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:273:2: Multiple substitutions specified in non-positional format of string resource string/profile_last_visited. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-sw/strings.xml:136:2: Multiple substitutions specified in non-positional format of string resource string/question_training_session_progress. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pt-rBR/strings.xml:98:2: Multiple substitutions specified in non-positional format of string resource string/chapter_completed. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pt-rBR/strings.xml:100:2: Multiple substitutions specified in non-positional format of string resource string/chapter_in_progress. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pt-rBR/strings.xml:96:2: Multiple substitutions specified in non-positional format of string resource string/chapter_locked_prerequisite_title_label. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pt-rBR/strings.xml:99:2: Multiple substitutions specified in non-positional format of string resource string/chapter_name. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pt-rBR/strings.xml:101:2: Multiple substitutions specified in non-positional format of string resource string/chapter_prerequisite_title_label. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values/strings.xml:96:2: Multiple substitutions specified in non-positional format of string resource string/chapter_completed. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values/strings.xml:98:2: Multiple substitutions specified in non-positional format of string resource string/chapter_in_progress. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values/strings.xml:94:2: Multiple substitutions specified in non-positional format of string resource string/chapter_locked_prerequisite_title_label. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values/strings.xml:97:2: Multiple substitutions specified in non-positional format of string resource string/chapter_name. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pt-rBR/strings.xml:427:2: Multiple substitutions specified in non-positional format of string resource string/onboarding_slide_dots_content_description. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pt-rBR/strings.xml:309:2: Multiple substitutions specified in non-positional format of string resource string/profile_last_visited. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pt-rBR/strings.xml:156:2: Multiple substitutions specified in non-positional format of string resource string/question_training_session_progress. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values/strings.xml:99:2: Multiple substitutions specified in non-positional format of string resource string/chapter_prerequisite_title_label. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values/strings.xml:683:2: Multiple substitutions specified in non-positional format of string resource string/onboarding_slide_dots_content_description. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values/strings.xml:332:2: Multiple substitutions specified in non-positional format of string resource string/profile_last_visited. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values/strings.xml:157:2: Multiple substitutions specified in non-positional format of string resource string/question_training_session_progress. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values/strings.xml:425:2: Multiple substitutions specified in non-positional format of string resource string/welcome_profile_name. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pcm-rNG/strings.xml:98:2: Multiple substitutions specified in non-positional format of string resource string/chapter_completed. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pcm-rNG/strings.xml:100:2: Multiple substitutions specified in non-positional format of string resource string/chapter_in_progress. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pcm-rNG/strings.xml:96:2: Multiple substitutions specified in non-positional format of string resource string/chapter_locked_prerequisite_title_label. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pcm-rNG/strings.xml:99:2: Multiple substitutions specified in non-positional format of string resource string/chapter_name. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pcm-rNG/strings.xml:101:2: Multiple substitutions specified in non-positional format of string resource string/chapter_prerequisite_title_label. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pcm-rNG/strings.xml:443:2: Multiple substitutions specified in non-positional format of string resource string/onboarding_slide_dots_content_description. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pcm-rNG/strings.xml:311:2: Multiple substitutions specified in non-positional format of string resource string/profile_last_visited. Did you mean to add the formatted="false" attribute?

/opensource/oppia-android/app/src/main/res/values-pcm-rNG/strings.xml:156:2: Multiple substitutions specified in non-positional format of string resource string/question_training_session_progress. Did you mean to add the formatted="false" attribute?

```

### Steps To Reproduce

Build app and see build logs

### Expected Behavior

There should be no multiple strings

**Comment by Raghav1783** [comment] 2024-08-14 12:27
Hi, I’m interested in working on this issue. Could you please assign it to me?

**Comment by adhiamboperes** [comment] 2024-08-14 14:14
@Raghav1783, Could you please make sure that you are able to reproduce this issue, and then give a brief description of what's causing it an the suggested fix?

**Comment by Raghav1783** [comment] 2024-08-15 12:32
@adhiamboperes yes i am able to reproduce this error . String resource has multiple %s . To avoid this, we must identify each like this: %1$s

**Comment by Raghav1783** [comment] 2024-08-16 13:41
@adhiamboperes should i create a pr?

**Comment by adhiamboperes** [comment] 2024-08-19 08:37
@Raghav1783, to reproduce means to perform the steps that caused the error to occur. For this specific issue, it would be great to see proof of this issue occuring on either your computer, or our GitHub CI. This way we can evaluate the before and after build isues and verify that your fix worked. If this is possible on your end, please feel free to create a PR.

**Comment by jainv4156** [comment] 2024-10-22 06:07
Hi @adhiamboperes,

I would like to work on this issue. This error appears every time I clean and rebuild the project. This issue seems to be related to the custom function getStringInLocale used for retrieving strings 
 
![image](https://github.com/user-attachments/assets/71e82098-fbad-41f9-b7e1-227902205bd3)

**Comment by jainv4156** [comment] 2024-10-22 06:11
I am currently researching this further, but I am having trouble locating the implementation of the sealed class OppiaLocale. Any guidance on where I might find it would be greatly appreciated.

**Comment by adhiamboperes** [comment] 2024-10-22 07:14
@jainv4156 please double check the OppiaLocale class. 
1. Read the kdoc at the top of the class
2. Each abstract class in the file has a corresponding 'Impl' in the same package as OppiaLocale.kt

**Comment by jainv4156** [comment] 2024-10-22 17:41
@adhiamboperes,

I’ve identified the main issue and found the solution. It is  what @Raghav1783 suggested. Should I go ahead and create a PR now?

**Comment by adhiamboperes** [comment] 2024-10-24 05:40
@jainv4156, please go ahead and create the PR

**Closed as completed** 2024-11-04 11:45 UTC
Labels: good first issue, Impact: Low, bug, Work: Low
