### ISSUE TITLE
"Profile Deletion" button is misaligned in landscape on a phone

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4852] opened 2023-01-21 01:45 UTC
**Describe the bug**
The "Profile Deletion" button in the "edit profile" screen on mobile landscape is overlapping with the other buttons available in the screen.

**To Reproduce**
1. Make sure there is more than one profile on the device.
1. Open Administrator Controls
2. Under "Profile Management" click "Edit profiles"
3. Select a **non-admin** profile
4. Rotate to landscape
5. Observe that the "Profile Deletion" button is overlapping the other buttons

**Expected behavior**

**Demonstration**
![image](https://user-images.githubusercontent.com/12983742/213835438-03b97f77-3963-4072-9f30-400876741d8d.png)

**Environment**
- Device/emulator being used: Nexus 5X
- Android or SDK version (e.g. Android 5 or SDK 21): SDK 27
- App version (you can get this through system app settings or via the admin controls menu in-app): an oppia_android_alpha_kenya build on tip-of-tree (71e769bec2b853d51996432e31f8bec232f16928), though I suspect this will also repro with oppia_dev.

**Additional context**
None.

**Comment by lonewolf2208** [comment] 2023-01-21 13:16
Hey @BenHenning , I can work on this can you assign this to me

**Comment by seanlip** [comment] 2023-01-22 16:03
@lonewolf2208 Could you please provide an explanation of what the root cause of this issue is, and what your PR will do to fix it (with names of files you're changing, what you plan to change in each file, etc.)? We'll need to see this (and it needs to be correct) before we can assign this issue to you. Thanks!

**Comment by lonewolf2208** [comment] 2023-01-22 17:22
Hello @seanlip , I think the problem is with the constraint of profile deletion button . (profile_edit_fragment.xml)
![image](https://user-images.githubusercontent.com/72886809/213930085-f411d6f0-415a-49fd-957a-917c9c26365a.png)

**Comment by seanlip** [comment] 2023-01-22 17:26
OK, thanks, I've assigned you. Feel free to make a PR (and include proof that it does the right thing)!

**Comment by Abhinav-1111** [comment] 2023-01-29 09:11
I want to work on this issue . Please assign me this issue.

**Comment by nawaz-anwar** [comment] 2023-02-05 12:01
I can solve these issues. It occurs in an Android environment when the device is rotated to landscape mode while the non-admin profile is selected.

**Comment by seanlip** [comment] 2023-02-05 16:20
Folks -- just wanted to suggest, if you're new to the repo, that you pick issues that are not yet assigned and that don't have a PR already open for them. Thanks!

**Comment by aayushimathur6** [comment] 2023-04-29 11:20
![image](https://user-images.githubusercontent.com/92685651/235299679-999f1da1-114f-47c2-9cc7-42ab375d1cf4.png)@rt4914 @BenHenning @adhiamboperes As per the issue the layout when reproduced on Nexus 5X shows only rename, reset pin, and profile deletion option but my question is when you see the code now, you will see that there is a lot of more code added for the "Mark Chapter completed", "Enable Quick Language Switching" and "Allow download access" buttons,
![image](https://user-images.githubusercontent.com/92685651/235298994-0b29d6fd-6d17-4ae8-8d3b-10b07b45523a.png) 
and for making "profile deletion button" aligned I was adding constraints to the bottom of "profile edit allow"  
![image](https://user-images.githubusercontent.com/92685651/235299477-5e2ebf18-334d-4df3-947d-532c9e2fc951.png)
but by doing so it's showing a gap after the "reset pin" button and not showing the rest of the buttons 
![image](https://user-images.githubusercontent.com/92685651/235299871-46077d97-125a-49d0-9434-f9dcab05e53b.png)

 so I am getting confused that where should I make it a constraint to "reset pin" button so that the gap shouldn't be there?

**Comment by aayushimathur6** [comment] 2023-04-29 11:32
@adhiamboperes @BenHenning Also I checked the PR which was closed earlier as suggested by @adhiamboperes, as per that PR the leftover changes according to Rajat are 
![image](https://user-images.githubusercontent.com/92685651/235300260-238ff499-5009-465d-987d-da7f01472f7c.png)
but I think these changes have already taken place and also the code has added a lot for the rest of the buttons I mentioned in my previous comment.

The changes:
![image](https://user-images.githubusercontent.com/92685651/235300451-7c9fb5af-076f-4bfc-8d6f-288a740e94ad.png)

**Comment by adhiamboperes** [comment] 2023-05-02 13:08
Hi @aayushimathur6, the visibility of the buttons are conditional based on the databinding value set in the the  `visibility` attribute, which is why some don't show by default.

Please constrain it to the bottom of parent.

**Comment by aayushimathur6** [comment] 2023-05-02 17:26
Thanks @adhiamboperes for clearing, I will implement it.

**Closed as completed** 2023-07-07 14:06 UTC
Labels: good first issue, Impact: Medium, bug, Work: Low
