### ISSUE TITLE
Fix all broken tests on develop

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#295] opened 2019-11-04 02:46 UTC
Most of our tests are failing. We need to fix these.

## Checklist
List of files which have failing test cases. You can start fixing these files and once you fix these files make sure you comment here mentioning what all files you have fixed.

**`app` module**
- [ ] `HtmlParserTest`
- [x] `AudioFragmentTest` (This can be because of Roboelectric too. @jamesxu0 Please check this.)
- [x] `CellularDataDialogFragmentTest`
- [ ] `ExplorationActivityTest`
- [ ] `TopicOverviewFragmentTest` (Failing because the TopicActivityPresenter is loading `TopicFragment` as default)
- [ ] `TopicPlayFragmentTest` (Failing because the TopicActivityPresenter is loading `TopicFragment` as default)
- [ ] `TopicReviewFragmentTest` (Failing because the TopicActivityPresenter is loading `TopicFragment` as default)
- [ ] `TopicTrainFragmentTest` (Failing because the TopicActivityPresenter is loading `TopicFragment` as default)

**`data` module**
- [x] `NetworkInterceptorTest`

** All modules**
- [ ] Final check of all test cases

**Comment by jamesxu0** [comment] 2019-11-05 00:04
PR #284 and #290 fixed AudioFragmentTest. PR #296 fixes CellularDataDialogFragmentTest.

**Comment by rt4914** [comment] 2019-11-05 04:50
@jamesxu0 I think there will be some more broken test cases a we move along, basically wherever we were using some dummy button needs to be removed and because of which these errors will occur. So you can expect that you are re-assigned to a broken-test which you have already solved.

**Comment by BenHenning** [comment] 2019-11-05 06:13
Thanks for breaking this down @rt4914 -- this is really helpful!

**Comment by jamesxu0** [comment] 2019-11-06 00:42
PR #296 makes CellularDataDialogFragmentTest pass locally for Espresso, but not on CircleCI for unknown reasons. I tried running the test on Robolectric, which failed due to these exceptions:
Caused by: android.view.InflateException: Binary XML file line #17: Layout state should be one of 100 but it is 10
Caused by: java.lang.IllegalStateException: Layout state should be one of 100 but it is 10
It seems it has somethign to do with databinding in onCreateViewHolder in StateAdapter.

**Comment by anandwana001** [comment] 2021-02-03 03:23
We are good to close this issue, as we have a master tracking issue for fixing test 
https://github.com/oppia/oppia-android/issues/2417

**Closed as completed** 2021-02-10 12:33 UTC
Labels: Priority: Essential, Z-ibt
