### ISSUE TITLE
Issues with Editing "Reading Text Size"

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2137] opened 2020-11-20 21:00 UTC
- Font size selections from "Reading Text Size" do not accurately reflect the changes the would be made to the text size. 
- If font size is changed in the Lesson Player through Options, the change is not reflected until the learner leaves the Lesson and comes back. Please change it so that when the learner does select a different text size, it is immediately reflected in the Lesson Player. [[Video 1](https://drive.google.com/file/d/1fkjh8hoBk0eO4hFYRXPogcFl4e4tGhHD/view?usp=sharing)] [[Video 2](https://drive.google.com/file/d/1ff0f7QHCu2JPjz6W9hdDWewbcJdRc_EC/view?usp=sharing)]

**Comment by chrk2205** [comment] 2020-11-21 17:44
duplicate of #1540

**Comment by rt4914** [comment] 2020-11-23 15:05
> duplicate of #1540

@chrk2205 Thanks for pointing this. I am closing this issue as we are already tracking this. @mschanteltc Thanks.

**Closed as completed by rt4914** 2020-11-23 15:05 UTC
Labels: Z-ibt
