### ISSUE TITLE
Marquee restarts after submitAnswer

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1770] opened 2020-09-02 10:29 UTC
**Describe the bug**

**To Reproduce**
1. Go to `The Meaning of Equal Parts` exploration
2. Go to `Second state`. Note that the title is not moving.
3. Submit current answer.
4. Marquee effect starts.

**Expected behavior**
Marquess effect should start only on click on the toolbar and not automatically.

**Comment by BenHenning** [comment] 2020-09-02 12:06
Doesn't seem bad enough to block alpha--moving to beta.

**Comment by prayutsu** [comment] 2020-09-06 06:46
@anandwana001 @rt4914 I found out that, marquee starts only when ```isSelected``` is set to true. So, I tried to set this property false, whenever we click the submit button, but then I discovered that it again restarts when we click on the editText to write the answer or whenever we close the keyboard. 
So, should I try setting the property to false when the keyboard appears and disapperars.
I also tried to find out why it is getting selected after submitting answer but didn't find anything suspicious.
So, is this the right approach to solve it?

**Comment by rt4914** [comment] 2020-09-08 05:20
> @anandwana001 @rt4914 I found out that, marquee starts only when `isSelected` is set to true. So, I tried to set this property false, whenever we click the submit button, but then I discovered that it again restarts when we click on the editText to write the answer or whenever we close the keyboard.
> So, should I try setting the property to false when the keyboard appears and disapperars.
> I also tried to find out why it is getting selected after submitting answer but didn't find anything suspicious.
> So, is this the right approach to solve it?

@prayutsu Instead of finding the solution, the approach in case of bugs should be like this:
1. First try to find the exact reasons of the bugs.
2. Once you have identified the reason, write a test case which actually fails because of the bug. (This will be needed in future).
3. Now work towards solution.
4. Now, the test cases which were written in (2.) should pass and that way we can be sure that the bug has been fixed.

So at this stage you should focus on step 1.

**Comment by prayutsu** [comment] 2020-09-08 05:26
@rt4914 Thanks for your tips, I'll surely tackle it the same way.

**Comment by prayutsu** [comment] 2020-09-19 19:58
Couldn't resolve the correct reason for the bug, so unassigning myself.

**Comment by Luffy18346** [comment] 2020-12-21 11:28
@rt4914 I have tried to reproduce the issue and apart from what you have mentioned above, I found 2 more ways to reproduce it.

**1st way:** 
1. Go to The Meaning of Equal Parts exploration
2. Go to Second state. Note that the title is not moving.
3. click and edit text and type something but do not close the keyboard.
**4.** Now "back press" , keyboard will close and you will see the marquee will start moving.

**2nd way**
1. Go to The Meaning of Equal Parts exploration
2. Go to Second state. Note that the title is not moving.
3. Click the title and note that it is moving.
4. After marquee stops, click again, note that title is not moving (This can also be considered as bug if I am thinking correctly that **each time user clicks on title, the marquee should start** but I am not sure that this is the objective we are trying to achieve here.)  
5. Now click on "close" button (make sure edittext is not selected), you will see that the title starts moving. 
5. After marquee stops, click on edittext  and you will see that title starts moving.

**Comment by Luffy18346** [comment] 2020-12-21 11:43
@rt4914 
My approach was
1. Apply `ellipsize = end` first. Then when user clicks on title then change it to `marquee` and set `isSelected = true`
2. Once marquee completes, then set` isSelected = false` and change `ellipsize = end` back.

1st point is achievable but it's 2nd point where I was interrupted because there is no easier way to know the status of marquee.
For that, I got reference from these 2 links of StackOverflow, but I was not able to achieve that. [https://stackoverflow.com/questions/12392540/fire-event-when-marquee-completes](url)
[https://stackoverflow.com/questions/35848015/android-marquee-start-position-and-change-speed](url)

Firstly I tried to access the hidden field `mMarquee ` as given in the second link but the field was null. 

If somehow, somebody manages to get the field then He has to access another field called `mStatus ` which will represent the status of marquee. If successful, then further steps are given in first link.

**Comment by rt4914** [comment] 2020-12-22 06:53
Thanks @Luffy18346 for adding comments.

**Comment by etigoel** [comment] 2021-01-20 16:23
I can look into this. Assigning Myself for the same.

**Comment by rt4914** [comment] 2021-01-20 16:44
> I can look into this. Assigning Myself for the same.

Thanks. Have a look at all the comments too as we already had difficulties in this issue. @etigoel

**Comment by etigoel** [comment] 2021-01-20 16:48
Sure.

**Closed as completed** 2021-01-28 15:52 UTC
Labels: Priority: Essential, Z-ibt
