### ISSUE TITLE
Submit Button becomes unresponsive

### ISSUE THREAD

**Issue by bkaur-bkj** [oppia/oppia-android#4013] opened 2021-11-23 20:10 UTC
**Describe the bug**
When trying to attempt question, if I enter wrong answer and click on submit button, in some cases in the next step the button becomes unresponsive even after more then 3 tries. have attached the  screen recording for details

1. Go to any chapter - you can choose First Test topic(as it has such types of questions)
2. Click on chapter 1 and start solving Prototype Exploration questions
3. Enter wrong answer in the blank intentionally and click on submit
4. Try entering the correct ans and you can see the error.
**Expected behavior**
when the correct answer is added , submit button should not act unresponsive and normally should be Green in color not grey.

 **Demonstration**

https://user-images.githubusercontent.com/64087572/143096174-21388ea8-e448-4f6f-82e3-162b02628106.mp4

**Environment**
- Device/emulator being used: Moto G Power 10
- Android or SDK version (e.g. Android 5 or SDK 21): Android 11
- App version (you can get this through system app settings or via the admin controls menu in-app): <app version>

**Comment by ihrishix** [comment] 2021-12-05 17:33
Can recreate this issue. Please try this again with latest app build and share steps to recreate.

**Comment by BenHenning** [comment] 2021-12-07 20:06
Ah, this is a really nice find @bkaur-bkj. It seems that the submit button state management for real-time vs. submit-time errors is getting borked up. Investigation is needed.

**Comment by anandwana001** [comment] 2022-03-11 01:51
Duplicate - https://github.com/oppia/oppia-android/issues/3861

**Comment by BenHenning** [comment] 2022-03-24 03:40
This is a duplicate of #3861 as @anandwana001 mentioned, so closing this.

**Closed as completed by BenHenning** 2022-03-24 03:40 UTC
Labels: Z-ibt
