### ISSUE TITLE
For talkback users it is difficult to understand if the question has a table, as it doesnt read the table content

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4360] opened 2022-05-16 10:33 UTC
**Describe the bug**
For talkback users it is difficult to understand if the question has a table as it doesnt read the table content

**To Reproduce**
1. Go to 'Place Values'
2. Click on 'Comparing Numbers'
3. Click on Continue to go to the question page
This is the table for a high score for Whac-a-mole. What number does this table represent

**Expected behavior**
Talkback should read the table content so that the users will be able to understand and enter the number in the edit box

Actual Result:
Taklback is not reading the table content so users can never know what to enter in the edit box
https://user-images.githubusercontent.com/101634267/168574542-f5b58319-3ed2-4191-9fe4-31b93588536f.mp4

Environment:
Device name: One plus Nord2 5G
Android version : Android 11
App version: 0.7-alpha-6c08d882d3

**Comment by BenHenning** [comment] 2022-05-18 08:31
This is a nice find. The issue is definitely how to represent complex graphic visuals with alternate text. We don't currently integrate alternate text for embedded images, but this problem may still exist even after that part is fixed if the alternate text isn't sufficiently clear.

**Comment by BenHenning** [comment] 2022-06-10 17:18
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by rt4914** [comment] 2022-09-01 16:57
This looks like a duplicate of https://github.com/oppia/oppia-android/issues/3432

@BenHenning Can I close this issue?

**Comment by BenHenning** [comment] 2022-09-02 00:01
SGTM. Closing as a duplicate.

**Closed as not planned by BenHenning** 2022-09-02 00:01 UTC
Labels: Impact: Medium, Z-ibt
