### ISSUE TITLE
Uneven spacing between the options

### ISSUE THREAD

**Issue by prayutsu** [oppia/oppia-android#3123] opened 2021-04-27 06:52 UTC
In some cases, the spacing between options is not consistent - 
<img src="https://user-images.githubusercontent.com/54636525/116198152-3f3cb780-a753-11eb-8469-eb1cea2f617b.jpg" width=230 height=450 /> <img src="https://user-images.githubusercontent.com/54636525/116198161-419f1180-a753-11eb-90fa-b226dce017e3.jpg" width=230 height=450 /> <img src="https://user-images.githubusercontent.com/54636525/116198166-4368d500-a753-11eb-834b-999b9e6ac293.jpg" width=230 height=450 />

**Comment by anandwana001** [comment] 2021-04-27 07:05
@prayutsu Let's use this format `<img src="IMAGE_URL_HERE" width=230 height=450 />`

**Comment by BenHenning** [comment] 2021-04-28 02:27
Note that this was found while testing alpha MR2 but is determined to not be a blocker.

**Comment by adhiamboperes** [comment] 2022-11-01 12:20
I am not able to reproduce this issue on a physical device or an emulator.
Tested with a 6.67” physical device, 5.6” Pixel 3a emulator, 5.0” Pixel 2 emulator @BenHenning

**Comment by BenHenning** [comment] 2022-11-01 18:01
@adhiamboperes do you have a screenshot to show that this isn't an issue any longer?

**Comment by adhiamboperes** [comment] 2022-11-01 18:25
> @adhiamboperes do you have a screenshot to show that this isn't an issue any longer?
 
@BenHenning , here are some screenshots:

|Physical Device, 6.67", Android 11|Emulator, 5.6", Android 10|Emulator, 5.0", Android 10|
|---|---|---|
|![Screenshot_2022-11-01-11-45-23-654_org oppia android](https://user-images.githubusercontent.com/59600948/199308992-fb9b3d05-fbae-4077-8951-f4babebd9b7e.jpg)|![Screenshot_1667299286](https://user-images.githubusercontent.com/59600948/199308462-670ad3a9-beb3-4c41-9564-536949963ba5.png)|![Screenshot_1667304666](https://user-images.githubusercontent.com/59600948/199308503-0ef44de4-c933-4a68-8a4d-2f21e45c8ac2.png)|

**Comment by BenHenning** [comment] 2022-11-02 03:26
Thanks @adhiamboperes! It's possible the content was fixed in lessons, but I suspect this was fixed in #3852 when we cleaned up spacing around bullet list HTML. I think we can close this as not reproducible until we see it again.

**Closed as not planned by BenHenning** 2022-11-02 03:26 UTC
Labels: Impact: Low, Z-ibt
