### ISSUE TITLE
No picture shown in Practice Mode

### ISSUE THREAD

**Issue by yashraj-01** [oppia/oppia-android#3039] opened 2021-04-03 17:48 UTC
**Describe the bug**
According to the question statement, it seems that there should have been a picture here which is not shown.

**To Reproduce**
1. Go to the 'Fractions' topic
2. Click on 'Practice' tab
3. Select 'What is a Fraction?' skill and start practice

**Expected behavior**
There should have been a picture shown here corresponding to the question

**Screenshots**
<img width="250" height="500" src="https://user-images.githubusercontent.com/63469151/113486540-0e10f480-94d1-11eb-9a5d-4d75ce6cb641.png">
<img width="250" height="500" src="https://user-images.githubusercontent.com/63469151/113486640-8bd50000-94d1-11eb-99f8-0faf563067c0.png">

**Device**
- Device being used: 10.or E (Android 8.1)
- SDK version: 29

**Comment by yashraj-01** [comment] 2021-04-03 17:48
@rt4914 @anandwana001 can you please confirm if this is a duplicate issue or not?

**Comment by Victor-Titan** [comment] 2021-04-04 14:31
Hey @yashraj-iitr, I couldn't reproduce your bug after following your instructions.
![WhatsApp Image 2021-04-04 at 7 59 49 PM](https://user-images.githubusercontent.com/54766268/113512063-8f739000-9580-11eb-847a-7c1e9da64137.jpeg)
![WhatsApp Image 2021-04-04 at 8 00 38 PM](https://user-images.githubusercontent.com/54766268/113512067-939fad80-9580-11eb-94c4-fe32b850da3e.jpeg)

**Comment by yashraj-01** [comment] 2021-04-04 15:12
@Victor-Titan looks like this error is associated with the android version of the device as I can still reproduce this on my device even after uninstalling and reinstalling it, but this issue was not reproducible on Pixel 3 API 30 emulator.

**Comment by Victor-Titan** [comment] 2021-04-04 17:17
> @Victor-Titan looks like this error is associated with the android version of the device as I can still reproduce this on my device even after uninstalling and reinstalling it, but was unable to reproduce this on Pixel 3 API 30 emulator.

@yashraj-iitr The screenshots are on Android 10 in my Poco X3. I haven't tried Pixel 3 yet.

**Comment by yashraj-01** [comment] 2021-04-12 19:15
The issue seems genuine for lower versions of android as I was again able to reproduce it on my Micromax phone with android 5.1 running on it.
Here is the screenshot
<img width="250" height="500" src="https://user-images.githubusercontent.com/63469151/114448660-7490c380-9bf1-11eb-878f-d4c26771f9cd.png">

**Comment by yashraj-01** [comment] 2021-04-12 19:16
@rt4914 @anandwana001 PTAL.

**Comment by rt4914** [comment] 2021-04-12 19:18
@yashraj-iitr Can you try to fix this?

**Comment by yashraj-01** [comment] 2021-04-19 11:12
> @yashraj-iitr Can you try to fix this?

@rt4914 I was looking into this issue but I was unable to find out how the image is processed/shown here. Could you please provide any reference? Thanks.

**Comment by rt4914** [comment] 2021-04-21 23:30
@yashraj-iitr I don't think this is an error. If you check the screenshot, the emulator does not have access to internet and that's images are not appearing. Closing this right now, you can try to check this and if it still happens just reopen this issue with appropriate comment.

**Closed as completed by rt4914** 2021-04-21 23:30 UTC
Labels: Z-ibt
