### ISSUE TITLE
Truncated display of correct answer image in Fractions

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#4688] opened 2022-11-01 15:34 UTC
**Describe the bug**
In the denominators of three screen where a user is asked to select all answers that are correct, there are two correct answers.
Issue 1: Only one of the two selected ansswers is shown as the correct answer.
Issue 2: The image displayed is truncated on the right hand side.

**To Reproduce**
1. Go to 'home' on the development version
2. Click on 'The fractions topic'
3. Scroll through to '`the denominators of 3` lesson'
4. Select the two correct answers
5. The error will be as shown in the screenshots below

**Expected behavior** 
||
|---|
|![Screenshot_1668625757](https://user-images.githubusercontent.com/59600948/202398795-34c9a92c-4bb7-45e1-919a-19667d189d6a.png)|

**Demonstration**
 | Pixel 2 5.0"   | Pixel 3a 5.6"  | Redmi Note 9S 6.67" |
| -------------| -----| -----|
|![Screenshot_1667304722](https://user-images.githubusercontent.com/59600948/199260497-8234d94d-3b53-4b1c-8440-5b4fd7014696.png)|![Screenshot_1667299316](https://user-images.githubusercontent.com/59600948/199259594-ecb047aa-7224-4021-b339-93745fe98c0f.png)|![Screenshot_2022-11-01-18-11-54-256_org oppia android](https://user-images.githubusercontent.com/59600948/199267791-06c92274-44dd-4bff-9244-bfec9862f81c.jpg)| - |

**Environment**
- Device/emulator being used: Redmi Note 9s 6.67"- Physical, Pixel 2 5.0"-Virtual, Pixel 3a 5.56"-Virtual
- Android version: <10,11>
- App version: <1.0, development version>

**Comment by BenHenning** [comment] 2022-11-02 03:34
Ah nice find. I suspect this may be due to us not letting the image go below a certain size, and we're not providing adequate space for the bullet list to extend leftward. This will require some changes to the feedback view & how much space it's allowed to extend to.

While image cutting off is generally believed to be a high-impact problem, I suspect this one is less likely to be one due to it needing several things to occur simultaneously, and the cut-off doesn't seem to break anything critical (yet--this may change if we see evidence of it).

**Comment by adhiamboperes** [comment] 2022-11-16 19:38
I have retested this, at the current head of develop, this is nolonger happening.

|4"|6.2"|
| --- | --- |
|![Screenshot_1668627038](https://user-images.githubusercontent.com/59600948/202276572-ccb840b6-9500-4fd6-a7c3-65f0058e754a.png)|![Screenshot_1668625757](https://user-images.githubusercontent.com/59600948/202276597-57c2e706-998f-4f90-b090-453015857f9f.png)|

**Comment by BenHenning** [comment] 2022-11-17 01:28
Hmm that’s actually a bit suspicious. @adhiamboperes can you recheck that you can still repro the original issue with the build you tried two weeks ago? If you can, can you track down which commit caused the fix (eg by checking each commit on develop with a rebuild and manual check)? I want to be sure this isn’t an intermittent issue.

**Comment by adhiamboperes** [comment] 2022-11-17 09:38
> Hmm that’s actually a bit suspicious. @adhiamboperes can you recheck that you can still repro the original issue with the build you tried two weeks ago? If you can, can you track down which commit caused the fix (eg by checking each commit on develop with a rebuild and manual check)? I want to be sure this isn’t an intermittent issue.


@BenHenning, I was able to reproduce the issue with the build where I had discovered it(commit `ac68f842d3f9c1816f0e0c1ff3e5e9b9ea165774`). I also ran through succeeding commits manually and found the issue was fixed in #4669 by @vrajdesai78. I found [this conversation thread](https://github.com/oppia/oppia-android/pull/4669#discussion_r1012109119) on the PR that may explain why this is resolved.

**Comment by BenHenning** [comment] 2022-11-17 10:01
Ah, well found @adhiamboperes. I think you may be right. This could be a happy side effect of making the alignment computation more robust for images. I think based on that, I'm happy to close this & the other issue as no longer reproducible. This is great to see. :)

**Closed as not planned by BenHenning** 2022-11-17 10:01 UTC
Labels: Impact: Low, Z-ibt
