### ISSUE TITLE
Profile onboarding experience is especially confusing for single-person device users, rendering the app not especially self-service

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4627] opened 2022-09-28 02:10 UTC
**Is your feature request related to a problem? Please describe.**
Yes: two users that I asked to install the app both ran into confusion issues after the onboarding flow and at the profile screen:
- The first user reported that they weren't sure if the default 'Administrator' account was meant to be in the release, and if they should be using it.
- The second user proceeded to immediately add a new profile after being instructed to by the onboarding slides, and then was prompted with filling in a PIN for the admin account (which confused them).

Neither user understood that they were supposed to use the admin account initially, as well as what profiles were for (without me directly explaining it to them).

The app is not sufficiently self-service for users who don't need to understand profiles.

**Describe the solution you'd like**
Ideally, the onboarding flow would require the user to _create_ the initial administrator account, and only be prompted to create new users when they actually need to (i.e. in cases when the device will be used by more than one user).

**Describe alternatives you've considered**
I didn't consider alternatives, though others are likely to be viable. The core problem is the focus of this feature request and needs to be addressed.

**Additional context**
No additional context.

**Comment by seanlip** [comment] 2022-09-28 02:16
Current version of updated flows (PTAL): https://docs.google.com/presentation/d/1cdvX9HUXuqJsV53odRM0TZlPA1EHOW3tpjK_tGpR73U/edit

**Comment by tanzhirong** [comment] 2023-04-05 16:20
The onboarding feature should address these issues:
"_The first user reported that they weren't sure if the default 'Administrator' account was meant to be in the release, and if they should be using it._"
--> Option for sole learners to proceed directly to the homescreen rather than be confused by the Admin terminologies.
"_The second user proceeded to immediately add a new profile after being instructed to by the onboarding slides, and then was prompted with filling in a PIN for the admin account (which confused them)._"
--> For sole learners, they do not have to go through the associated with the Administrator (i.e. creating PIN, adding a new profile).

Have also created a separate ticket for the onboarding feature here:
https://github.com/oppia/oppia-android/issues/4938

**Comment by seanlip** [comment] 2023-04-09 03:52
Thanks! Closing this as a duplicate of #4938, then.

**Closed as not planned by seanlip** 2023-04-09 03:52 UTC
Labels: Impact: Medium, Z-ibt, enhancement
