### ISSUE TITLE
Option images are not rendered in exploration.

### ISSUE THREAD

**Issue by MaskedCarrot** [oppia/oppia-android#3514] opened 2021-07-22 09:03 UTC
**Describe the bug**
Options images are not rendered in an exploration.

**To Reproduce**
1. Go to 'Fractions' topic
2. Click on 'what is fractions' exploration
3. Advance to the 6th question/state
5. navigate to previous state
6. return to the 6th state
7. see images rendered properly.

**Expected behavior**
Option images should be rendered every time.

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

https://user-images.githubusercontent.com/53645584/126613717-5a8a820d-3251-4223-8b98-dbae703ff13e.mp4

**Device**
- Device/emulator being used: Real device OnePlus 7
- SDK version 30
- Device/emulator being used: Emulator Pixel 4
- SDK version 28

**Additional context**
Reverting PR #3433 fixes the issue.

**Comment by MaskedCarrot** [comment] 2021-07-22 09:04
@rt4914 PTAL

**Comment by rt4914** [comment] 2021-07-24 03:01
@MaskedCarrot This looks like a one-of bug. I am unable to reproduce this on my emulator but still this should not happen.

**Comment by rt4914** [comment] 2022-01-19 15:55
Closing this as it was solved with #3765

**Closed as completed by rt4914** 2022-01-19 15:55 UTC
Labels: Z-ibt
