### ISSUE TITLE
Profile Picture not saving 

### ISSUE THREAD

**Issue by Precious-goziemba** [oppia/oppia-android#4906] opened 2023-03-17 14:09 UTC
**Describe the bug**
I tried adding a profile picture to the admin account, after going through the steps, the change didn't save. 

**To Reproduce**
1. Go to '.Hamburger icon that brings the side bar.'
2. Click on 'Admin...', this takes you to the admin profile page 
3. Click on 'Edit icon' on the profile picture 
4. Select 'Choose from library'
5. Select 'Gallery'
6. Click on an image
7. You would be taken back to the profile page without the change being effected. 

**Expected behavior**
A new profile picture should be there when you are taken back or a status update showing (like loading or a loading icon)

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

**Environment**
- Device/emulator being used: <device version/emulator>
- Android or SDK version (e.g. Android 5 or SDK 21): <Android 11>
- App version (you can get this through system app settings or via the admin controls menu in-app): <app version 0.10-beta-5e64fae55e>

**Additional context**

**Comment by BenHenning** [comment] 2023-03-24 02:28
Thanks for filing this @Precious-goziemba! It looks like this is a duplicate of #4803, but it's good to have additional repro examples as it can help us narrow down the problem once we can investigate this.

**Closed as not planned by BenHenning** 2023-03-24 02:28 UTC
