### ISSUE TITLE
Lesson Name unexpectedly starts to marquee

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2136] opened 2020-11-20 20:59 UTC
When the input is selected and/or entered, the Lesson Name begins to marquee unexpectedly. [[Video 1](https://drive.google.com/file/d/1f4Y3wdh_di_ge7CRKT5FFrGjgjTBxEpu/view?usp=sharing)] [[Video 2](https://drive.google.com/file/d/1fJpNsc-FkERWwSSIAcISir7HtDK6ocqK/view?usp=sharing)]

**Comment by prayutsu** [comment] 2020-11-21 11:50
@mschanteltc I think this issue is a duplicate of [#1770](https://github.com/oppia/oppia-android/issues/1770)

**Comment by rt4914** [comment] 2020-11-23 15:08
> @mschanteltc I think this issue is a duplicate of [#1770](https://github.com/oppia/oppia-android/issues/1770)

Thanks @prayutsu and @mschanteltc 

Closing this because of duplicate issue #1770

**Closed as completed by rt4914** 2020-11-23 15:08 UTC
Labels: Z-ibt
