### ISSUE TITLE
Tablet Profile Chooser UI

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#3110] opened 2021-04-21 08:32 UTC
**Describe the bug**
The add item of the profile chooser screen is incorrectly aligned

**To Reproduce**
1. Open app on tablet
2. Add a profile
3. check the alignment 

**Expected behavior**
The items should be aligned correctly 

**Screenshots**
![Screenshot_1618993856](https://user-images.githubusercontent.com/25057618/115522948-327b1800-a2aa-11eb-8260-56e08eb0d7ba.png)

**Device**
- emulator being used
- SDK version - Pixel C API 28

**Comment by ArpitShukIa** [comment] 2021-04-27 08:34
@anandwana001 Is it a duplicate of #2116?

**Comment by rt4914** [comment] 2021-04-28 02:44
@ArpitShukIa Yes. Closing this issue.

**Closed as completed by rt4914** 2021-04-28 02:44 UTC
Labels: good first issue, Z-ibt
