### ISSUE TITLE
[FEATURE REQUEST]: Implement CI check to make sure that all colors are used from `component_colors.xml` file only [DARK MODE]

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#5114] opened 2023-08-01 11:18 UTC
### Is your feature request related to a problem? Please describe.

This is more of a developer workflow task instead of a feature request. 

We need to implement CI check for following task:
Other than thumbnails and icons in `mipmap` and `drawable` folder, all other places should reference color code from `component_colors.xml` file only. There should not be any direct usage of color from `color_palette.xml` or `color_defs.xml` or any other file.

### Describe the solution you'd like

Implement a CI check to meet the above described criteria.

**Comment by MohitGupta121** [comment] 2023-08-01 13:37
@rt4914 this is already done by me in these PR  https://github.com/oppia/oppia-android/pull/4882  https://github.com/oppia/oppia-android/pull/4960#issue-1689080280  but due to some confusion that need to change but that is now reverted in this PR https://github.com/oppia/oppia-android/pull/5081

Also I think this issue is duplicate of this https://github.com/oppia/oppia-android/issues/5075

**Comment by MohitGupta121** [comment] 2023-08-02 17:46
So @rt4914 @adhiamboperes we can close this issue as you already solving this in #5081?

**Comment by rt4914** [comment] 2023-08-05 05:50
@MohitGupta121 Can you update the `dark-mode` wiki by removing the point which links to this issue.
You can remove this entire last-second point on the page.

`Other than thumbnails and icons in mipmap and drawable folder, all other places should reference color code from component_colors.xml file only. There should not be any direct usage of color from color_palette.xml or color_defs.xml or any other file. (Note: there is an issue filed at [#5114](https://github.com/oppia/oppia-android/issues/5114) to do this automatically via a CI check, but until that issue is resolved, this needs to be checked manually.)`

Once removed, you can close this issue too. Thanks.

**Comment by MohitGupta121** [comment] 2023-08-05 05:52
Okay @rt4914 I'll do that.
But I have to remove the line from `Note:` ? Right?

**Closed as completed** 2023-08-05 15:20 UTC
Labels: Impact: Low, enhancement, Work: Low
