### ISSUE TITLE
Inputting text input answers auto-closes keyboard

### ISSUE THREAD

**Issue by srushtirk** [oppia/oppia-android#3832] opened 2021-09-23 00:51 UTC
**Describe the bug**
The keyboard auto-closes every time an answer is being inputted in the text input box in all topics/chapters.

**To Reproduce**
1. Go to Oppia app
2. Click on "What are place values" topic
3. Start the first chapter
4. Once you reach the question card "What about digit  1? What place value is the digit 1 in? Nikhil asked", click on the text input box. This will auto-close the keyboard in a second.

**Expected behavior**
The keyboard should be available to type in text input for the user until user clicks on enter key.

**Demonstration**
One of the text input boxes where the keyboard autocloses:
![image](https://user-images.githubusercontent.com/27875087/134440147-1c62e297-5942-4bea-b6d5-b251d20825f4.png)

**Environment**
- Device/emulator being used: Honor-6X
- Android or SDK version (e.g. Android 5 or SDK 21): Android 7
- App version: 0.6-alpha-908d57b2b1

**Additional context**
This issue was found in MR2 (https://github.com/oppia/oppia-android/issues/1769) and was fixed, i.e. the text input box now works fine in MR2 but seems like this issue regressed in MR3. Default keyboard selected was 'Microsoft Swiftkey Keyboard'.

The issue does not occur when default keyboard selected is 'gboard' (tested on both mr2 and mr3).

**Comment by BenHenning** [comment] 2021-09-23 00:58
To clarify: #1769 is probably a different issue, it's just similar. Something else has regressed this behavior since it was always previously working in portrait mode (whereas #1769 is landscape-specific).

Some quick searching suggests that users often hit these types of issues on Huawei phones. From the videos you shared in chat, my best guess is the extra tall keyboard might be triggering something (from the frame-by-frame it seems like the layout doesn't want to allow the submit button to go under the toolbar).

**Comment by BenHenning** [comment] 2021-09-23 01:00
I can't be sure this was caused by a change in state_fragment.xml, but the two relevant changes to that file between MR2 & MR3:
- https://github.com/oppia/oppia-android/commit/74e4aba4030a1d2da993f2e55dfc568286dfe07a#diff-31658d6687495c018f73ebcabf8c5212d7c05d2ad81cddd7357bd87cf2f8a0de
- https://github.com/oppia/oppia-android/commit/ef906e40619e7e5c670fce5bdb87d9ba558096e7#diff-31658d6687495c018f73ebcabf8c5212d7c05d2ad81cddd7357bd87cf2f8a0de

Both are space-related changes and thus inherently suspicious. Given we only have a single production device to repro this on, we'll need to build a few different variants that are prod-key signed to try and narrow down at least the commit that regressed behavior. Actually root causing this will require a bit of intuition.

**Comment by BenHenning** [comment] 2021-09-23 01:11
I can repro this on my Nexus 5X: install Microsoft Swiftkey Keyboard & open any text input layout in portrait (landscape works "fine"*). We should be able to root cause this now since we can repro on dev builds.

*it looks bad, but it's functional.

Edit: from searching it seems like other people do hit this issue with the keyboard, but not broadly. We're probably doing something to cause the layout to force the keyboard closed, but I'm not sure that I understand what that could be.

**Comment by BenHenning** [comment] 2021-09-23 01:24
@anandwana001 could you please work on root causing this (i.e. via a binary search) & finding the cause PR? I suspect we won't be able to revert whatever caused this, but finding the actual PR might make it easier to fix the problem.

**Comment by anandwana001** [comment] 2021-09-24 06:18
@BenHenning I tried over my Redmi phone with the internal testing APK and installing the Microsoft swift keyboard but was not able to repro this issue.

**Comment by BenHenning** [comment] 2021-09-27 09:11
Ack @anandwana001.

@srushtirk my inclination is to not block MR3 on this issue. We should still investigate & try to find the root cause PR, and fix the issue, but if someone runs into it we can tell them how to mitigate (i.e. use a different keyboard). Do you agree?

**Comment by srushtirk** [comment] 2021-09-27 19:17
Agreed!

**Comment by BenHenning** [comment] 2022-06-10 01:29
For searching context, this issue was found in 0.6-alpha (MR3).

**Comment by KevinGitonga** [comment] 2022-10-05 12:42
@BenHenning @srushtirk not able to repro this on pixel 3xl even while using Microsoft swiftkey keyboard as input method.

https://user-images.githubusercontent.com/20886444/194062060-3cefe070-347d-4d53-bb66-1a4be8e3c684.mp4

**Comment by BenHenning** [comment] 2022-10-11 02:08
Thanks @KevinGitonga. I'll need to see if I can still repro the issue locally as it may be tied to device size.

**Comment by BenHenning** [comment] 2022-10-19 08:28
Confirming I also cannot repro this anymore, so I think we can close this. Thanks @KevinGitonga!

**Closed as not planned by BenHenning** 2022-10-19 08:28 UTC
Labels: Impact: Medium, Z-ibt

**Comment by KolliAnitha** [comment] 2022-11-14 06:45
Unable to repro this issue in beta 0.10-beta-5e64fae55e
