### ISSUE TITLE
For few of the questions in explorations the hints provided are numbered randomly

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4343] opened 2022-05-05 12:50 UTC
**Describe the bug**
For few of the questions in explorations the hints provided are numbered randomly

**To Reproduce**
1. Go to 'Ratios'
2. Click on 'Multiplication'
3. Click on Continue to get to the question page 'how many petals there are on the flowers'
4. Wait for hint

**Expected behavior*
Hint 1 should be displayed instead of hint 6

Actual Result:
Hint 6 is seen 

![Screenshot_2022-04-29-18-21-47-60_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/166926997-b1f00169-5def-4bcd-ad55-b61f2a5ec42f.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment] 2022-05-06 20:16
Ah, I was aware of this but I don't think we had an issue to track it--thanks @KolliAnitha.

The problem here is that we're currently use the content ID of the hint as its header which is incorrect. We should instead be numbering the headers in a localization-friendly way.

I think this is a good starter issue material, but marking it as a 'second issue' since the APIs for localization can be a bit tricky to learn.

**Comment by BenHenning** [comment] 2022-06-10 17:18
For searching context, this issue was found in 0.7-alpha (MR4).

**Comment by Ryggs** [comment] 2022-08-23 14:34
For developers, here are instructions for reproducing the bug on the develop branch ( or any branch you're working on based off develop)
Steps to reproduce blocker issue:

1. Click Topic Ratios and Proportions.
2. Click to Expand topic.
3. Click and work exercises in “Order is important”

**Comment by Ryggs** [comment] 2022-09-21 17:16
@BenHenning , 
- I have downloaded the release assets as per the directions in this 
"Downloading production assets for testing release bugs" document.

- Successfully build and run the app, as shown.
https://user-images.githubusercontent.com/31986629/191573742-48cafb41-5987-4b19-a54b-7fb0c7d45310.mp4

- Completed all the exercises under ratios, and have not come across any flower/petal-related questions or hints, as described in this issue.

![WhatsApp Image 2022-09-21 at 20 00 06](https://user-images.githubusercontent.com/31986629/191567500-9fbba5f9-4795-4d7c-a9bb-76d25aeca5a2.jpeg)

- Opened the whole folder in vs code. Search globally “content_id”:”hint_15”, and “content_id”:”hint_6”. 
- To show you that some hint content_id’s are not orderly numbered, some start from 6 then 7 or 14, 15. So maybe this could just be a numbering issue in the JSON files.  As shown in the images below.

![hint7](https://user-images.githubusercontent.com/31986629/191568351-439870cd-3b84-47df-b811-debe7bca22f1.PNG)

![hint16](https://user-images.githubusercontent.com/31986629/191569228-4e396a93-fde5-4144-b617-fd127554dd02.PNG)

![WhatsApp Image 2022-09-14 at 15 46 14 (2)](https://user-images.githubusercontent.com/31986629/191570428-1e2127b2-e256-47a1-a840-285522d34308.jpeg)


![WhatsApp Image 2022-09-21 at 20 01 00](https://user-images.githubusercontent.com/31986629/191567635-349542e8-8916-4394-9ec4-3ea72d7e7467.jpeg)

I cannot seem to find the hint text in the issue in the release assets folder. 
Perform a search in vs code and type in petal or the text in the photo, assigned with this issue, 
you will notice its absence. 

Suggestion: This issue may just be fine the way it is, or the hint numbering in the JSON files is needed.

**Comment by BenHenning** [comment] 2022-09-22 20:09
@Ryggs this issue isn't fine the way it is because learners will encounter hint numbers that don't make sense to them. This comes from the fact that we're using the content IDs today for the hint name header, but content IDs are never meant to be shown to the user (so there's nothing to actually change in the lessons themselves). We should, instead, be displaying the hint number based on _which_ hint it is, rather than based on its content ID.

**Comment by ma-za-kpe** [comment] 2022-09-23 17:37
This makes things much clear, thank you.

**Closed as completed** 2022-10-10 23:39 UTC
Labels: Impact: Medium, Z-ibt

**Comment by KolliAnitha** [comment] 2022-11-14 09:56
Verified in beta build 0.10-beta-5e64fae55e. Observed for couple of questions the hints are numbered orderly
![Screenshot (Nov 14, 2022 2_38_05 PM)](https://user-images.githubusercontent.com/101634267/201630360-5978ca70-6865-4c4e-9ed9-847f1c4027ff.jpg)
