### ISSUE TITLE
[RTL] High-fi On home screen, username comes before the salutation

### ISSUE THREAD

**Issue by ForgottenProgramme** [oppia/oppia-android#2229] opened 2020-12-06 11:28 UTC
**Describe the bug**
On the home screen, the username comes before the greeting/salutation ('good afternoon' etc).

**To Reproduce**
1. Force RTL layout on device
2. Launch app
3. Click on any user profile to reach the home screen.

**Expected behavior**
The user name should come after the greeting.

**Screenshots**

![space_rtl](https://user-images.githubusercontent.com/65779580/101278848-2b180e00-37e4-11eb-905c-7df9a55a4f67.png)

![space_greeting_name](https://user-images.githubusercontent.com/65779580/101278711-67973a00-37e3-11eb-8714-836d1763ba42.png)

**Device**
- Pixel 2 
-  API 28 2

**Additional context**
There is also a lot of unnecessary space between the  username and the greeting, which shouldn't be there.

**Comment by anandwana001** [comment] 2020-12-06 21:34
@mschanteltc Adding you for your input on how to proceed with this issue.

**Comment by mschanteltc** [comment] 2020-12-10 00:38
@anandwana001 It's strange that in the screenshots, the names start on a new line but are offset for some reason. Does this problem occur in a RTL language?

**Comment by anandwana001** [comment] 2020-12-10 08:56
> @anandwana001 It's strange that in the screenshots, the names start on a new line but are offset for some reason. Does this problem occur in a RTL language?

@ForgottenProgramme Could you please verify this and update the issue accordingly.

**Comment by ForgottenProgramme** [comment] 2020-12-10 09:51
> @anandwana001 It's strange that in the screenshots, the names start on a new line but are offset for some reason. Does this problem occur in a RTL language?

Hey, @mschanteltc !
I didn't quiet understand what you are trying to say. In the screenshots, the name is not on a newline.

**Comment by mschanteltc** [comment] 2020-12-10 20:49
> > @anandwana001 It's strange that in the screenshots, the names start on a new line but are offset for some reason. Does this problem occur in a RTL language?
> 
> Hey, @mschanteltc !
> I didn't quiet understand what you are trying to say. In the screenshots, the name is not on a newline.

You're right, it was the trick of the eye for me! 

The fix here is to lessen the gap between the name and the greeting. Does this problem still occur in RTL languages?

**Comment by ForgottenProgramme** [comment] 2020-12-11 17:26
> > > @anandwana001 It's strange that in the screenshots, the names start on a new line but are offset for some reason. Does this problem occur in a RTL language?
> > 
> > 
> > Hey, @mschanteltc !
> > I didn't quiet understand what you are trying to say. In the screenshots, the name is not on a newline.
> 
> You're right, it was the trick of the eye for me!
> 
> The fix here is to lessen the gap between the name and the greeting. Does this problem still occur in RTL languages?

Just lessen the gap? Shouldn't the name come AFTER the greeting?

**Comment by mschanteltc** [comment] 2020-12-12 00:34
> > > > @anandwana001 It's strange that in the screenshots, the names start on a new line but are offset for some reason. Does this problem occur in a RTL language?
> > > 
> > > 
> > > Hey, @mschanteltc !
> > > I didn't quiet understand what you are trying to say. In the screenshots, the name is not on a newline.
> > 
> > 
> > You're right, it was the trick of the eye for me!
> > The fix here is to lessen the gap between the name and the greeting. Does this problem still occur in RTL languages?
> 
> Just lessen the gap? Shouldn't the name come AFTER the greeting?

Yes the name should come after the greeting, and since this is in RTL layout, the name should be left of the greeting.

**Comment by ForgottenProgramme** [comment] 2020-12-12 08:53
> > > > > @anandwana001 It's strange that in the screenshots, the names start on a new line but are offset for some reason. Does this problem occur in a RTL language?
> > > > 
> > > > 
> > > > Hey, @mschanteltc !
> > > > I didn't quiet understand what you are trying to say. In the screenshots, the name is not on a newline.
> > > 
> > > 
> > > You're right, it was the trick of the eye for me!
> > > The fix here is to lessen the gap between the name and the greeting. Does this problem still occur in RTL languages?
> > 
> > 
> > Just lessen the gap? Shouldn't the name come AFTER the greeting?
> 
> Yes the name should come after the greeting, and since this is in RTL layout, the name should be left of the greeting.

Yes, you are right. That would be the case if our text was in some Arabic language. But this is still English and not Arabic. 
Here, have a look at this other screen in the app where RTL support has been added:
![port_mob_faq](https://user-images.githubusercontent.com/65779580/101979685-1674c380-3c85-11eb-801c-fe1b5fc25212.png)

The text is aligned to the right, but it is still read from Left to Right.

**Comment by mschanteltc** [comment] 2020-12-15 01:39
I'm confused as to why we're implementing RTL for the English language. If the app language were English, then it should always be LTR. 
@anandwana001 Is it possible you can elaborate what the issue is?

**Comment by ForgottenProgramme** [comment] 2020-12-15 08:46
@rt4914

**Comment by ForgottenProgramme** [comment] 2020-12-15 09:00
@mschanteltc ,
I think we are trying to make sure our app looks and works fine even when the user forces RTL layout on the device (under Developer Options).
@anandwana001  and @rt4914  will know better about this.

**Comment by rt4914** [comment] 2020-12-22 06:18
> I'm confused as to why we're implementing RTL for the English language. If the app language were English, then it should always be LTR.
> @anandwana001 Is it possible you can elaborate what the issue is?

@mschanteltc We are not implementing the RTL for English language we are just fixing code so that it supports RTL. As of now we do not have any other language in app and therefore we have to treat english language as RTL language to support RTL layouts. This is just for testing purposes.

@ForgottenProgramme Mostly using the `android:textAlignment="viewStart"` for the profile name should fix this issue. Thanks.

**Comment by ForgottenProgramme** [comment] 2020-12-22 08:02
@rt4914 , should I fix this or mark it as 'good first issue' and let someone new do this?

**Comment by rt4914** [comment] 2020-12-22 08:03
> @rt4914 , should I fix this or mark it as 'good first issue' and let someone new do this?

Either one is fine.
My personally suggestion is that you fix this because I think HomeScreen RTL is sort of the hardest one.

**Comment by ForgottenProgramme** [comment] 2020-12-22 14:19
Yes, @rt4914. Okay.
The extra space between the greeting and the user name is removed when RTL support is added to profile_name_textview.
The 'greeting' and the 'user name' are two different textviews. And RTL leads to a mirroring effect. In LTR 'greeting' comes before 'profile name', hence in its mirror image (RTL), 'greeting' is coming after the 'profile name'. 

What if we merge the two into a single textview? That should do the trick? What are your views? 

Also, look at this,
![orange](https://user-images.githubusercontent.com/65779580/102897880-b6ed9380-448e-11eb-903b-1033f4af9171.png)

What's this orange bar below the greeting?

**Comment by rt4914** [comment] 2020-12-22 14:51
> Yes, @rt4914. Okay.
> The extra space between the greeting and the user name is removed when RTL support is added to profile_name_textview.
> The 'greeting' and the 'user name' are two different textviews. And RTL leads to a mirroring effect. In LTR 'greeting' comes before 'profile name', hence in its mirror image (RTL), 'greeting' is coming after the 'profile name'.
> 
> What if we merge the two into a single textview? That should do the trick? What are your views?
> 
> Also, look at this,
> ![orange](https://user-images.githubusercontent.com/65779580/102897880-b6ed9380-448e-11eb-903b-1033f4af9171.png)
> 
> What's this orange bar below the greeting?

@ForgottenProgramme We cannot merge the text views because of the **orange** underline below the greetings which we won't be able to control if we have a single text view. Reference PR: https://github.com/oppia/oppia-android/pull/2186

**Comment by FareesHussain** [comment] 2020-12-28 07:34
@rt4914 PTAL https://github.com/oppia/oppia-android/pull/2330#pullrequestreview-559009139

**Comment by ForgottenProgramme** [comment] 2020-12-31 09:08
![as](https://user-images.githubusercontent.com/65779580/103403333-b8e1e180-4b75-11eb-8ba2-b06f324583e6.png)


Appears to be fixed with pseudolocale turned on.

**Comment by rt4914** [comment] 2020-12-31 11:49
Closing this as per https://github.com/oppia/oppia-android/issues/2229#issuecomment-752897285

**Closed as completed by rt4914** 2020-12-31 11:49 UTC
Labels: Z-ibt
