### ISSUE TITLE
Unable to select a profile image from the gallery while Adding profile

### ISSUE THREAD

**Issue by shubham419** [oppia/oppia-android#4806] opened 2022-12-27 11:10 UTC
**Describe the bug**
when we select a image from gallery while adding new profile, And after that click on **create**  button it does not responce and new profile is not added.

**To Reproduce**
1. open app
2. Click on add profile button
3. enter administrator's pin
4. click on round profile image view
5. select image from gallery
6. enter name
7. and click create button

**Expected behavior**
It shuld successfully create new user with the choosen profile image.

**Demonstration**

https://user-images.githubusercontent.com/63647613/209657829-1e4c3a97-ae40-461e-8699-dd12d8651e6a.mp4

**Environment**
- Device/emulator being used: POCO X2
- Android : Android 11
- App version : 1

**Comment by shubham419** [comment] 2022-12-27 11:16
Hi i come across this issue, and i tried to solve it and also find easy solution for #4803 issue.

**Comment by ShubhadeepKarmakar** [comment] 2022-12-27 11:43
Hey, can I work on it?

**Comment by shubham419** [comment] 2022-12-27 13:20
@ShubhadeepKarmakar I have created a pull request, check whether my solution is correct or not

**Comment by BenHenning** [comment] 2023-01-11 01:14
Just to clarify @shubham419 is it the case that the create button isn't doing anything when tapped after selecting a profile image? And to check: are you able to create profile images when not selecting a profile image?

**Comment by SidharthMudgil** [comment] 2023-02-15 14:49
Can you assign this issue to me?

**Comment by seanlip** [comment] 2023-02-15 15:39
@SidharthMudgil Please follow the instructions [here](https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android#finding-something-to-do) for claiming an issue. You will need to provide an explanation of how you would fix it, and (if possible) a demo of the working fix.

I would also recommend reading and following the other instructions on that page if you haven't already done so. Thanks!

**Comment by ShubhadeepKarmakar** [comment] 2023-02-16 19:31
Hey is it fixed? If not, then I would like to work on it.

**Comment by seanlip** [comment] 2023-02-17 08:27
@ShubhadeepKarmakar See my previous comment in this thread for instructions on how to claim an issue.

You should be able to check directly on your local version of the app whether it is fixed or not.

**Comment by SidharthMudgil** [comment] 2023-02-23 09:10
@BenHenning Hi, I also come up with this solution https://github.com/oppia/oppia-android/pull/4808, it works can you tell me why it was not merged so I can focus on that

**Comment by BenHenning** [comment] 2023-02-28 01:38
> @BenHenning Hi, I also come up with this solution #4808, it works can you tell me why it was not merged so I can focus on that

@SidharthMudgil it looks like there were requested action items from both Oppiabot and me on #4808 that weren't resolved, and then the PR was closed due to inactivity.

**Comment by BenHenning** [comment] 2023-03-24 02:27
Duplicate of #4072.

**Closed as not planned by BenHenning** 2023-03-24 02:27 UTC
