### ISSUE TITLE
Talkback auto select to header text or edit text inconsistently 

### ISSUE THREAD

**Issue by vrajdesai78** [oppia/oppia-android#4654] opened 2022-10-13 17:59 UTC
**Describe the bug**
When we open Authorize to add profiles screen or forgot pin dialog, talkback reader auto-selects focus inconsistently i.e. in some device it selects header text and in some devices it select edit text which is inconsistent. 

**To Reproduce**
Steps to reproduce the behavior (For Authorize to add profile screen):
1. Turn on talkback reader
2. Click on Set Up Multiple Profile Select your profile screen

Steps to reproduce the behavior (For forgot pin dialog):
1. Click on Add profile (If you haven't set up admin password then you need to click on Set Up Multiple Profile and set Admin Pin First)
2. Turn on Talkback reader.
3. Click on Forgot Pin.

**Expected behavior**
Talkback reader should auto select focus consistently on all devices. 

**Demonstration**

https://user-images.githubusercontent.com/43074241/195673859-557cf03b-f3ac-44e5-9484-60f37802ca85.mp4

**Environment**
- Device/emulator being used: Realme GT Master Edition
- Android or SDK version (e.g. Android 5 or SDK 21): Android 12
- App version (you can get this through system app settings or via the admin controls menu in-app): 1.0

**Comment by rt4914** [comment] 2022-10-25 16:10
@vrajdesai78 not part of GSoC

**Comment by rt4914** [comment] 2023-05-15 07:42
This is the correct and expected behaviour. Here are the reasons:
1. This is part of `AlertDialog` which our code does not control a lot. The output of screen-reader on this is controlled by android OS and our code does not play part in it.
2. The output is actually correct. The problem was that being a developer we are testing it for blind people but we are using our to test it and this makes it seem as if the output it wrong. Why? If you close your eyes and then hear the output (or in current video case, just focus on below text), you will notice that **it does read the header text** , the talkback does not highlight it because there is no action to be taken, but it does read the header which is exactly what we want.

Closing this as this is not an issue infact a bit optimised implementation by android OS itself.

**Closed as completed by rt4914** 2023-05-15 07:42 UTC
