### ISSUE TITLE
Bazel 4.0 not building project correctly on macOs Monterrey version 12.4

### ISSUE THREAD

**Issue by KevinGitonga** [oppia/oppia-android#4391] opened 2022-06-10 08:27 UTC
**Describe the bug**
Building project with bazel using macOs Monterrey version 12.4 on terminal fails see logs below for context

` Generating JavaLite proto_library //model/src/main/proto:event_logger_proto failed: (Segmentation fault): protoc failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc '--proto_path=bazel-out/android-armeabi-v7a-fastbuild/bin/model/src/main/proto/_virtual_imports/math_proto' ... (remaining 22 argument(s) skipped)
`

**To Reproduce**
1. Setup Oppia Android project on macOs Monterrey version 12.4 as per the docs
2. Run command `bazel build //:oppia ` on terminal
3. See error

**Expected behavior**
I expect Bazel to build project successfully and be able to generate required artifacts.

**Demonstration**
<img width="1387" alt="Screenshot 2022-06-10 at 11 17 46" src="https://user-images.githubusercontent.com/20886444/173022664-ff43745c-2cab-445c-a710-d246826262b9.png">

**Environment**
- macOs Monterrey version 12.4
- Android or SDK version 30
- App version 1.0
- Bazel Version 4.0

**Additional context**
Issue with similar specs on Bazel repository
https://github.com/bazelbuild/bazel/issues/14469

**Comment by BenHenning** [comment] 2022-06-11 01:57
Thanks for filing this @KevinGitonga.

This issue will be blocked on us being able to upgrade to Bazel 5.0 (which is the recommendation in the reference Bazel bug above). We can't do that until Bazel is moved over to using the new D8 tool (since it forces using build tools 31+ which removes the desugar compatibility tool that Bazel expects--see https://github.com/bazelbuild/bazel/issues/13989). I'm tracking the other constituent work items needed to unblock this work.

**Comment by adhiamboperes** [comment] 2023-07-27 11:42
Hey @KevinGitonga, Could you please try this build to see if it is still reproducible? @kkmurerwa had a similar issue on M1, and we were able to find a fix (unused imports in the affected models -- which seem not to be an issue with the highlighted `math.proto` currently)

**Comment by BenHenning** [comment] 2024-08-30 00:08
Similar to #3653 I suspect that this isn't an issue after #4886 was merged. Please reopen if this is still a problem.

**Closed as completed by BenHenning** 2024-08-30 00:08 UTC
Labels: Impact: Medium, Z-ibt, bug, Work: High
