### ISSUE TITLE
Talk back is reading Good Afternoon twice when the focus is on it for the first time

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4317] opened 2022-04-25 11:31 UTC
**Describe the bug**
Talk back is reading Good Afternoon twice when the focus is on it for the first time

Pre-requisite: Enable Talk back on

**To Reproduce**
1. Login to Oppia as Admin
2. Get to label 'Good Afternoon, Admin'

**Expected behavior**
Talk back should read Good Afternoon Admin

Actual Result: Talk back is reading Good Afternoon Admin, Good Afternoon

Video link: https://drive.google.com/file/d/1KyNdR7qguDPockkFkZRVYgidt5_UeAFq/view 

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

Note:
This happens only when the focus is on it for the first time.

**Comment by BenHenning** [comment] 2022-04-26 22:18
This seems like a good first issue to work on.

Assignees: I suggest enabling speech output for TalkBack so that you don't need to rely on hearing it (this can be set via TalkBack developer settings). You should first verify you can repro the exact issue on your local device/emulator. After that, a good place to start is HomeActivity (which is where the greeting is set up), and investigating the view hierarchy for any obvious tells on why the duplication is happening (e.g. perhaps we are setting the content descriptions for multiple views to the same thing). It may also be helpful to use Android Studio's layout inspector to verify the actual content descriptions set for various views in the hierarchy.

**Comment by vrajdesai78** [comment] 2022-04-28 08:17
@BenHenning I have tried to reproduce this error on my device but I didn't get this issue of reading Good Afternoon twice. I am attaching screen recording of my device.

https://user-images.githubusercontent.com/43074241/165708909-520dc592-e095-49fa-9acc-c2670d0cd953.mp4

**Comment by BenHenning** [comment] 2022-04-29 05:57
@vrajdesai78 it's a bit hard to tell from your video because the second 'Good afternoon' comes after the first one disappears. When I repro this locally, I see the following output:
- 'Good afternoon, Admin!'
- 'Good afternoon'

(in succession)

Do you not see this? If not, what device are you using? Also, could you try this on an emulator running Android 11? It would also be a good idea to try version 0.7 of the app (the same one @KolliAnitha is using) on the device where you can't repro it to see if there's a difference between the local development version and the production version.

**Comment by vrajdesai78** [comment] 2022-05-04 14:06
@BenHenning I have tested on Android 11.0 as well as on v0.6 also but still, I am not able to produce the same issue. On my device it's showing Good Afternoon, Admin one time only. 
![untitled](https://user-images.githubusercontent.com/43074241/166698597-4941c40c-a2e6-4915-a6f7-c1d191fcf127.gif)
This video is taken from Pixel 2 Android 11 and App version 0.6

**Comment by rt4914** [comment] 2022-05-06 06:24
I have checked this too and I am unable to reproduce this on current develop.

**Comment by BenHenning** [comment] 2022-05-06 10:14
@KolliAnitha can you check this again on the latest version of 0.7 MR4 (it should be going out to the test track in a few hours--I'll send a mail once it's available). It's possible this issue has gone away on its own due to other changes.

**Comment by KolliAnitha** [comment] 2022-05-06 10:17
Sure @BenHenning, I will check it in the latest version

**Comment by KolliAnitha** [comment] 2022-05-10 15:34
Verified in 0.7 MR4, I am not able to reproduce the issue now
Environment
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

**Comment by BenHenning** [comment] 2022-05-28 00:44
Ah, thanks for following back up @KolliAnitha. Glad to see 0.7 has a fix, though it's not great that we don't know exactly why it's fixed. Either way, closing this since it isn't reproducible. Please reopen if it comes up again.

**Closed as not planned by BenHenning** 2022-05-28 00:44 UTC
Labels: good first issue, Z-ibt

**Comment by BenHenning** [comment] 2022-06-10 17:21
For searching context, this issue was found in 0.7-alpha (MR4).
