### ISSUE TITLE
Focus is not going to the content when moving to the next page in Introduction slides

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4794] opened 2022-12-19 07:01 UTC
**Describe the bug**
Focus is not going to the content when moving to the next page in Introduction slides

**To Reproduce**
Enable Talkback
1. Install Oppia
2. Open Oppia app
3. Click on Next button in the Introduction slide

**Expected behavior**
Focus should go to the content in the next slide

**Demonstration**
https://user-images.githubusercontent.com/101634267/208366204-94e884ce-530d-4bdd-a098-9473ff246982.mp4

**Environment**
Device/emulator being used: Oneplus nord2 5g
Android or SDK version (e.g. Android 5 or SDK 21): Android version 12
App version (you can get this through system app settings or via the admin controls menu in-app): 0.10-beta-5e64fae55e

**Comment by BenHenning** [comment] 2022-12-19 21:34
@KolliAnitha is this the same as #4655 or are you thinking the flow should be different than what's been discussed in that issue?

**Comment by KolliAnitha** [comment] 2022-12-21 05:05
Yes @BenHenning, its the same issue as #4655

**Comment by BenHenning** [comment] 2022-12-23 03:36
Thanks for checking @KolliAnitha! Marking this as a duplicate of #4655 then.

**Closed as not planned by BenHenning** 2022-12-23 03:36 UTC
