### ISSUE TITLE
Failed to add Admin (or non-admin) Profile Picture.

### ISSUE THREAD

**Issue by ShubhadeepKarmakar** [oppia/oppia-android#4803] opened 2022-12-24 09:30 UTC
**Describe the bug**
Whenever I try to change admin profile picture or basically setup, I get redirected to gallery but after selecting approximate picture I go back to the previous section (profile progress activity) but the profile picture is not set.

**To Reproduce**
1. Go to app drawer.
2. Click on Admin Profile Picture
3. Then again click on the profile picture and then click 'Choose From Gallery' option.
4. Select any image from gallery.
5. See the error: Admin Profile Picture is not.

**Demonstration**
https://user-images.githubusercontent.com/99060332/209429780-72e28ad6-7de1-4dd5-9f2a-5dda875cfe9f.mp4
**Environment**
- Device being used: Redmi Note pro
- Android version: Android 11
- App version: 0.10-beta

**Comment by BenHenning** [comment] 2023-01-11 01:16
Thanks @ShubhadeepKarmakar. This looks closely related to #4806 (and probably has the same root cause).

**Comment by nawaz-anwar** [comment] 2023-02-05 12:07
Please assign it to me I know to handle this. Whenever the user tries to change the admin profile picture, the app is redirecting to the gallery, but after selecting an image and returning to the previous section, the profile picture is not set.

**Comment by seanlip** [comment] 2023-02-05 16:09
@nawaz-anwar Thanks for your interest in this issue. Could you please provide an explanation of what exactly your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue.

Thanks!

**Comment by nawaz-anwar** [comment] 2023-02-06 11:52
@seanlip I have gone through the problem-solving process and found a solution that worked. I have documented the solution in the form of a video, which I would like to share with you.

Video Link: https://drive.google.com/file/d/1UQEiJD55ck9Mjl5JJKw0O6miYLfY8ncf/view

**Comment by seanlip** [comment] 2023-02-06 14:49
@nawaz-anwar I'm not quite sure what app you're using, but the app shown in the video is not the Oppia android app.

**Comment by nawaz-anwar** [comment] 2023-02-07 07:25
@seanlip @BenHenning  I have successfully resolved the issue with the failed admin profile picture. As shown in the attached video, the problem has been fixed. May I request for a code merge?

Video Link: https://drive.google.com/file/d/1UaXZ61hW-3lGEcSSrqqQNg1mSRPTuSGm/view

**Comment by seanlip** [comment] 2023-02-07 12:25
Hi @nawaz-anwar -- yup, please go ahead and make a PR. Thanks!

**Comment by seanlip** [comment] 2023-02-07 12:26
@nawaz-anwar That said -- please make sure to follow the instructions here first, too, otherwise your PR may be closed by Oppiabot: https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android . Thanks!

**Comment by nawaz-anwar** [comment] 2023-02-07 13:49
> @nawaz-anwar That said -- please make sure to follow the instructions here first, too, otherwise your PR may be closed by Oppiabot: https://github.com/oppia/oppia-android/wiki/Contributing-to-Oppia-android . Thanks!



> Hi @nawaz-anwar -- yup, please go ahead and make a PR. Thanks!

@seanlip When I attempted to create a pull request, I received an error message saying "permission denied".
<img width="927" alt="Screenshot_20230207_191047" src="https://user-images.githubusercontent.com/95420628/217261403-b386894f-6750-419d-bd29-4fdf3e695410.png">

**Comment by seanlip** [comment] 2023-02-07 14:00
Please make sure to follow all the steps on the page I linked you to, from top to bottom.

**Comment by nawaz-anwar** [comment] 2023-02-08 06:08
> Please make sure to follow all the steps on the page I linked you to, from top to bottom.

@seanlip Can't create a new pull request: Push failed: remote: Permission to oppia/oppia-android.git denied to nawaz-anwar. unable to access 'https://github.com/oppia/oppia-android.git/': The requested URL returned error: 403

**Comment by seanlip** [comment] 2023-02-08 06:10
From the docs I linked you, which step exactly are you following and which command are you running when you get the error?

**Comment by nawaz-anwar** [comment] 2023-02-08 06:19
@seanlip While pushing my branch using this command " git push --set-upstream origin <my-branch-name>.

**Comment by seanlip** [comment] 2023-02-12 09:48
@nawaz-anwar I don't see the command you're running in the wiki page: https://github.com/oppia/oppia-android/wiki/Guidance-on-submitting-a-PR

Could you please point out which step you are following and which instruction in that page doesn't work? If you don't follow these steps but use some other commands, you might run into unexpected issues.

(It might also be better to have this discussion on GitHub Discussions instead if you are running into generic issues with git that aren't related to this issue in particular -- there are more people looking at those boards who can help you faster.)

**Comment by BenHenning** [comment] 2023-03-24 02:29
Per #4906 this will also affect non-admins.

**Comment by ShubhadeepKarmakar** [comment] 2023-08-05 12:56
Hey @adhiamboperes I have the solution, if you don't work on it, can I be responsible??
Just two lines of codebase changes and things will be fine.

**Comment by ShubhadeepKarmakar** [comment] 2023-08-06 15:02
I have made the PR, @adhiamboperes please review it.

**Closed as completed** 2023-08-10 03:13 UTC
Labels: Impact: Low, bug, Work: Low
