### ISSUE TITLE
Math expressions can be cut off when they're at the bottom of the card

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#3003] opened 2021-03-24 19:28 UTC
**Describe the bug**
Math expressions can be cut off when they're at the bottom of the card, likely due to the extra translation that we're doing.

**To Reproduce**
1. Play through most of 'The meaning of Equal Parts" Fractions lesson
2. Reach the state starting with "Mr. Baker chuckled"
3. Scroll to the bottom of the content card
4. Observe that the 1/2 + 1/4 is being partially cut-off

**Expected behavior**
The text box should grow (or have a bit of extra padding) to make up for potential LaTeX vertical space. We may just need to bake the vertical alignment into that drawable's bounds.

**Screenshots**
![image](https://user-images.githubusercontent.com/12983742/112371993-77586280-8c9c-11eb-8221-2eb19be73d42.png)

**Device**
- Device being used: Nexus 5X
- SDK version: 27

**Additional context**
Found during alpha MR2 testing.

**Comment by imraghav20** [comment] 2021-03-26 12:03
@BenHenning check if the issue is resolved. In my device it looks perfect both in portrait and landscape mode.

![WhatsApp Image 2021-03-26 at 5 30 39 PM](https://user-images.githubusercontent.com/59257038/112628715-45402f80-8e59-11eb-925a-ce195374dd24.jpeg)
<br>
![WhatsApp Image 2021-03-26 at 5 30 39 PM (1)](https://user-images.githubusercontent.com/59257038/112628714-440f0280-8e59-11eb-9fd0-5a94678bdc19.jpeg)

**Comment by anandwana001** [comment] 2021-05-11 08:12
@rt4914 adding you if this comes under content UI part.

**Comment by adhiamboperes** [comment] 2022-11-29 10:55
For the concept card explanation text in `concept_card_fragment.xml`, the images are no longer truncated as this was resolved in #4669
|5.6", dev|6.7", beta|
|---|---|
|![Screenshot_1669718695](https://user-images.githubusercontent.com/59600948/204509818-1f6f9130-f875-4b10-a2be-8a216f935cc2.jpg)|![Screenshot_2022-11-29-13-42-42-480_org oppia android](https://user-images.githubusercontent.com/59600948/204511871-78f40f01-e648-4a7b-99a9-31f8319a3953.jpg)|

**Comment by seanlip** [comment] 2023-03-28 15:54
@adhiamboperes Just to check, do you mean that the original issue has been fixed?

(If not, which part of it is not fixed?)

**Comment by adhiamboperes** [comment] 2023-03-29 03:51
@seanlip yes this was fixed, I can nolonger reproduce this issue in the latest versions of dev and beta.

**Comment by seanlip** [comment] 2023-03-30 19:13
Great, thanks! Closing it, then.

**Closed as completed by seanlip** 2023-03-30 19:13 UTC
Labels: Impact: Medium, Z-ibt, bug
