### ISSUE TITLE
After clicking on logout user is taken to profile selection page

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4324] opened 2022-04-27 12:05 UTC
**Describe the bug**
After clicking on logout user is taken to profile selection page

**To Reproduce**
1. Go to 'Administrator Controls'
2. Go to Account Actions
3. Tap on Log Out

**Expected behavior**
  If the user logs out of the application login page should be seen

Actual Result:
On clicking the log out button user is taken to profile selection page

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.7-alpha-d1b2827517

https://user-images.githubusercontent.com/101634267/165514513-e3ace9f8-0389-4882-af60-6e2152383d0c.mp4

**Comment by BenHenning** [comment] 2022-04-29 06:12
Since we don't yet have an actual registration or login flow built yet, this is actually the intended behavior @KolliAnitha. I think you can go ahead and update the regression test cases to match this as the expected outcome, and follow-up once done so that I can close this. Does this sound good or do you have any doubts?

**Comment by KolliAnitha** [comment] 2022-04-29 11:11
If that's the intended behavior we can close this issue i will update the test cases as per this behavior

**Comment by BenHenning** [comment] 2022-05-03 21:26
Thanks @KolliAnitha. In that case, closing this issue.

**Closed as completed by BenHenning** 2022-05-03 21:26 UTC
Labels: Z-ibt

**Comment by BenHenning** [comment] 2022-06-10 17:21
For searching context, this issue was found in 0.7-alpha (MR4).
