### ISSUE TITLE
[BUG]: Missing Text Margins In Topic Revision Cards in Large Screens

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5120] opened 2023-08-06 06:36 UTC
### Describe the bug

Unlike in small screens, the tablet UI of revision cards does not have any margins/padding.

| Small screen | Tablet|
| ------ | ------ |
|![Screenshot_1691303581](https://github.com/oppia/oppia-android/assets/59600948/0225c760-efef-4a2d-b6b3-64a4a1616609)| ![Screenshot_1690255965](https://github.com/oppia/oppia-android/assets/59600948/2c712138-4e1d-462a-bd93-8f3684258bcf)|

### Steps To Reproduce

Install Oppia on a real tablet or emulator such as a Nexus 9 device.
On a profile home screen, click on any topic.
On the topic list screen, switch to the Revision tab and observe that there is no margin.

### Expected Behavior

There should be some text margin.

**Comment by pingu-73** [comment] 2023-08-08 13:23
I've reproduced the above error:
![padding and margin](https://github.com/oppia/oppia-android/assets/121669947/d370ef6d-ef89-4f60-b2a2-1b9ab06ff6a2)

I think the issue is with layer layout ID: 
<img width="1316" alt="Screenshot 2023-08-09 at 12 35 43 AM" src="https://github.com/oppia/oppia-android/assets/121669947/6f5b948a-a706-452b-a8ef-929e6cae2ddf">


@adhiamboperes I'm new to android development but I'm eager to learn it, **can you assign this issue to me** and guide me through.
Thanks

**Comment by pingu-73** [comment] 2023-08-08 19:07
@adhiamboperes @MohitGupta121 can you please assign me this issue and guide me through.

**Comment by adhiamboperes** [comment] 2023-08-08 19:16
> @adhiamboperes I'm new to android development but I'm eager to learn it, **can you assign this issue to me** and guide me through. Thanks


I do not understand what you mean by layout id(can you explain why you think it is causing an issue?). The screen needs a layout margin, either in the parent layout or the textview displaying the text itself(do you understand margins in android layouts?). You can check how margin is implemented for the same layout in small devices (same layout name, but without "land/" before it). Please also read about how to find things in the codebase [here](https://github.com/oppia/oppia-android/wiki/Overview-of-the-Oppia-Android-codebase-and-architecture#codebase-walkthrough).

**Comment by pingu-73** [comment] 2023-08-08 19:49
@adhiamboperes What I meant was that the issue is within the following file 
oppia-android>app>src>main>res>layout>revision_card_fragment.xml

**Comment by adhiamboperes** [comment] 2023-08-08 20:04
@pingu-73 could you please put up a PR with your solution?

**Comment by pingu-73** [comment] 2023-08-08 20:06
@adhiamboperes I haven't done it yet, can you please tell if my approach is correct or not?
So I could start working on it
Thanks

**Comment by adhiamboperes** [comment] 2023-08-08 20:10
@pingu-73 the file is correct but what change do you plan to make on it?

**Comment by pingu-73** [comment] 2023-08-08 20:13
I'm new to Android dev. So,I've to go through documentation of kotlin I will let you know about the changes by tomorrow,
if that's fine?

**Comment by adhiamboperes** [comment] 2023-08-08 20:15
> I'm new to Android dev. So,I've to go through documentation of kotlin I will let you know about the changes by tomorrow, if that's fine?


Please read this doc: https://developer.android.com/develop/ui/views/layout/declaring-layout#write.

**Comment by pingu-73** [comment] 2023-08-08 20:20
@adhiamboperes can you please assign this task to me.

**Comment by kkmurerwa** [comment] 2023-08-08 21:49
Hi @pingu-73, I believe Adhiambo wants you to give a breakdown of how you intend to fix the issue. We know that the issue is most likely in the `revision_card_fragment.xml` but how would you fix it? 
You can either try it out and send a PR with a fix or send a screenshot here showing that you attempted a solution and it fixed the issue.

**Comment by pingu-73** [comment] 2023-08-09 02:55
@adhiamboperes 
initial view:
<img width="1395" alt="Screenshot 2023-08-09 at 8 22 58 AM" src="https://github.com/oppia/oppia-android/assets/121669947/8353e1a4-3f3a-4236-a21b-151090712085">

view after making changes:
<img width="1397" alt="Screenshot 2023-08-09 at 8 21 57 AM" src="https://github.com/oppia/oppia-android/assets/121669947/86bf2751-7773-4cda-a784-94f1420e0480">

changes made:
I've added left and right margins of 8dp. @adhiamboperes Is this approach right?

**Comment by ShubhadeepKarmakar** [comment] 2023-08-09 10:12
I have made the PR, @adhiamboperes @kkmurerwa please review it.

**Comment by adhiamboperes** [comment] 2023-08-09 10:14
Thanks @ShubhadeepKarmakar, but @pingu-73 is working through this issue. If you would like to work on an issue please request to be assigned to it.

**Comment by ShubhadeepKarmakar** [comment] 2023-08-09 10:17
Oh! really sorry for that, it would not happen again.

**Comment by adhiamboperes** [comment] 2023-08-09 10:29
> changes made: I've added left and right margins of 8dp. @adhiamboperes Is this approach right?

Hi @pingu-73, not quite. You have added margins to the wron view. Please refer again to my comment:

The screen needs a layout margin, either in the parent layout or the textview displaying the text itself(@id/revision_card_explanation_text). 

You can check how margin is implemented for the same layout in small devices (revision_card_fragment, but without "land/sw-600dp" before it). 

Note: 
1. Deploy your changes on the emulator(nexus 9 api 29 tablet) to see if your fix worked.
2. We use margin start/end, not left/right
3. big screen layouts are prefixed with either layout-land or layout-sw600dp. The changes you have made are actually on the small screen layout.

**Comment by ShubhadeepKarmakar** [comment] 2023-08-09 10:38
@pingu-73 you can also go through my pr to see the exact point.

**Comment by pingu-73** [comment] 2023-08-09 11:46
@adhiamboperes please review my [pull request](https://github.com/oppia/oppia-android/pull/5127)

**Closed as completed** 2023-08-10 13:45 UTC
Labels: good first issue, Impact: Low, bug, Work: Low
