### ISSUE TITLE
Chapter progress not immediately visible after completing exploration

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1048] opened 2020-05-09 20:48 UTC
After completing an exploration & navigating back to the topic page, the chapter isn't marked as complete without restarting the activity.

**Comment by ArpitShukIa** [comment] 2021-03-13 18:26
@rt4914 Are you working on this?

**Comment by rt4914** [comment] 2021-03-15 12:55
@ArpitShukIa Actually I am not working for now. I am assigning this to you. But do make sure that this is still an issue because it might have happened that it got solved in some other PR earlier. Thanks.

**Comment by ArpitShukIa** [comment] 2021-03-16 12:09
@rt4914 Looks like the issue has already been fixed. Progress is updated immediately after completing the exploration.
Please verify it once on your side. If the issue still exists, please tell the steps to reproduce it.

**Comment by rt4914** [comment] 2021-03-17 16:02
Yeah, I thought so too. Closing this as it is fixed in some other PR.

**Closed as completed by rt4914** 2021-03-17 16:02 UTC
Labels: Priority: Essential, Z-ibt
