### ISSUE TITLE
Voiceover changed from English to some other language

### ISSUE THREAD

**Issue by dika1osune** [oppia/oppia-android#4016] opened 2021-11-30 13:44 UTC
**Describe the bug**
Young learner was going through the lessons on an Android device (not sure what version it is). The voiceover feature was in use, suddenly the language changed. I asked for the phone to check the language options to see if the child flipped a switch, but the selected option was still English.

**To Reproduce**
I have not been able to reproduce the error

**Expected behavior**
Voiceover feature isn't expected to switch languages midway through the lessons

**Demonstration**
If applicable, add screenshots or videos to help explain your problem.

**Environment**
- Device/emulator being used: Android device
- Android or SDK version (e.g. Android 5 or SDK 21): <os/sdk version>
- App version MR4

**Additional context**
Young learner was going through the Fractions Lesson (chapter 1)

**Comment by BenHenning** [comment] 2021-12-07 20:48
Thanks @dika1osune. This is really helpful additional context for #3088.

I suspect that this is a duplicate of #3088, so closing as such.

**Closed as completed by BenHenning** 2021-12-07 20:48 UTC
Labels: Z-ibt
