### ISSUE TITLE
[Mobile-Portrait] High-fi StoryActivity Updated UI with lock and blur effect.

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#2054] opened 2020-10-29 07:12 UTC
The `StoryActivity`  UI has been updated a lot which is available here. https://xd.adobe.com/view/e8aa4198-3940-47f9-514a-f41cc54457f6-9e9b/screen/5abb0ace-19ee-48b8-8154-919154f924d2/

Major changes:
- [ ] Blur effect and lock icon on the inactive cards.

Paw icon: https://drive.google.com/file/d/1aHLklyfrwdWfVUm-Lc7ITlyspRl9-DnU/view?usp=sharing

**Comment by KMaragh** [comment] 2020-11-16 16:31
I can take a look at this!

**Comment by KMaragh** [comment] 2020-12-01 16:11
@rt4914 Finally have some time to look at this. Is the expectation to change the Story chapter's image that are missing prerequisites to the blur effect and lock icon?

And change the chapter complete icon to the paw instead of the checkmark?

**Comment by rt4914** [comment] 2020-12-04 20:17
> @rt4914 Finally have some time to look at this. Is the expectation to change the Story chapter's image that are missing prerequisites to the blur effect and lock icon?
> 
> And change the chapter complete icon to the paw instead of the checkmark?

@KMaragh Paw icon is not needed for this PR. Mainly focus on Inactive Card blur effect and the lock icon.

**Comment by anandwana001** [comment] 2020-12-22 03:13
unassigning @KMaragh as no further update. 
Closing this issue as it's a duplicate of https://github.com/oppia/oppia-android/issues/2132

**Closed as completed by anandwana001** 2020-12-22 03:13 UTC
Labels: Priority: Essential, Type: Task, Z-ibt
