### ISSUE TITLE
Add dark mode for Topic lessons tab

### ISSUE THREAD

**Issue by JishnuGoyal** [oppia/oppia-android#4599] opened 2022-09-17 18:42 UTC
Add dark mode support for the new recycler view design introduced in #4535.

**Comment by MohitGupta121** [comment] 2022-11-29 16:48
This issue is a duplicate of #4624 and work started on that issue.
So I'm closing this issue to avoid confusion.

**Closed as not planned by MohitGupta121** 2022-11-29 16:48 UTC
